### ISSUE TITLE
Running tfsec multiple times gives different results on AWS099

### ISSUE THREAD

**Issue by fliphess-nhb** [aquasecurity/tfsec#1003]
**Describe the bug**

My pipeline sometimes fails on `aws-iam-no-policy-wildcards (AWS099)`.
I run tfsec with the following arguments: `tfsec --config-file .tfsec.yml`

But the strangest is: If I run my pipeline again, it succeeds without errors.... 

Running tfsec outside the ci pipeline on my local machine, (in both ci and local I run version `v0.56.0`), I get the same behaviour: If I run tfsec 10 times, it fails about 2 times and succeeds 8 times on the same code block. 

In some cases the error is printed several times (as different problems) for the same codeblock, rather than just only ones.

Output of tfsec failing on KMS resource policy:
```
  Result 1
  [aws-iam-no-policy-wildcards][HIGH] Resource 'data.aws_iam_policy_document' defines a policy with wildcarded actions.
  /builds/<org>/devops/terraform/modules/tf-eks-cluster/main.tf:31
      28 |         data.aws_caller_identity.this.account_id
      29 |       )
      30 |     ]
      31 |     actions = ["kms:*"]    list: ["kms:*"]
      32 | 
      33 |     principals {
      34 |       type = "AWS"
  Legacy ID:  AWS099
  Impact:     Overly permissive policies may grant access to sensitive resources
  Resolution: Specify the exact permissions required, and to which resources they should apply instead of using wildcards.
  More Info:
  - https://tfsec.dev/docs/aws/iam/no-policy-wildcards#aws/iam 
  - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document 
  - https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html 
  1 potential problems detected.
```

My .tfsec config file is "empty": 
```
exclude: []
```

**Expected behavior**
The error is either shown every time when I run tfsec, or the error is not shown because it is OK or in the exclude list.

**Desktop (please complete the following information):**
 - OS: both on linux and mac osx

**Additional context**
I suspect this only appears when using multiple files and/or with use of external terraform modules, because when I try to reproduce this with a very small test file that exactly replicates the code it fails on, no errors appear, even after running it multiple times.

The codeblock it seems to fail on: 

```
data "aws_region" "this" {}

data "aws_caller_identity" "this" {}

data "aws_iam_policy_document" "this" {
  statement {
    sid    = "Allow Amazon EKS use of the key"
    effect = "Allow"
    resources = [
      format("arn:aws:kms:%s:%s:key/*",
        data.aws_region.this.name,
        data.aws_caller_identity.this.account_id
      )
    ]
    actions = [
      "kms:DescribeKey",
      "kms:CreateGrant",
    ]

    principals {
      type        = "Service"
      identifiers = ["eks.amazonaws.com"]
    }
  }
  statement {
    sid    = "Enable IAM User Permissions"
    effect = "Allow"
    resources = [
      format("arn:aws:kms:%s:%s:key/*",
        data.aws_region.this.name,
        data.aws_caller_identity.this.account_id
      )
    ]
    actions = ["kms:*"]

    principals {
      type = "AWS"
      identifiers = [
        format("arn:aws:iam::%s:root", data.aws_caller_identity.this.account_id)
      ]
    }
  }
}

resource "aws_kms_key" "this" {
  deletion_window_in_days = 30
  enable_key_rotation     = true
  policy                  = data.aws_iam_policy_document.this.json
}
```

**Comment by liamg** [comment]
Thanks for the report, please could you run with `--verbose` while we look into this?

**Comment by fliphess-nhb** [comment]
Yes! There you go :) 

[tfsec.debug.txt](https://github.com/aquasecurity/tfsec/files/6953230/tfsec.debug.txt)

**Comment by liamg** [comment]
Thanks @fliphess-nhb , do you also have verbose logs for a time when it fails tp detect the issue?

**Comment by fliphess-nhb** [comment]
Yes! 

I've added some excludes in the meantime, so at the moment my .tfsec.yml looks like: 
```
exclude:
- aws-vpc-no-public-egress-sgr 
- aws-eks-no-public-cluster-access
- aws-eks-encrypt-secrets              # This one is actually encrypted btw, but that's another one for another time
```

(Not sure if that's relevant)

But the check shown in the output in the previous `tfsec.debug.txt` is not excluded. 

[tfsec.debug.ok.txt](https://github.com/aquasecurity/tfsec/files/6955428/tfsec.debug.ok.txt)

**Comment by liamg** [comment]
@fliphess-nhb Awesome, thanks - we've found the issue, fix incoming...

**Comment by liamg** [comment]
You should have some luck with `v0.57.1` :crossed_fingers:

**Comment by fliphess-nhb** [comment]
@liamg Awesome! You are the best :) Thanks so much for the quick fix!  
I ran it about a 100 times in a row and doesn't appear anymore! :) 

I really love using the security tools you've created, keep up the good work! :) 👍
