### ISSUE TITLE
AWS066 is triggered when when setting encryption_config in a dynamic block (ie, when using terraform-aws-modules/eks/aws)

### ISSUE THREAD

**Issue by LesterTheTester** [aquasecurity/tfsec#1011]
**Describe the bug**
We use the AWS EKS helper module from https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest

It supports setting encryption_config via a variable `cluster_encryption_config`:

```
module "eks" {
  source           = "terraform-aws-modules/eks/aws"
  version          = "17.1.0"
  cluster_name     = var.cluster_name
  cluster_version  = "1.19"

  cluster_enabled_log_types = ["scheduler", "controllerManager", "authenticator", "audit", "api"]

  cluster_encryption_config = [
    {
      resources        = ["secrets"]
      provider_key_arn = aws_kms_key.eks-secrets.arn
    }
  ]
```

which internally passes this to the eks module by way of a dynamic block...

```
dynamic "encryption_config" {
    for_each = toset(var.cluster_encryption_config)

    content {
      provider {
        key_arn = encryption_config.value["provider_key_arn"]
      }
      resources = encryption_config.value["resources"]
    }
  }
```

It seems tfsec is unable to determine the value of "resources" in this case.  Maybe this is another reason for us to start using the first-class eks resource directly instead of the helper module, but it would be nice if tfsec supported this.

**To Reproduce**
1. Configure terraform-aws-module/eks/aws as above
2. Run tfsec

**Expected behavior**
AWS066 is not triggered

**Comment by liamg** [comment]
Hey @LesterTheTester - we’re actually about to release proper support for this today as a result of #1010 - I’ll post in this thread once it’s out there 👍

**Comment by liamg** [comment]
This should now work in `v0.58.0`.
