### ISSUE TITLE
AWS099 aws-iam-no-policy-wildcards should handle conditions

### ISSUE THREAD

**Issue by acdha** [aquasecurity/tfsec#1014]
Terraform code like this will trigger AWS099:

```hcl
  statement {
    resources = ["*"]
    actions = [
      "backup:TagResource",
    ]

    condition {
      test     = "StringLike"
      variable = "aws:RequestTag/Environment"
      values   = [var.global_tags["Environment"]]
    }

    condition {
      test     = "StringLike"
      variable = "aws:RequestTag/Project"
      values   = [var.global_tags["Project"]]
    }
  }
```

I'd tend to think for a tool like `tfsec` it would be sufficient to suppress that (or maybe lower the severity level?) in the presence of conditions.

**Comment by liamg** [comment]
This is a difficult one as it really depends on what the condition is. For example if you're giving full access on the condition the environment is production, it's still a potentially serious issue. It gets complicated further by which action(s) are being given.

Would it be helpful to instead have lists of "safe" or "less serious" actions where the severity would be reduced?

**Comment by acdha** [comment]
That's what I was thinking — maybe lower the level if there are conditions on the theory that you still want to look at it but it's avoiding the highest risk situations. Similarly to how a `Get<Noun>*` policy will trigger it but there's far less risk to that than `*` or a destructive operation.

In general, I'm a little concerned about how many ignore comments I'm seeing added to projects for `AWS099` when people are trying to avoid CI failures. I don't want that to become reflex.

**Comment by liamg** [comment]
Yeah, that makes sense, and I agree the addition of ignores as a reflex action is going to get worse.

I think part of the solution is going to be adding a lot more contextual analysis to the IAM checks and reducing severity where required, but that's not going to solve the ignore issue in general. 

Perhaps we should split this into multiple rules for `Get*`, `*` etc.

What's your view @owenrumney ?

**Comment by acdha** [comment]
One other thought: it feels like there's often a time-based aspect it'd be nice to be able to have rules around so you could make it easier to get a short-term ignore than a long-term one. The problem is doing that in the context of a tool like this which is otherwise stateless.

This isn't a fully-formed idea but I wonder whether there might be room for something like [expiring comments](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/expiring-todo-comments.md) where you could have some kind of project policy along the lines of “A new version of tfsec came out, it's okay to delay fixing things which weren't previously flagged for a month” without it meaning that you never remember to revisit that decision.

**Comment by liamg** [comment]
I think this would be a really good candidate for creating a [discussion](https://github.com/aquasecurity/tfsec/discussions). I'll close this issue for now until we have something concrete to get started on.

**Comment by acdha** [comment]
I added a comment to https://github.com/aquasecurity/tfsec/discussions/1639 which is similar
