### ISSUE TITLE
GCP VPC flow logs

### ISSUE THREAD

**Issue by gysel** [aquasecurity/tfsec#1024]
There is a new rule to ensure that VPC flow logs are activated on GCP.

```
  Result 1
  [google-compute-enable-vpc-flow-logs][LOW] Resource 'google_compute_subnetwork.redacted-subnetwork' uses default value for enable_flow_logs
  /builds/QNB_T93t/0/uc/redacted/terraform/gcp.tf:180-203
     179 | # Create subnets
     180 | resource "google_compute_subnetwork" "redacted-subnetwork" {
     198 |   // redacted
     199 |   log_config {
     200 |     aggregation_interval = "INTERVAL_5_SEC"
     201 |     flow_sampling        = 1
     202 |   }
     203 | }
     204 | 
  Impact:     Limited auditing capability and awareness
  Resolution: Enable VPC flow logs
  More Info:
  - https://tfsec.dev/docs/google/compute/enable-vpc-flow-logs#google/compute 
  - https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_subnetwork#enable_flow_logs 
```

The attribute `enable_flow_logs` does not exist in the latest Google Terraform provider version. The correct syntax to enable flow logging is listed on lines 199-202.

**Comment by owenrumney** [comment]
Thanks @gysel  - apologies for the delay in responding. I've raised https://github.com/aquasecurity/tfsec/issues/1076 to track the wider issue of taking provider into account when evaluating checks. In the meantime I suggest an ignore (maybe with an 3 month expiry) for this?
