### ISSUE TITLE
tfsec inconsistent results for a pair of buckets

### ISSUE THREAD

**Issue by dhallam** [aquasecurity/tfsec#1035]
**Describe the bug**
When trying to apply tfsec to terraform code containing a pair of buckets that use `terraform-aws-modules/s3-bucket/aws`, I am seeing intermittent failures. On my main codebase it occurs more frequently.  

The intermittent failure is a report stating

```
[aws-s3-enable-bucket-logging][MEDIUM] Resource 'module.s3_bucket_1:aws_s3_bucket.this[0]' does not have logging enabled.
```

See https://asciinema.org/a/9ygsuHdWwENmiVy4rXNJpGRfj for a demo that uses the code below.

**To Reproduce**
```
$ terraform --version
Terraform v1.0.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.54.0
```

```
$ tfsec --version
0.58.4
```

Create file `main.tf`:
```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}

provider "aws" {
  region = "eu-west-2"
}

resource "aws_kms_key" "objects" {
  description             = "KMS key is used to encrypt bucket objects"
  deletion_window_in_days = 7
  enable_key_rotation     = true
}

module "s3_bucket_logs" {
  source               = "terraform-aws-modules/s3-bucket/aws"
  version              = "~> 1.0"
  acl                  = "log-delivery-write"
  bucket               = "my-s3-bucket-logs"
  attach_public_policy = true
  force_destroy        = true

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true

  server_side_encryption_configuration = {
    rule = {
      apply_server_side_encryption_by_default = {
        # Can't use KMS on logs bucket
        sse_algorithm = "AES256"
      }
    }
  }

  versioning = {
    enabled = true
  }
}

module "s3_bucket_1" {
  source = "terraform-aws-modules/s3-bucket/aws"

  bucket = "my-s3-bucket-1"
  acl    = "private"

  attach_public_policy    = true
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true

  logging = {
    target_bucket = module.s3_bucket_logs.this_s3_bucket_id
    target_prefix = "log/"
  }

  server_side_encryption_configuration = {
    rule = {
      apply_server_side_encryption_by_default = {
        kms_master_key_id = aws_kms_key.objects.arn
        sse_algorithm     = "aws:kms"
      }
    }
  }

  versioning = {
    enabled = true
  }
}

```

To iterate through multiple runs, checking for the results, run:
```
$ for i in `seq 1 10`; do terraform init 2>&1 > /dev/null && tfsec --no-color . | egrep "potential problems|^  \[|No problems detected"; done
```

**Expected behavior**
Checks should pass and pass consistently.

**Screenshots**
See https://asciinema.org/a/9ygsuHdWwENmiVy4rXNJpGRfj

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04

**Additional context**
None

**Comment by owenrumney** [comment]
@dhallam I'm pretty sure this isn't the issue, but can you confirm if this is a typo 
```
target_bucket = module.s3_bucket_logs.this_s3_bucket_id
```

I think it should be a `this.s3_bucket_id`?
```
target_bucket = module.s3_bucket_logs.this.s3_bucket_id
```

**Comment by dhallam** [comment]
Hi @owenrumney. That's interesting - good spot. We're still using the v1 of the module (1.25.0) where the output prefix was `this_` (was removed in https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/pull/88). However, I notice that I hadn't specified the version of `s3_bucket_1` so it was pulling the latest (2.7.0). The `s3_bucket_logs` is pinned to v1 so the terraform in the sample is valid, albeit running a different version of the terraform-aws-s3-module for each bucket. 

Re-running with both `s3_bucket_1` and `s3_bucket_logs` pinned to `~> 1.0`, I consistently get

```
[aws-s3-enable-bucket-logging][MEDIUM] Resource 'module.s3_bucket_1:aws_s3_bucket.this[0]' does not have logging enabled.
```

If I pin both to `~> 2.0` and update to `target_bucket = module.s3_bucket_logs.s3_bucket_id`, I consistently get

```
[aws-s3-enable-bucket-logging][MEDIUM] Resource 'module.s3_bucket_1:aws_s3_bucket.this[0]' does not have logging enabled.
```

If I pin `s3_bucket_1` to `~> 2.0` so that it's explicit and leave `s3_bucket_logs` pinned to `~> 1.0`, I see the inconsistent results as reported in this issue.

So I think there are two issues:

1. Why are we getting `aws-s3-enable-bucket-logging` on a bucket that has logging enabled when using the `terraform-aws-s3-bucket` module?
2. What is the cause of the inconsistency when the two modules use different versions of `terraform-aws-s3-bucket`?

**Comment by owenrumney** [comment]
Thanks for this - I'll take a look at 1. I think the reason for 2 is a dedup issue, will try to work that out too

**Comment by liamg** [comment]
@dhallam Please could you test this with the latest release and let us know here if it's still an issue? I believe this should be fixed now with the reworking of our results handling for modules.
