### ISSUE TITLE
Public ECR image instead of DockerHub

### ISSUE THREAD

**Issue by w0rmr1d3r** [aquasecurity/tfsec#1044]
**Is your feature request related to a problem? Please describe.**
Is there a public AWS ECR image to pull from instead of DockerHub?

**Describe the solution you'd like**
A public image to pull from ECR instead of pulling it from DockerHub

**Describe alternatives you've considered**
I've search for it in public ECR repos, but can't find it 😕 

**Additional context**
Have looked for issues regarding this but found nothing.

**Comment by owenrumney** [comment]
Yup - just need to find out which AWS account to hook this up to

**Comment by w0rmr1d3r** [comment]
Hello @owenrumney !
A GitHub package to use it with Docker works as well!

Thanks!

**Comment by owenrumney** [comment]
Hey @w0rmr1d3r - I think I've done that right :man_shrugging:  - the latest version should be available in packages now https://github.com/orgs/aquasecurity/packages?repo_name=tfsec

**Comment by w0rmr1d3r** [comment]
Thank you @owenrumney !
Tested the new image and it works perfectly!

Closing the issue now 😄
