### ISSUE TITLE
Azure app service check requires attribute auth_settings.enabled = true

### ISSUE THREAD

**Issue by wlodekj** [aquasecurity/tfsec#1066]
**Describe the bug**

Hey,

I have been using tfsec a lot recently and found it really helpful, however some new updates to azure appservice checks look a little bit weird to me. There are a lot of azure app services that are public facing and do not require authentication and I don't understand why it's a security "threat".

```
Azure app service check requires attribute auth_settings.enabled = true
```

**To Reproduce**

1. Setup dummy app service

```
resource "azurerm_app_service" "test" {
  name                = "test"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  app_service_plan_id = azurerm_app_service_plan.test.id

  https_only = true
  client_cert_enabled = true

  site_config {
    always_on  = true
    scm_type   = "LocalGit"
    ftps_state = "Disabled"
    linux_fx_version = "NODE|12-lts"
    http2_enabled = true
  }

  auth_settings {
    enabled = false
  }

  identity {
    type = "UserAssigned"
    identity_ids = [data.azurerm_user_assigned_identity.test.id]
  }
}
```

3. Run tfsec

**Expected behavior**

You should probably consider adding something called "suggestions" and display that message there to "remember about adding auth when you require a login to your app". 

**Screenshots**

<img width="597" alt="Screenshot 2021-09-02 at 15 30 32" src="https://user-images.githubusercontent.com/45555255/131852475-16615422-2b72-486c-8e05-fcff2c311510.png">

**Desktop**

 - OS: macOS Catalina

**Comment by owenrumney** [comment]
Hey @wlodekj - thanks for the issue, ignores exist for this situation. We can't infer the intent of the appservice, so we prefer to exercise caution and report all unauthenticated endpoints. If this is incorrect in a specific case, that is where you would add an ignore.

**Comment by wlodekj** [comment]
Hey @owenrumney, thanks for the quick reply! - that makes sense however after recent updates I already had to add 3 ignores to each app service config (mainly because we are using application gateway instead of standalone app service) and that's why I was a little bit concerned.

Thanks,
Jakub

**Comment by owenrumney** [comment]
I think there is probably an argument for some sort of "grace period" before checks start erroring, particularly as we add more checks.

V1 is coming soon, at that point we will have added a the majority of checks and it will ease off on volume additions
