### ISSUE TITLE
Cloud account takeover if a resource using a service account is compromised

### ISSUE THREAD

**Issue by steveoh** [aquasecurity/tfsec#1067]
**Describe the bug**

I have a GCS bucket and a `google_storage_bucket_iam_member` with a role that allows a service account to manage files within the bucket.

```tf
resource "google_storage_bucket_iam_member" "default" {
  bucket = google_storage_bucket.default.name
  role   = "roles/storage.objectAdmin"
  member = "serviceAccount:${google_service_account.default.email}"
}
```

This produces the following potential problem

> Impact:     Cloud account takeover if a resource using a service account is compromised
> Resolution: Limit service account access to minimal required set

This seems to me to be a false positive. There are a few other roles that trigger this warning as well. Is the problem triggered because the role has `admin` in the name?

If this is not a false positive or a bug, what is the recommendation for the level of granularity to assign roles?

I have considered using the 9 assigned permissions for `objectAdmin` but that seems excessive and a round about way to skirt the problem.

```
resourcemanager.projects.get
resourcemanager.projects.list
storage.objects.create
storage.objects.delete
storage.objects.get
storage.objects.getIamPolicy
storage.objects.list
storage.objects.setIamPolicy
storage.objects.update
```

**Comment by liamg** [comment]
The recommendation is generally to avoid any kind of "admin" level permissions where possible, and assign more granular permissions i.e. a subset of the above permissions as required. This is sometimes going to raise issues where all of those permissions (or use of the `storageAdmin` role and similar) is required, but we prefer to err on the side of caution in this case.
