### ISSUE TITLE
Allowlist existing tfsec lint violations to enable adoption in legacy projects

### ISSUE THREAD

**Issue by ghost** [aquasecurity/tfsec#1073]
**Is your feature request related to a problem? Please describe.**

Adopting tfsec in an existing terraform codebase is difficult because I cannot automatically generate ignore statements for all existing tfsec lint violations.

**Describe the solution you'd like**

Generate an allowlist of existing lint violations, similar to RuboCop's `.rubocop_todo.yml`.

https://docs.rubocop.org/rubocop/configuration.html#automatically-generated-configuration

**Describe alternatives you've considered**

- Not adopting tfsec.
- Blanket ignoring existing error codes, which does not prevent them from being introduced in net new terraform code.

**Comment by owenrumney** [comment]
Hey @lopopolo-figma - I think your only current option is to add the ignore list for the project the tackle them over time

You could do something like
```shell
tfsec --format=csv [PATH_TO_TERRAFORM_CODEBASE] 2>/dev/null | grep '^/' | awk -F, '{"  - "print $4}' | sort -u
```
to get the list of all the issues then you can add a config file to `[PATH_TO_TERRAFORM_CODEBASE]/.tfsec/config.yaml`

```yaml
exclude:
  - aws-api-gateway-use-secure-tls-policy
  - aws-ec2-enforce-http-token-imds
  - aws-elbv2-http-not-used
  - aws-rds-no-classic-resources
  - aws-vpc-add-description-to-security-group
  - aws-vpc-no-public-ingress-sgr
  - general-secrets-sensitive-in-attribute-value
```

You can find more information on local project config - https://tfsec.dev/docs/config/

**Comment by lopopolo-figma** [comment]
Hi @owenrumney. I would rather allowlist specif if violations instead of blanket ignoring nearly every lint.

I'd love to permit the existing violations as is but lint all new terraform code with all lints to ensure new code is conformant.

Blanket ignoring entire lints does not meet that purpose and means the code will continue to accrue violations until a Big Bang commit fixes all of them, which may not be feasible to do atomically.

**Comment by owenrumney** [comment]
I don't think it's practicable to have allowed lists - that would require a reference to the issue/file/line to a config file and any reshuffle of the code would render that obsolete.

The vscode plugin allows you to add ignores for checks that it finds on a per-issue basis, I'll take a look at how easily it could be updated to add ignores en-mass from the plugin

**Comment by lopopolo-figma** [comment]
Another option to consider is to have a count of lint violations per file that acts as a ratchet. If the count goes up, `tfsec` fails. If the count goes down, a warning is issued to move the ratchet down.

**Comment by liamg** [comment]
It is now possible to generate ignore rules for violations using the [vscode extension](https://marketplace.visualstudio.com/items?itemName=tfsec.tfsec) which may help with your use case.
