### ISSUE TITLE
Add support for Provider version involvement check resolution

### ISSUE THREAD

**Issue by owenrumney** [aquasecurity/tfsec#1076]
**Is your feature request related to a problem? Please describe.**

When evaluating checks, the version of the provider should be taken into account. This is brought to light by recent changes to GCP provider to v3 which has breaking changes

**Describe the solution you'd like**

When there is a material change between provider versions, the used version should be taken into account

**Additional context**
See https://github.com/aquasecurity/tfsec/issues/1024 for an example

**Comment by liamg** [comment]
The adapters can take care of this once we hit v1.

**Comment by liamg** [comment]
I think this is now an adapter responsibility - they will have to handle different provider implementations e.g. trying multiple attributes when an attribute has been renamed etc. I guess they could read `provider` blocks and act specifically on the version there too.
