### ISSUE TITLE
ftps_state should be under the site_config block

### ISSUE THREAD

**Issue by shaneschnell** [aquasecurity/tfsec#1084]
If I put ftps_state in the azurerm_app_service resource block the security check succeeds and the terraform plan fails.
If I put ftps_state in the site_config block the security check sets a warning and the terraform plan succeeds.

The issue seems to be with the security check.  I believe the check should verify that ftps_state is under the site_config block.

https://github.com/aquasecurity/tfsec/blob/a61476838681e17a02513b895621374a96faaaeb/internal/app/tfsec/rules/azure/appservice/ftp_deployments_disabled_rule.go#L36

**Comment by mattmichal** [comment]
I'm facing this issue as well. PR #1080 should address this; hopefully it is merged soon.

**Comment by leesutcliffe** [comment]
This issue was fixed and merged in [PR1091](https://github.com/aquasecurity/tfsec/pull/1091)
Hopefully should be included in an upcoming release

**Comment by owenrumney** [comment]
This is released as v0.58.12 - thanks for the report and thanks to @leesutcliffe and @jan-mrm  for the fixes
