### ISSUE TITLE
Check for descriptions in ingress and egress blocks within aws_security_group resources

### ISSUE THREAD

**Issue by drewhammond** [aquasecurity/tfsec#1087]
**Is your feature request related to a problem? Please describe.**
We would like to ensure `ingress` and (optionally) `egress` blocks within `aws_security_group` resources have a `description` field. Right now, AWS018 seems to only inspect `aws_security_group_rule` resources, or descriptions at the top level of `aws_security_group`.

**Describe alternatives you've considered**
We're using a custom check to accomplish this, but it would be nice to have the functionality in a core rule.

**Additional context**

In this example, we'd like to detect the missing description from the second `ingress` block:

```
resource "aws_security_group" "example" {
  name        = "example"
  description = "Some SG" # we don't care about this
  vpc_id      = aws_vpc.main.id

  ingress {
    description     = "access from xyz" # this description is the important one
    from_port       = 8080
    to_port         = 8080
    protocol        = "tcp"
    security_groups = [aws_security_group.foo.id]
  }

  ingress {
    from_port       = 443
    to_port         = 443
    protocol        = "tcp"
    security_groups = [aws_security_group.foo.id]
  }
}
```

**Comment by owenrumney** [comment]
Yup, I'll put this in over the weekend

**Comment by owenrumney** [comment]
This has been added @drewhammond in #1089 thanks. And also Thanks, appreciated :+1:
