### ISSUE TITLE
Make tfsec actually ignore downloaded modules.

### ISSUE THREAD

**Issue by YuriGal** [aquasecurity/tfsec#1088]
When repo's `.terraform` folders contains large number of modules and submodules, and tfsec runs with option `--force-all-dirs` - scan can take a really long time and cause other issues. We still need this option though, because there're legitimate user subfolders with terraform files that need to be scanned.

**Describe the solution you'd like**
Currently option `--exclude-downloaded-modules` excludes result of `.terraform` folder scan from final output, but actual scan still happens. Ideally this option (or maybe some new one) should exclude `.terraform` folder from scanning altogether.

**Describe alternatives you've considered**
We can run tfsec programmatically, doing recursive walk thru folders on our own and within each folder just scan its root.

**Comment by owenrumney** [comment]
Hi @YuriGal  - I've added this as #1100  - I'll discuss it with @liamg  on Monday and if we're happy it doesn't risk breaking other peoples flow it will be in the next release.

**Comment by owenrumney** [comment]
Hey @YuriGal  - this will be in the next release

**Comment by YuriGal** [comment]
Awesome, thanks, @owenrumney!
