### ISSUE TITLE
TFSec --out Argument Causes `Exit 1` Failure

### ISSUE THREAD

**Issue by AErmie** [aquasecurity/tfsec#1096]
**Describe the bug**
When running TFSec via the [Docker container](https://github.com/aquasecurity/tfsec#use-with-docker) method, when attempting to use the `--out` command, the following error is thrown: `open src/TFSecReport: is a directory`

NOTE: In my example, the TFSecReport already exists. Also, the [usage](https://github.com/aquasecurity/tfsec#use-with-docker) documentation is not clear, as the argument states that `--out` is used as "[path to output to]" whereas the description says "Set output file". 

So which is it? A path, or an explicit file? 

Further, even when attempting to specify an explicit file, the following error is thrown: `open src/TFSecReport/TFSec-Report.xml: permission denied`

**To Reproduce**
``` YAML
- bash: | 
  docker run --rm --volume $(System.DefaultWorkingDirectory):/src \
    aquasec/tfsec:latest ./src \
    --format JUnit \
    --out ./src/TFSecReport/
displayName: TFSec Static Code Analysis
```

**Expected behavior**
The expectation is to have the appropriately formatted output file will be written to the target `--out` directory/path

**Additional context**
The only approach that works to obtain output is the following: 
```yaml
docker run --rm --volume $(System.DefaultWorkingDirectory):/src \
  aquasec/tfsec:latest ./src --format JSON > $(System.DefaultWorkingDirectory)/TFSecReport/TFSec-Report.json
```

**Comment by owenrumney** [comment]
`--out` is as per the usage `Set output file` - so an explicit file. I've updated the usage to clarify this in the documentation

If you're getting a 1 and have errors then this is expected behaviour. tfsec will return non-zero when checks fail regardless of whether output is going to stdout or into a file
