### ISSUE TITLE
Ignored Count Inaccurate When Using `--include-ignored` Command

### ISSUE THREAD

**Issue by AErmie** [aquasecurity/tfsec#1097]
**Describe the bug**
Although using a [config file](https://tfsec.dev/docs/config/) for check exclusions, those checks still appear in the output as errors and are not included in the "ignored" count when using the `--include-ignored` command.

**To Reproduce**
Config File:
```yaml
exclude:
  - aws-cloudwatch-log-group-customer-key
```
TFSec execution via Docker container:
```yaml
docker run --rm --volume $(System.DefaultWorkingDirectory):/src \
  --config-file src/tfsec.yml --include-ignored
```

TFSec scan shows zero (0) as ignored, and the specific check still appears with its severity.

```yaml
results
  ------------------------------------------
  critical             242
  high                 34
  medium               12
  low                  6
  ignored              0

[aws-cloudwatch-log-group-customer-key][LOW] Resource 'aws_cloudwatch_log_group.ecs_log' is only using default encryption
  /src/terraform/ecs.tf:44-48
```

**Expected behavior**
The ignored check should be counted in the `ignored` value even when using the `--include-ignored` command. 

**Additional context**

**Comment by owenrumney** [comment]
Hey @AErmie  - if you `--include-ignored` they are included in the other result numbers. All that this flag does is bypass the logic that checks for comments in the resources and if you've asked for them to be included they will be treated like any other failure. I think this may be where you talk about "Other" in one #1098 - are you saying that you think ignored should be flagged as ignored in the results?

**Comment by AErmie** [comment]
Hey @owenrumney, my interpretation/expectation was that if I used the `--include-ignored` command, that the resulting stats/report would include them in the count (ie. you're ignoring 3 checks), not include them in the scan as if they weren't ignored at all. 

If I misunderstood how that command is supposed to be used, that's fine, but might I suggest adding some clarity to the documentation for it?

**Comment by owenrumney** [comment]
Thanks @AErmie  - updated the docs to reflect what include-ignored actually does more clearly
