### ISSUE TITLE
Include Ignored Checks in Azure DevOps Pipeline Test Results When Using the `--include-ignored` Command

### ISSUE THREAD

**Issue by AErmie** [aquasecurity/tfsec#1098]
**Is your feature request related to a problem? Please describe.**
When running TFSec in an Azure DevOps pipeline, and using the `--include-passed` command (along with the appropriate output format), the passed tests are also visible in the pipeline test results. However, when using the `--include-ignored` command, those tests are not included in the pipeline test results.

**Describe the solution you'd like**
It would be nice to have the 'ignored' checks appear in the "Others" category for Azure pipeline test results. That way, we can easily review if an ignored check should be re-included. 

**Describe alternatives you've considered**
No alternatives were explored. 

**Additional context**

**Comment by owenrumney** [comment]
Hey @AErmie - can you clarify what you mean by the pipeline test results? Is that something specific to Azure Pipelines, I'm guessing so as you mention "Others" category

If I run with `--format json --include-ignored` then the ignore results are included in the json.

**Comment by AErmie** [comment]
Hey @owenrumney, yes I'm referring to the Azure Pipeline test results. 

What I meant was... when you include the `--include-passed` command, the JUnit XML file that's produced (and published to Azure Pipelines via the [Publish Test Results](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=trx%2Cyaml) task), will rightfully show the passed and failed tests.

![TFSec-AzurePipeline-TestResults](https://user-images.githubusercontent.com/10376796/135729603-083227cc-e8ac-4920-9f2a-16e0eb255882.png)

What I would also like to include in the output (using the `--include-ignored` command), is all ignored/suppressed checks, but categorize them as "other" (in reference to Azure Pipeline test results). 

That way it allows us to also track if the number of suppressed checks changes as well.

**Comment by owenrumney** [comment]
If I understand the docs correctly, you can only do `failure`, `skipped`, `error` or anything else and anything else equates to `passed`. So I'm not clear that this would be achievable without artificially setting the outcome to skipped. 
```
Outcome | Failed: if exists /Testsuites/testsuite/testcase/failure Or /Testsuites/testsuite/testcase/error 
                 Not Executed: if exists Testsuites/testsuite/testcase/skipped 
                 Passed: for all other cases

```

Or does it use a different element of the XML to do this?

**Comment by AErmie** [comment]
Hey @owenrumney, I tried to do some digging around, and the only thing I could find is this article [About pipeline tests](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/test-glossary?view=azure-devops). I'm not sure if it's linked to one of the 15 outcome types (maybe None, Not applicable, Not executed, or Not impacted).

**Comment by liamg** [comment]
This is an interesting requirement - it would be good to see how many others require this feature before proceeding.

**Comment by liamg** [comment]
It would be good to talk about this in [discussions](https://github.com/aquasecurity/tfsec/discussions) if still required, then we can reopen an issue once we have a concrete idea of what this would look like.
