### ISSUE TITLE
running tfsec with a tfvars file containing secrets erroneously triggers secrets warnings for variables

### ISSUE THREAD

**Issue by lopopolo** [aquasecurity/tfsec#1102]
```console
$ tfsec --tfvars-file secrets.auto.tfvars

  Result 1

  [general-secrets-sensitive-in-attribute][CRITICAL] Block 'provider.github' includes a potentially sensitive attribute which is defined within the project.
  /Users/lopopolo/dev/hyperbola/project-infrastructure/github/main.tf:19


      16 | }
      17 |
      18 | provider "github" {
      19 |   token = var.github_token    string: "xxxx"
      20 |   owner = "hyperbola"
      21 | }
      22 |

  Legacy ID:  GEN003
  Impact:     Block attribute could be leaking secrets
  Resolution: Don't include sensitive data in blocks

  More Info:
  - https://tfsec.dev/docs/general/secrets/sensitive-in-attribute#general/secrets
  - https://www.terraform.io/docs/state/sensitive-data.html

  Result 2

  [general-secrets-sensitive-in-attribute-value][CRITICAL] Block 'provider.github' includes potentially sensitive data. Check for new Github Token
  /Users/lopopolo/dev/hyperbola/project-infrastructure/github/main.tf:19


      16 | }
      17 |
      18 | provider "github" {
      19 |   token = var.github_token    string: "xxx"
      20 |   owner = "hyperbola"
      21 | }
      22 |

  Legacy ID:  GEN005
  Impact:     Sensitive credentials may be compromised
  Resolution: Check the code for vulnerabilities and move to variables

  More Info:
  - https://tfsec.dev/docs/general/secrets/sensitive-in-attribute-value#general/secrets
  - https://www.terraform.io/docs/state/sensitive-data.html

  times
  ------------------------------------------
  disk i/o             1.785178ms
  parsing HCL          35.444µs
  evaluating values    1.22209ms
  running checks       2.709682ms

  counts
  ------------------------------------------
  files loaded         9
  blocks               13
  modules              2

  results
  ------------------------------------------
  critical             2
  high                 0
  medium               0
  low                  0
  ignored              4

  2 potential problems detected.
```

Running without the flags to give the tfvars file gives this warning:

```
Warning: A tfvars file was found but not automatically used. Did you mean to specify the --tfvars-file flag?
```

The secret does not appear in the configuration, I do not think this code should warn with CRITICAL violations.

**Comment by owenrumney** [comment]
I'm not sure I follow, if you pass a tfvars file that has attributes that are sensitive, it will report it as a rule breach

**Comment by lopopolo** [comment]
Gotcha, including a tfvars file treats it as part of the validated config. The tfvars file in question is git ignored and not checked in.

Is this not what tfsec expects?

What is the correct way to address the warning?

**Comment by owenrumney** [comment]
I'm not sure there really is a correct way to address it. If you're piping stdout to a file then it won't appear in there because it's written to stderr. What is the concern so I can try and address that specifically

**Comment by lopopolo** [comment]
Is the warning tfsec is giving me actionable?

I tried to address the warning by doing what it suggests and that caused config validation errors.

What is the purpose of the warning if I should not do what it suggests?

**Comment by owenrumney** [comment]
Is the warning tfsec is giving me when not including the tfvars flag actionable? - No, its informative, will have a think if it needs changing to an info.

I tried to address the warning by doing what it suggests and adding the flag for the tfvars file. Doing what the warning is warning me to do caused config validation errors. 

What is the purpose of the warning if I should not do what it suggests? - the idea of it came from someone complaining that their tfvars file wasn't being used so we put in a warning that there was one there but it hadn't been used. It was to mitigate people assuming it should pick it up automagically

**Comment by liamg** [comment]
Ideally you should be passing sensitive values to terraform via a secrets manager, that is the real issue that tfsec is reporting.
