### ISSUE TITLE
[False Positive ?] `general-secrets-sensitive-in-attribute` false positive in `google_service_account_key` resource

### ISSUE THREAD

**Issue by julien-sugg** [aquasecurity/tfsec#1107]
Greetings,

I started playing with tfsec today and I have the feeling that I am hitting a false positive for one particular case.

**Describe the bug**
I am hitting a false positive using the `google_service_account_key` resource available in the `google` provider on the `private_key_type` argument.

**To Reproduce**
1. Use the following minimalist TF code snippet that will be scanned:

```hcl
resource "google_service_account_key" "ingress-uptime-monitoring-key" {
  public_key_type = "TYPE_X509_PEM_FILE"
  # False positive here, it is not a credential
  private_key_type = "TYPE_GOOGLE_CREDENTIALS_FILE"
  key_algorithm = "KEY_ALG_RSA_2048"
}
```

2. Run the scan

```bash
tfsec .
```

3. Confirm that an error occurs (`general-secrets-sensitive-in-attribute`) for the `private_key_type` argument

```bash
$ tfsec .

  Result 1

  [general-secrets-sensitive-in-attribute][CRITICAL] Block 'google_service_account_key.ingress-uptime-monitoring-key' includes a potentially sensitive attribute which is defined within the project.
  /tmp/repro.tf:4


       1 | resource "google_service_account_key" "ingress-uptime-monitoring-key" {
       2 |   public_key_type = "TYPE_X509_PEM_FILE"
       3 |   # False positive here, it is not a credential
       4 |   private_key_type = "TYPE_GOOGLE_CREDENTIALS_FILE"    string: "TYPE_GOOGLE_CREDENTIALS_FILE"
       5 |   key_algorithm = "KEY_ALG_RSA_2048"
       6 | }
       7 |

  Legacy ID:  GEN003
  Impact:     Block attribute could be leaking secrets
  Resolution: Don't include sensitive data in blocks

  More Info:
  - https://tfsec.dev/docs/general/secrets/sensitive-in-attribute#general/secrets 
  - https://www.terraform.io/docs/state/sensitive-data.html 

  times
  ------------------------------------------
  disk i/o             277.7351ms
  parsing HCL          4.2µs
  evaluating values    52.4µs
  running checks       1.7974ms

  counts
  ------------------------------------------
  files loaded         1
  blocks               1
  modules              0

  results
  ------------------------------------------
  critical             1
  high                 0
  medium               0
  low                  0
  ignored              0

  1 potential problems detected.
```

**Expected behavior**
No error should occur.

**Screenshots**
Not Applicable, see copy-pasted output above.

**Desktop (please complete the following information):**
 - OS: WSL2 (debian)

**Additional context**
- tfsec version: 0.58.12

**Comment by owenrumney** [comment]
yup - its seeing a value specified in there and treating it as a risk. best course of action would be to add `#tfsec:ignore:general-secret-sensitive-in-attribute` either at the end of the line or in the line directly above `private_key_type`

**Comment by julien-sugg** [comment]
Thanks for the confirmation, I was indeed using this instruction in my code base to safely ignore this now confirmed false positive.

Unfortunately, I don't know much about the project's code-base yet, nor how the checks/rules operate, but is it an expected behavior ? Is there anything we can attempt to improve from the rule engine perspective ? Indeed, I am a bit troubled with this particular use-case since the value of the `private_key_type` argument is some kind of enum (See https://cloud.google.com/iam/docs/reference/rest/v1/projects.serviceAccounts.keys#serviceaccountprivatekeytype), whom none are considered as sensitive.

Are the `general-secret-sensitive-in-attribute` checks solely performed on naming conventions due to the inherent complexity of such rules ?

**Comment by owenrumney** [comment]
@julien-sugg  - I've added a whitelist for this attribute. We have a list of attribute names we alert on. the one coming into play here was `private_key`
