### ISSUE TITLE
Skipping download modules takes a very long time

### ISSUE THREAD

**Issue by Makeshift** [aquasecurity/tfsec#1112]
**Describe the bug**
I have a reasonably large infrastructure managed by Terraform and Terragrunt. Each terragrunt folder has a `.terragrunt-cache` and each terraform module has a local `.terraform` folder.

tfsec will fully traverse the entire tree even inside the dotfolders, which appears to slow it down considerably:

For example:
```
skipping download module file /home/connor/projects/iea/resat/aws/infrastructure/iea/prod/data/c3s_team_data/.terragrunt-cache/AwfKwmYiBGyKypK-K4c9GFWLo1c/VRIcfLosMDxxEDmoQatIlS1c6XM/tf_modules/c3s_data/.terraform/modules/this
skipping download module file /home/connor/projects/iea/resat/aws/infrastructure/iea/prod/data/data_team_infra/.terragrunt-cache/eYhZrGII82tvdoiYycZhBOGiuDE/VRIcfLosMDxxEDmoQatIlS1c6XM/tf_modules/resat_data_team/.terraform/modules/this
skipping download module file /home/connor/projects/iea/resat/aws/infrastructure/iea/prod/data/data_team_infra/.terragrunt-cache/eYhZrGII82tvdoiYycZhBOGiuDE/VRIcfLosMDxxEDmoQatIlS1c6XM/tf_modules/resat_data_team/.terraform/modules/userdata.this
```
tfsec shouldn't be checking anything in the .terragrunt-cache or .terraform folders, and it shouldn't bother traversing them either. With `--exclude-dir` being removed a little while back, I can't use tfsec on my whole project, as it tries to scan every single tf file in my terragrunt-cache - all 11634 of them.

I only have 193 files that tfsec should check, I believe:
```
# /bin/find "$PWD" -not -path '*/\.*' -name '*.tf' | wc -l
193
```

With my setup, tfsec takes 

**To Reproduce**
1. Have a terragrunt project with a local .terragrunt-cache folder
2. Try to run tfsec

**Expected behavior**
tfsec to only discover and scan tf files in non-hidden folders.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by owenrumney** [comment]
Oh maybe I've misunderstood. Are you saying even using skip downloaded it's not working? Which version of tfsec are you on?

**Comment by owenrumney** [comment]
Closing due to no further information .Feel free to reopen if required
