### ISSUE TITLE
[CHECK] AWS Tag requirement & character breach check

### ISSUE THREAD

**Issue by japan-p** [aquasecurity/tfsec#1117]
**Target Provider**
This check will target AWS provider

**Target Terraform Block type**
- [X] module
- [X] resource
- [ ] data 
- [ ] provider
- [X] variable

**Target Terraform Type(s)**
Tags on all AWS resources

** Background**
- Currently the only way to know if a terraform resource has any issue in tags with character limit or forbidden characters or using reserved tags key prefix is when after the terraform apply failed due to AWS returning an error to user for using invalid tag key or value.
- In tfsec there is a way to check this using custom checks with regex pattern however this is limited to checking only for either tag key or tag value where when checking for tag value, the custom check needs know about the tag key the value needs to be checked instead of checking on any tag keys.

**Description of check**
This new check is to create a built-in check to identify any breach of AWS tagging rules and requirement on character/naming limits and to see if there are any forbidden characters present in the tag key or values for any AWS resource, this will help identify any tagging issues early instead of late in the terraform apply errors.

**Relevant links**
Tag naming limits and requirements section in https://docs.aws.amazon.com/general/latest/gr/aws_tagging.html

**Anything Else**
NA

**Comment by owenrumney** [comment]
This isn't a security check in my mind, its a linter check. The custom checks were created with a view to people adding their compliance checks (with a security slant)
