### ISSUE TITLE
Ignore checks with variable context

### ISSUE THREAD

**Issue by borissavelev** [aquasecurity/tfsec#1119]
**Is your feature request related to a problem? Please describe.**
Hey! I have complex TF code with dynamic resources based on variables. Trying to use tfsec and it works great! Thank you!

But I want to skip some checks for part of variable and haven't seen possibility to do this.

example:
```
locals {
  rules = {
    http = 80
    https = 443
  }
}

resource "aws_security_group_rule" "this" {
      for_each = local.rules
      type = "ingress"
      description     = "test"
      from_port       = each.value
      to_port         = each.value
      protocol        = "tcp"
      cidr_blocks     = ["0.0.0.0/0"]

}
```

the aim is ignore `aws-vpc-no-public-ingress-sgr` for port 443, but still have an error for port 80

**Describe the solution you'd like**
Ignore checks for parts of variables

```
locals {
  rules = {
    http = 80
    #tfsec:ignore:aws-vpc-no-public-ingress-sgr
    https = 443
  }
}
```

**Describe alternatives you've considered**

**Additional context**
Some kind related to https://github.com/aquasecurity/tfsec/issues/493

**Comment by owenrumney** [comment]
Hey @borissavelev  - this isn't possible in the way you have described it, however we have come to a solution which should make it doable.

```hcl
locals {
  rules = {
    http = 80
    https = 443 
  }
}

#tfsec:ignore:aws-vpc-no-public-ingress-sgr[from_port=443]
resource "aws_security_group_rule" "this" {
      for_each = local.rules
      type = "ingress"
      description     = "test"
      from_port       = each.value 
      to_port         = each.value
      protocol        = "tcp"
      cidr_blocks     = ["0.0.0.0/0"]

}
```

**Comment by owenrumney** [comment]
@borissavelev  - this is in v0.60.0

**Comment by crhuber** [comment]
@owenrumney are there any docs for this?

**Comment by owenrumney** [comment]
Reopening while I write some docs - @crhuber  - give me today to get this done!

**Comment by owenrumney** [comment]
@crhuber  - https://aquasecurity.github.io/tfsec/v0.61.3/getting-started/configuration/ignores/
