### ISSUE TITLE
Dynamic blocks aren't rendered in error messages

### ISSUE THREAD

**Issue by nantiferov** [aquasecurity/tfsec#1121]
**Describe the bug**
Resources generated with dynamic blocks are checked correctly, but not rendered in error messages

**To Reproduce**
1. create `main.tf` file with dynamic blocks, example with `aws_security_group`:
```terraform
locals {
  groups = {
    "test1" = {
      "description" = "test1 group",
      "ingress" = [
        {
          "from_port" = 22,
          "to_port"   = 22,
          "protocol"  = "tcp",
          "cidr_blocks" = [
            "0.0.0.0/0"
          ]
        },
        {
          "description" = "test1 http any",
          "from_port"   = 80,
          "to_port"     = 80,
          "protocol"    = "tcp",
          "cidr_blocks" = [
            "0.0.0.0/0"
          ]
        },
      ],
      "egress" = [
        {
          "from_port" = 0,
          "to_port"   = 0,
          "protocol"  = "-1",
          "cidr_blocks" = [
            "0.0.0.0/0"
          ]
        }
      ]
    }
  }
}

resource "aws_security_group" "this" {
  for_each = local.groups

  name        = each.key
  description = lookup(each.value, "description", each.key)
  vpc_id      = "vpc-xxxx"

  dynamic "ingress" {
    for_each = each.value.ingress

    content {
      description = lookup(ingress.value, "description", "")
      from_port   = ingress.value.from_port
      to_port     = ingress.value.to_port
      protocol    = ingress.value.protocol
      cidr_blocks = lookup(ingress.value, "cidr_blocks", null)
    }
  }

  dynamic "egress" {
    for_each = each.value.egress

    content {
      description     = lookup(egress.value, "description", null)
      from_port       = egress.value.from_port
      to_port         = egress.value.to_port
      protocol        = egress.value.protocol
      cidr_blocks     = lookup(egress.value, "cidr_blocks", null)
      security_groups = lookup(egress.value, "security_groups", null)
      self            = lookup(egress.value, "self", null)
    }
  }
}
```

2. Run `tfsec --exclude aws-vpc-no-public-ingress-sg,aws-vpc-no-public-egress-sg`
3. There will be one `aws-vpc-add-description-to-security-group` error found:
```log
[aws-vpc-add-description-to-security-group][LOW] Resource 'aws_security_group.this["test1"]' has ingress without description.
  /Users/nantiferov/projects/bolteu/terraform-main/infratest/eu-central-1/test1/main.tf:54-60


      51 |   dynamic "ingress" {
      52 |     for_each = each.value.ingress
      53 | 
      54 |     content {
      55 |       description = lookup(ingress.value, "description", "")
      56 |       from_port   = ingress.value.from_port
      57 |       to_port     = ingress.value.to_port
      58 |       protocol    = ingress.value.protocol
      59 |       cidr_blocks = lookup(ingress.value, "cidr_blocks", null)
      60 |     }
      61 |   }
      62 | 
      63 |   dynamic "egress" {

  Legacy ID:  AWS018
  Impact:     Descriptions provide context for the firewall rule reasons
  Resolution: Add descriptions for all security groups and rules
```

4. But since in error message present not rendered ingress, it's not really actionable.
5. And, moreover, if we remove description from another ingress rule, `test1 http any`, there will be still one error, which is probably not correct.

**Expected behavior**

Blocks of code in error messages should contain rendered content with filled variables. 
Or, if it's hard or impossible, it could be excluded from output message.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 10.15
 - tfsec v0.58.14

**Additional context**
Seems it expected behaviour, I see in other issues the same output https://github.com/aquasecurity/tfsec/issues/493#issue-734352345
Maybe it's better to hide it at all then and add to documentation?

P.S. Haven't found similar issue created before.

**Comment by liamg** [comment]
Hey @nantiferov - I think in the case above we wouldn't expect an annotation. We attach results to either an entire block e.g. resource (i.e. in the case of "missing description"), or to an attribute (i.e. this attribute has a bad value). In the latter case, we annotate the attribute with the derived value as you described above, but not in the former case as the result is associated with the entire resource, not any particular added attribute.

I believe the dynamic blocks scenario would work for a check like `aws-vpc-no-public-egress-sg` where a particular attribute is linked to the result.
