### ISSUE TITLE
No recheck switch in tfsec

### ISSUE THREAD

**Issue by djdta** [aquasecurity/tfsec#1125]
**Describe the bug**
Currently, there is not there is no recheck command in tfsec to allow rechecking of terraform code.

**To Reproduce**
1. Go to your terraform in question
2. Run tfsec --tfvars-file `Name of file`
3. Then rerun the same command from step 3
4. 

**Expected behavior**
Would be nice to have a recheck command or something similar

**Screenshots**

**Desktop (please complete the following information):**
 - Linux

**Additional context**

**Comment by owenrumney** [comment]
Hi @djdta - can you elaborate on what you're asking for? I don't understand what the recheck would be for. Each run of tfsec is atomic and runs as a snapshot of your code.

**Comment by djdta** [comment]
Hi @owenrumney 

The issue is i checked my code and found some issues, then when i wanted to recheck it, there was no ability to do that.  Maybe a switch can be added for recheck,  Something like the following

tfsec --recheck

**Comment by owenrumney** [comment]
If I understand correctly you're looking for the diff between the outputs of two checks by running recheck?

Tfsec runs as a point in time operation and reports the issues at that time. No history of runs is retained to verify previous failures are now fixed. 

This isn't something we will be adding. A possible solution if your workflow is to try and resolve specific failures in a project could be to use the `--filter-results` flag to only return results of a specific type.
