### ISSUE TITLE
AWS099 should not apply to policies that require a star policy to function

### ISSUE THREAD

**Issue by dmonego** [aquasecurity/tfsec#1128]
**Describe the bug**
AWS099 is applied to IAM policies that are required to have a * resource policy. 

**To Reproduce**
1. Create a lambda in terraform
2. Give it the necessary permissions to join a VPC:

```
  statement {
    effect = "Allow"
    actions = [
      "ec2:CreateNetworkInterface",
      "ec2:DescribeNetworkInterfaces",
      "ec2:DeleteNetworkInterface",
      "ec2:AssignPrivateIpAddresses",
      "ec2:UnassignPrivateIpAddresses"
    ]

    resources = [
      "*"
    ]
  }
```
3. Run tfsec on the terraform directory.

**Expected behavior**
All of these policies can only be applied to "*". Applying them to "*" should not generate an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/526218/139487477-e4255083-5cf4-4c1e-885d-bea3c1cb9553.png)

**Desktop (please complete the following information):**
 - OS: OSX Big Sur

**Comment by liamg** [comment]
We generate a huge list of actions which require a `*` resource from the AWS docs, so it looks like something is missing from that list. All of the actions in your list have a required resource type in the docs, so it could even be an issue in their docs. Which one of those seems to cause the problem in the AWS UI? Or is it more than one?

The page I'm referencing is here: https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonec2.html

**Comment by dmonego** [comment]
Thanks for the followup. Beating through this statement by statement, it appears that `ec2:DescribeNetworkInterfaces` is the culprit.

**Comment by liamg** [comment]
Yeah, `ec2:DescribeNetworkInterfaces` requires the use of `*`, but it looks like the other actions you're using can have specific resources specified rather than `*` which is why tfsec is finding a problem.
