### ISSUE TITLE
Usage of `--force-all-dirs` messes up relative paths on modules `source` definition

### ISSUE THREAD

**Issue by skuethe** [aquasecurity/tfsec#1129]
**Describe the bug**

As noted in #567 we need to make use of the `--force-all-dirs` flag when we have a `.tf` file in the root directory but also want to scan files in subdirectories.
When applying this flag, modules defined in subdirectories, which make usage of relative paths, break, because the root path is used instead of the actual path of each subdirectory.

**To Reproduce**

Setup directory structure:

```shell
~/git/github/[ORG]/tf-mod $ tree -d
.
├── azure
│   ├── resource_groups
│   ├── virtual_network
└── tests
    └── azure
        ├── virtual_network
```

Setup testing files for `virtual_network`:

```shell
~/git/github/[ORG]/tf-mod $ grep -ri -B1 "\ssource\s=" tests/azure/virtual_network/main.tf
module "resource_groups" {
  source = "../../../azure/resource_groups"
--
module "vnet" {
  source = "../../../azure/virtual_network/"
```

Execute `tfsec` command WITHOUT `--force-all-dirs` flag - everything is fine:

```shell
~/git/github/[ORG]/tf-mod $ tfsec . >/dev/null; echo $?
0
```

Execute `tfsec` command WITH `--force-all-dirs` flag - module loading is failing:

```shell
~/git/github/[ORG]/tf-mod $ tfsec . --force-all-dirs >/dev/null; echo $?
WARNING: Failed to load module: failed to load module resource_groups: open /home/[USERNAME]/git/azure/resource_groups: no such file or directory
WARNING: Failed to load module: failed to load module vnet: open /home/[USERNAME]/git/azure/virtual_network: no such file or directory
0
```

**Expected behavior**

As can be seen, when providing the flag, it is using the root path to adopt the path of `../../../`, so it tries to include the path (f.e.):  
`~/git/azure/resource_groups`  
Instead of:  
`~/git/github/[ORG]/tf-mod/azure/resource_groups`

**Desktop (please complete the following information):**
 - OS:
     ```shell
    $ lsb_release -d
    Description:    Linux Mint 20.2
    ```
- version:
    ```shell
    $ tfsec --version
    0.58.14
    ```

**Comment by owenrumney** [comment]
Please feel free to reopen if this hasn't been resolved. I strongly suspect the changes will mean it has
