### ISSUE TITLE
Custom check not working 

### ISSUE THREAD

**Issue by venkyio** [aquasecurity/tfsec#1130]
**Describe the bug**
Custom check not working.
I have used https://github.com/aquasecurity/tfsec/tree/master/example/1000

**To Reproduce**
1. Download tfsec and download files from https://github.com/aquasecurity/tfsec/tree/master/example/1000
2. And go to the tf directory and Run `tfsec .`

**Expected behavior**
Custom check should run and raise error.
I can see no custom checks loaded.

**Desktop (please complete the following information):**
 - Mac (mChip)

**Comment by owenrumney** [comment]
Hi @venkyio  - can you run this with `--verbose` and provide the output please so we can further investigate.

**Comment by owenrumney** [comment]
Closing due to no response. Please feel free to reopen if required
