### ISSUE TITLE
[bug] should tfsec for GC change recommendation for image os type for cluster nodes

### ISSUE THREAD

**Issue by ShreyShah977** [aquasecurity/tfsec#1141]
**Describe the bug**
The default os image type for cluster nodes now by GCP is now `COS_CONTAINERD`, while `tfsec` recommends using `COS`.

GCP Page: https://cloud.google.com/kubernetes-engine/docs/concepts/using-containerd
>  Starting with GKE node version 1.19, the default node image for Linux nodes is Container-Optimized OS with containerd (cos_containerd) instead of Container-Optimized OS with Docker (cos).

GCP recommends migrating to `COS_CONTAINERD`

`tfsec` issue ID page: https://tfsec.dev/docs/google/gke/node-pool-uses-cos/#google/gke

Should the suggested resolution be changed to match recommended option (`COS_CONTAINERD`) from GCP?

**To Reproduce**
1. Obtain suggestion warning of type: `https://tfsec.dev/docs/google/gke/node-pool-uses-cos/#google/gke`
2. See that the recommended option from GCP is `COS_CONTAINERD` not `COS`.
3. See that the [tfsec page](https://tfsec.dev/docs/google/gke/node-pool-uses-cos/#google/gke) option recommend conflicts with GCP's.
> Use the COS image type

**Expected behavior**
The suggested resolution is to use the `COS_CONTAINERD` image type.

**Screenshots**
See links to both websites above.

**Desktop (please complete the following information):**
- macOS but applies to all.

**Additional context**

**Comment by owenrumney** [comment]
@ShreyShah977  - can you confirm your version? tfsec failed when not using COS_CONTAINERD https://github.com/aquasecurity/tfsec/blob/68af1966652bce85363c71be789309d6706ab1a6/internal/app/tfsec/rules/google/gke/node_pool_uses_cos_rule.go#L112
