### ISSUE TITLE
Which docker image should be used aquasec/tfsec or tfsec/tfsec?

### ISSUE THREAD

**Issue by vanmash** [aquasecurity/tfsec#1144]
**Describe the bug**
Which docker repo should be used? 
In the [README.md](https://github.com/aquasecurity/tfsec#use-with-docker) both are mentioned, [aquasec/tfsec](https://hub.docker.com/r/aquasec/tfsec) and [tfsec/tfsec](https://hub.docker.com/r/tfsec/tfsec)

**Comment by owenrumney** [comment]
Aquasec/tfsec. 

The other one was legacy for people who didn't know tfsec was acquired by Aqua Security

**Comment by vanmash** [comment]
@owenrumney 
perhaps you could put this information on the old [tfsec Docker hub page](https://hub.docker.com/r/tfsec/tfsec)?

**Comment by owenrumney** [comment]
done
