### ISSUE TITLE
[question] Add option to sort a report by criticality

### ISSUE THREAD

**Issue by vanmash** [aquasecurity/tfsec#1149]
**Is your feature request related to a problem? Please describe.**
I would like to have an option to sort finding by criticality, from CRITICAL to LOW for example

**Comment by vanmash** [comment]
Hey @owenrumney 

it looks like this option is removed in v1.0.2

Updating from 1.0.0 to v1.0.2
Error: unknown flag: --sort-severity
Usage:
unknown flag: --sort-severity

**Comment by owenrumney** [comment]
Hey @vanmash  - they're sorted by severity by default from v1 onwards

It was detailed in the breaking changes section of the release - https://github.com/aquasecurity/tfsec/releases/tag/v1.0.0
