### ISSUE TITLE
bump tfsec version on chocolatey

### ISSUE THREAD

**Issue by vanmash** [aquasecurity/tfsec#1159]
Hi

can you upload a new version to Chocolatey
https://community.chocolatey.org/packages/tfsec

also check virus report at https://community.chocolatey.org/packages/tfsec#virus

**Comment by owenrumney** [comment]
Done - https://community.chocolatey.org/packages/tfsec/0.60.1 It's pending

Also, very little we can do about the virus report, its a false positive which seems to be shared by a lot of Go based applications

**Comment by vanmash** [comment]
thanks @owenrumney  

PS: there is a nice workaround for this
`choco install tfsec`
`tfsec --update`
