### ISSUE TITLE
google_compute_subnetwork there is no enable_flow_logs Arugments

### ISSUE THREAD

**Issue by sandyvanam** [aquasecurity/tfsec#1161]
**Describe the bug**
google_compute_subnetwork there is no enable_flow_logs Arugments
https://tfsec.dev/docs/google/compute/enable-vpc-flow-logs/#google/compute
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_subnetwork#enable_flow_logs

**Comment by owenrumney** [comment]
Thanks @sandyvanam  - this will be in the next release (today)
