### ISSUE TITLE
Wrong configuration snippet for PR Commenter docs

### ISSUE THREAD

**Issue by nilya** [aquasecurity/tfsec#1166]
**Describe the bug**
The PR Commenter guide https://tfsec.dev/docs/pr-commenter/ has broken configuration snippet.
`github_token: $`
instead of
`github_token: ${{ secrets.GITHUB_TOKEN }}`

Such snippet doesn't work.

**To Reproduce**
1. follow the instruction https://tfsec.dev/docs/pr-commenter/ to set up the checker for your repository
2. make PR in your repository
3. open Actions
4. See error "tfsec failed to create a new commenter. PR number [XXX] not found for"

**Expected behavior**
Instruction has the GITHUB_TOKEN variable in the snippet and PR Commenter works.

**Screenshots**
![image](https://user-images.githubusercontent.com/131207/144185694-a1c82669-21cb-4a5d-9d94-f1652cb9a6ea.png)

**Desktop (please complete the following information):**
 - OS: Firefox web browser

**Additional context**
--

**Comment by owenrumney** [comment]
thanks @nilya  - that's been resolved now
