### ISSUE TITLE
Unable to install tfsec using Chocolatey

### ISSUE THREAD

**Issue by RyanTreanor3** [aquasecurity/tfsec#1170]
**Describe the bug**
When trying to install tfsec using Chocolatey: choco install tfsec -y
It calls this url: https://github.com/aquasecurity/tfsec/releases/download/v0.60.1/tfsec-windows-amd64.exe
Which returns a 403 and doesn't seem to exist.

ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/aquasecurity/tfsec/releases/download/v0.60.1/tfsec-windows-amd64.exe'. Exc
eption calling "GetResponse" with "0" argument(s): "The remote server returned an error: (403) Forbidden."
This package is likely not broken for licensed users - see https://docs.chocolatey.org/en-us/features/private-cdn.
The install of tfsec was NOT successful.
Error while running 'H:\developer\chocolatey\lib\tfsec\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (H:\developer\chocolatey\logs\chocolatey.log).

Failures
 - tfsec (exited 404) - Error while running 'H:\developer\chocolatey\lib\tfsec\tools\chocolateyinstall.ps1'.
 See log for details.

**Comment by owenrumney** [comment]
Hi @RyanTreanor3  - its just downloading from the releases page - https://github.com/aquasecurity/tfsec/releases/tag/v0.60.1

Is this the first time you're downloading it? Are you behind a corporate proxy or similar?
