### ISSUE TITLE
Install Error: package io/fs: unrecognized import path "io/fs" (import path does not begin with hostname)

### ISSUE THREAD

**Issue by CheneyZeng** [aquasecurity/tfsec#1179]
**Describe the bug**
We used to use `go get -u github.com/aquasecurity/tfsec/cmd/tfsec` to install the tfsec, but the current new version >v0.63.0.

We currently use `GO111MODULE=on go get -u github.com/aquasecurity/tfsec/cmd/tfsec@v0.61.3` to fix the version.

**To Reproduce**
Our environment is AWS codebuild Dockerfile `docker: 18`

**Expected behavior**
Install sucessfully.

**Screenshots**
<img width="872" alt="Screen Shot 2021-12-08 at 3 17 44 PM" src="https://user-images.githubusercontent.com/28200206/145306478-5c09a733-5553-422f-9bd7-7a06134a1c8c.png">

**Desktop (please complete the following information):**
 - AWS codebuild, Dockerfile `docker: 18`

**Comment by skadz** [comment]
From looking at this: https://github.com/tdewolff/minify/issues/388

It looks like whatever change was made has forced a minimum version of 1.16 (which is not great, since CodeBuild only supports up to 1.14 right now)

**Comment by liamg** [comment]
It looks like CodeBuild supports later versions of go now - or is this still an issue?

**Comment by skadz** [comment]
Codebuild supports 1.16, but only in one of their images.  That being said, the 1.X versions of tfsec seem to only support Go 1.17, so it is once again broken for anyone using AWS to test their stuff.


# github.com/aquasecurity/tfsec/internal/pkg/adapter/aws/iam
77 | /go/pkg/mod/github.com/aquasecurity/tfsec@v1.1.5/internal/pkg/adapter/aws/iam/passwords.go:52:40: undefined: math.MaxInt
78 | note: module requires Go 1.17
79

<br class="Apple-interchange-newline">

**Comment by liamg** [comment]
Yeah, it's frustrating that it takes a while for AWS to support stable versions. I would recommend downloading the latest binary straight from releases instead.
