### ISSUE TITLE
Check: Ensure plaintext value is not used for GitHub Action Environment Secret

### ISSUE THREAD

**Issue by owenrumney** [aquasecurity/tfsec#1182]
Add a tfsec check to ensure that the plaintext value is not set on the GitHub provider resource `github_actions_environment_secret`

Documentation for Provider: https://registry.terraform.io/providers/integrations/github/latest/docs/resources/actions_environment_secret

### What is required
- [ ] create a new check in `internal/app/tfsec/rules/github/actions` to check `plaintext_value` has not been set on `github_actions_environment_secret`. The `actions` folder will need creating
- [ ] Check properties must be `no_plain_text_secrets` 
  - [ ] Provider: provider.GitHubProvider
  - [ ] Service: actions
  - [ ] ShortCode: no-plain-text-secrets 
  - [ ] Add Sensible Documentation values
  - [ ] RequiredTypes: resource
  - [ ] RequiredLabels: github_actions_environment_secret
- [ ] Provide a Bad and good example - this is just the body of the resource, with and without the `plaintext_value` set
- [ ] Add a suitably simple `CheckFunc` which checks if there is a `plaintext_value`
- [ ] Submit a PR in accordance with https://github.com/aquasecurity/tfsec/blob/master/CONTRIBUTING.md

**Comment by liamg** [comment]
Looks like this was added at some point.
