### ISSUE TITLE
v0.63.1 release missing assets

### ISSUE THREAD

**Issue by arbourd** [aquasecurity/tfsec#1184]
It seems that goreleaser is having issues uploading all the assets. In this case with the latest release, it's the Windows binary.

I looked at the `.goreleaser.yml` and it looks fine. Must be an issue with the Github API or GoReleaser action.

<img width="940" alt="Screen Shot 2021-12-11 at 11 15 46 PM" src="https://user-images.githubusercontent.com/7211830/145700026-be807761-d7fe-431b-9a49-7a94ac71ad0f.png">

**Comment by roryprimrose** [comment]
Same as `v0.63.0`
