### ISSUE TITLE
Azure postgresql server configuration isn't recognized even though a block exists

### ISSUE THREAD

**Issue by shayfisher** [aquasecurity/tfsec#1185]
Trying to create an Azure Postgresql server.
Fails the following checks (medium severity) for the following resource type: azurerm_postgresql_server
There is a following block for the resource type of azurerm_postgresql_configuration which configures the following configurations:
log_connections
log_checkpoints
connection_throttling

1. Create a server configuration for azurerm_postgresql_server.
2. add azurerm_postgresql_configuration block which references the server from (1) and configures - log_connections, log_checkpoints, connection_throttling to be on.
3. Run tfsec against the configuration.

**Expected behavior**
tfsec shouldn't alert about those configurations.

**Comment by gabrielleecredera** [comment]
can't seem to reproduce the issue? using the following terraform code:
```tf
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_postgresql_server" "example" {
  name                             = "example-psqlserver"
  location                         = azurerm_resource_group.example.location
  resource_group_name              = azurerm_resource_group.example.name
  ssl_minimal_tls_version_enforced = "TLS1_2"
  public_network_access_enabled    = false
  ssl_enforcement_enabled          = true
}

resource "azurerm_postgresql_configuration" "example1" {
  name                = "log_checkpoints"
  resource_group_name = azurerm_resource_group.example.name
  server_name         = azurerm_postgresql_server.example.name
  value               = "on"
}

resource "azurerm_postgresql_configuration" "example2" {
  name                = "connection_throttling"
  resource_group_name = azurerm_resource_group.example.name
  server_name         = azurerm_postgresql_server.example.name
  value               = "on"
}

resource "azurerm_postgresql_configuration" "example3" {
  name                = "log_connections"
  resource_group_name = azurerm_resource_group.example.name
  server_name         = azurerm_postgresql_server.example.name
  value               = "on"
}
```
@shayfisher

**Comment by shayfisher** [comment]
Hi @gabrielleecredera ,

Probably was something with an older version - I wish I would have documented the version I've used but I didn't.
I've verified now with 0.63.1 and it seems to be working correctly.
Thank you!
