### ISSUE TITLE
Docs on "checks" should show vulnerability levels (low, medium, etc)

### ISSUE THREAD

**Issue by gl-amagana** [aquasecurity/tfsec#1199]
**Is your feature request related to a problem? Please describe.**
When viewing the docs on `checks`, there should be a clear label as to what level vulnerability a certain check is.

**Describe the solution you'd like**
For example, if I go to `checks` > `aws` > `s3` > `enable-bucket-encryption` I should immediately see that this is a HIGH-level vulnerability.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by owenrumney** [comment]
Thanks @gl-amagana  - its done now, waiting on the next release to appear
