### ISSUE TITLE
Azure network - convert tfsec checks to use defsec logic

### ISSUE THREAD

**Issue by vanesasejdiu** [aquasecurity/tfsec#1237]
Adapt Azure network to Go struct based on #1194 instructions:

Remove tfsec logic from `internal/app/tfsec/rules/azure/network/disable_rdp_from_internet_rule.go`
`internal/app/tfsec/rules/azure/network/no_public_egress_rule.go`
`internal/app/tfsec/rules/azure/network/no_public_ingress_rule.go`
`internal/app/tfsec/rules/azure/network/retention_policy_set_rule.go`
`internal/app/tfsec/rules/azure/network/ssh_blocked_from_internet_rule.go`

Create adapt functions to populate the Go struct in `internal/app/tfsec/adapter/azure/network/adapt.go`

**Comment by vanesasejdiu** [comment]
Working on this but the tests [`"check RDP is acceptable from a specific source"`](https://github.com/aquasecurity/tfsec/blob/master/internal/app/tfsec/rules/azure/network/disable_rdp_from_internet_rule_test.go#L177) and [`"check RDP is acceptable from a specific source on security group"`](https://github.com/aquasecurity/tfsec/blob/master/internal/app/tfsec/rules/azure/network/disable_rdp_from_internet_rule_test.go#L193 ) keep failing. 
On defsec [`cidr.IsPublic()`](https://github.com/aquasecurity/defsec/blob/master/rules/azure/network/disable_rdp_from_internet.go#L37) returns true for `"4.53.160.75"`. Should it?

@owenrumney @liamg

**Comment by liamg** [comment]
@vanesasejdiu Good point, this is a bug. I refactored the CIDR checking code to properly detect whether a range includes any public IPs, but this means we now need to use a function that counts the addresses inside a CIDR and the check can see if the count is > 1. You can instead use `cidr.CountAddresses(myCidr)` instead :crossed_fingers:

**Comment by liamg** [comment]
Hey @vanesasejdiu - I'll take a look, the tests could well need updating to take into account the tweaked logic - do you have a working branch I can experiment with?
