### ISSUE TITLE
Azure database - convert tfsec checks to use defsec logic

### ISSUE THREAD

**Issue by vanesasejdiu** [aquasecurity/tfsec#1238]
Adapt Azure databases to Go structs based on #1194 instructions:

Remove tfsec logic from `internal/app/tfsec/rules/azure/database/all_threat_alerts_enabled_rule.go`
`internal/app/tfsec/rules/azure/database/enable_audit_rule.go`
`internal/app/tfsec/rules/azure/database/enable_ssl_enforcement_rule.go`
`internal/app/tfsec/rules/azure/database/no_public_access_rule.go`
`internal/app/tfsec/rules/azure/database/no_public_firewall_access_rule.go`
`internal/app/tfsec/rules/azure/database/postgres_configuration_log_checkpoints_rule.go`

Create adapt functions to populate the Go structs in `internal/app/tfsec/adapter/azure/database/adapt.go`

**Comment by vanesasejdiu** [comment]
This one is done, waiting on the latest defsec version.

**Comment by liamg** [comment]
Cool, I've merged and tagged `v0.3.16`  of defesc now :+1:
