### ISSUE TITLE
Publish official docker images for arm64 too?

### ISSUE THREAD

**Issue by lavaturtle** [aquasecurity/tfsec#1244]
**Is your feature request related to a problem? Please describe.**
We're trying to switch our CI system from amd64 machines to arm64, to save money on AWS. We're running into a problem with our builds that use tfsec, because the docker image for tfsec is only published for amd64 architecture.

**Describe the solution you'd like**
If there was an arm64 version of the [tfsec docker image](https://hub.docker.com/r/aquasec/tfsec), that would be ideal.

**Describe alternatives you've considered**
We're working on trying to build such a docker image ourselves, using the Dockerfile in this repository, but it's proving somewhat difficult because of our limited knowledge of docker and go.

**Additional context**
I think the above covers it. Thank you for considering our request!

**Comment by lavaturtle** [comment]
Update: We've ended up building our own Dockerfile that uses the "install with Go" method to install tfsec, and that seems to work for our purposes.

**Comment by owenrumney** [comment]
Hey @lavaturtle  - sounds like something that more people are going to be doing so I'll  add this to the release process, thanks

**Comment by lavaturtle** [comment]
Awesome, thank you!
