### ISSUE TITLE
Digital Ocean spaces - convert tfsec checks to use defsec logic

### ISSUE THREAD

**Issue by vanesasejdiu** [aquasecurity/tfsec#1256]
Adapt Digital Ocean spaces to Go structs based on #1194 instructions:

Remove tfsec logic from `internal/app/tfsec/rules/digitalocean/spaces/acl_no_public_read_rule.go`
`internal/app/tfsec/rules/digitalocean/spaces/disable_force_destroy_rule.go`
`internal/app/tfsec/rules/digitalocean/spaces/versioning_enabled_rule.go`

Create adapt functions to populate the Go structs in `internal/app/tfsec/adapter/digitalocean/spaces/adapt.go`

**Comment by atombrella** [comment]
Work is being done in #1246 :tada:

**Comment by vanesasejdiu** [comment]
@atombrella I'm sorry I only checked for opened issues. I already completed digital ocean spaces, but I'll leave compute alone. 
Please open an issue beforehand in the future so that we can avoid this.
