### ISSUE TITLE
Google SQL- convert tfsec checks to use defsec logic

### ISSUE THREAD

**Issue by vanesasejdiu** [aquasecurity/tfsec#1349]

**Comment by vanesasejdiu** [comment]
Working on this but tests are failing. In [defsec](https://github.com/aquasecurity/defsec/blob/master/rules/google/sql/no_public_access.go#L41) `cidr.IsPublic()` is returning true for `"108.12.12.0/24"`.

**Comment by liamg** [comment]
That does look like a public block - perhaps this is a broken test.
