### ISSUE TITLE
Scan "reusable infrastructure"

### ISSUE THREAD

**Issue by thisisalim** [aquasecurity/tfsec#1365]
I need to create VPCs for different environments, so vpc.tf is always the same, and anything different goes into another file called variables.tf.

In vpc.tf, there are 2 variables (port and IP address) used to define the ingress rule in the security group. Let's assume a user provides 0.0.0.0/0 on port 22 in the variables.tf file. That would open SSH on the world once the infrastructure is provisionned.

In order to address the above use case, I'm wondering if it wouldn't make sense to assess the output of a "terraform plan" command.

**Comment by liamg** [comment]
Hi @thisisalim - tfsec will resolve the variables in the variables.tf and work out whether or not vpc.tf is in violation. So this should already work dynamically dependent on the variables provided.
