### ISSUE TITLE
tfsec not scanning modules

### ISSUE THREAD

**Issue by lonecoder433** [aquasecurity/tfsec#1374]
**Describe the bug**
When I run tfsec, it scanning only resource blocks in the tf files not modules blocks, I am using modules to create resources, instead of direct resource blocks.
**To Reproduce**
.create a modules for any gcp resource in a folder and use that module in another folder by giving public access.

**Expected behavior**
It should scan modules and provide tfsec output that it has scanned modules. 

**Screenshots**
![image](https://user-images.githubusercontent.com/90032329/150755897-4bf32f63-2382-40ba-bba8-ee8333320028.png)

**Desktop (please complete the following information):**
macOS Monterey 12.1
--
**Additional context**
I am using yaml file for variables instead of json or tfvars. I am decoding yaml in terraform locals. Please let me know if that is causing the issue.

**Comment by lonecoder433** [comment]
tfsec --verbose output

[DEBUG][2022-01-24 09:28:22.675334 +0000 WET m=+0.072939626] Loading custom checks...
[DEBUG][2022-01-24 09:28:22.67543 +0000 WET m=+0.073035376] Using the default custom check folder
[DEBUG][2022-01-24 09:28:22.675433 +0000 WET m=+0.073037960] custom check directory set to /layers/00-project-owner/.tfsec
[DEBUG][2022-01-24 09:28:22.675438 +0000 WET m=+0.073043501] Custom checks loaded
[DEBUG][2022-01-24 09:28:22.675442 +0000 WET m=+0.073046960] checking for tfvars files using glob: /layers/00-project-owner/*.tfvars
[DEBUG][2022-01-24 09:28:22.678277 +0000 WET m=+0.075882585] Starting parser...
[DEBUG][2022-01-24 09:28:22.678289 +0000 WET m=+0.075893835] Finding Terraform subdirectories...
[DEBUG][2022-01-24 09:28:22.678371 +0000 WET m=+0.075976501] Found qualifying subdirectory containing .tf files: /layers/00-project-owner
[DEBUG][2022-01-24 09:28:22.678376 +0000 WET m=+0.075981085] Beginning parse for directory '/layers/00-project-owner'...
[DEBUG][2022-01-24 09:28:22.680667 +0000 WET m=+0.078272501] Added 9 blocks from /layers/00-project-owner/main.tf...
[DEBUG][2022-01-24 09:28:22.68069 +0000 WET m=+0.078295043] Added 1 blocks from /layers/00-project-owner/backend.tf...
[DEBUG][2022-01-24 09:28:22.680693 +0000 WET m=+0.078298376] Project root set to '/layers/00-project-owner'...
[DEBUG][2022-01-24 09:28:22.680695 +0000 WET m=+0.078300085] Loading TFVars...
[DEBUG][2022-01-24 09:28:22.680696 +0000 WET m=+0.078301543] Loading module metadata...
[DEBUG][2022-01-24 09:28:22.682127 +0000 WET m=+0.079732293] Evaluating expressions...
[DEBUG][2022-01-24 09:28:22.682198 +0000 WET m=+0.079802960] Starting iteration 1 of context evaluation...
[DEBUG][2022-01-24 09:28:22.682327 +0000 WET m=+0.079932460] Starting iteration 2 of context evaluation...
[DEBUG][2022-01-24 09:28:22.682408 +0000 WET m=+0.080012543] Loading modules...
[DEBUG][2022-01-24 09:28:22.682467 +0000 WET m=+0.080072376] Starting iteration 1 of context evaluation...
[DEBUG][2022-01-24 09:28:22.682534 +0000 WET m=+0.080139501] Starting scanner...
[DEBUG][2022-01-24 09:28:22.683498 +0000 WET m=+0.081103085] Running rule for general-secrets-sensitive-in-attribute-value on locals. (/layers/00-project-owner/main.tf)...
[DEBUG][2022-01-24 09:28:22.683553 +0000 WET m=+0.081157626] Running rule for general-secrets-sensitive-in-local on locals. (/layers/00-project-owner/main.tf)...

  times
  ------------------------------------------
  disk i/o             3.777916ms
  parsing HCL          6.833µs
  evaluating values    213.167µs
  running checks       1.026667ms

  counts
  ------------------------------------------
  files loaded         2
  blocks               10
  modules              0

  results
  ------------------------------------------
  critical             0
  high                 0
  medium               0
  low                  0
  ignored              0

No problems detected!

**Comment by owenrumney** [comment]
@lonecoder433  - I'm stuggling to see what could be the issue here? Are you able to post the module definition in `layers/00-project-owner/main.tf` or an approximation of it so we can see if there is something that tfsec is missing there?

**Comment by lonecoder433** [comment]
Here is my module definition
![image](https://user-images.githubusercontent.com/90032329/150808878-a061d6d8-0491-4584-bcad-45b1f42d7f43.png)
Here I am loading my vars through yaml
![image](https://user-images.githubusercontent.com/90032329/150809246-322b4281-e807-4e57-a001-b846bc7223ae.png)

**Comment by liamg** [comment]
@lonecoder433 Is your `config` variable defined as part of a `locals` block? If you can expand a little on what your code looks like I can replicate the setup here and try to reproduce the issue.
