### ISSUE TITLE
Unexpected .json extension added to --out filename when --format=json

### ISSUE THREAD

**Issue by andrassy** [aquasecurity/tfsec#1386]
**Describe the bug**
An unexpected `.json` extension is added to the provided filename when using the `--out` argument with `--format=json`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install tfsec v1.0.0-rc.2 : `go install github.com/aquasecurity/tfsec/cmd/tfsec@v1.0.0-rc.2`.
1. Run `tfsec --out=results.json --format=json` in a terraform containing directory.
1. A file is created called `results.json.json`.

**Expected behavior**
The output file should honour the provided filename.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OSX (but also Ubuntu, inside a GitHub action, I believe)

**Additional context**
This change will break the tfsec/tfsec-pr-commenter-action behaviour as the commenter will not find the `results.json` file.

**Comment by liamg** [comment]
Thanks for the heads-up. A fix is incoming shortly!

**Comment by liamg** [comment]
Fixed in `v1.0.0-rc.3`, building now: https://github.com/aquasecurity/tfsec/releases/tag/v1.0.0-rc.3

**Comment by andrassy** [comment]
I can confirm this is fixed for me in rc.3. Quick work folks! 💪
