### ISSUE TITLE
Check results are duplicated multiple times for modules

### ISSUE THREAD

**Issue by andrassy** [aquasecurity/tfsec#1390]
**Describe the bug**
Identical check findings are repeated multiple times. For example, this CRITICAL warning appears 37 times (I think, findings #32783 to #32819). Seems to affect all check types, not just this one.

```
 #32783 CRITICAL Security group rule allows ingress from public internet.
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 sno**************ing.tf Line 489
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  484  │   ingress {
  485  │     from_port = 443
  486  │     to_port   = 443
  487  │     protocol  = "tcp"
  488  │ 
  489  │     cidr_blocks = ["0.0.0.0/0"] # Accessible via VPC or a peered VPC.
  490  │   }
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
          ID aws-vpc-no-public-ingress-sgr
      Impact Your port exposed to the internet
  Resolution Set a more restrictive cidr range

  More Information
  - https://aquasecurity.github.io/tfsec/latest/checks/aws/vpc/no-public-ingress-sgr/
  - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule#cidr_blocks
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

..........repeated many times.......


#32819 CRITICAL Security group rule allows ingress from public internet.
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 sno**************ing.tf Line 489
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  484  │   ingress {
  485  │     from_port = 443
  486  │     to_port   = 443
  487  │     protocol  = "tcp"
  488  │ 
  489  │     cidr_blocks = ["0.0.0.0/0"] # Accessible via VPC or a peered VPC.
  490  │   }
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
          ID aws-vpc-no-public-ingress-sgr
      Impact Your port exposed to the internet
  Resolution Set a more restrictive cidr range

  More Information
  - https://aquasecurity.github.io/tfsec/latest/checks/aws/vpc/no-public-ingress-sgr/
  - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule#cidr_blocks
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```

**To Reproduce**
1. I'm currently working on a simple shareable repro case. 

**Expected behavior**
Each check is only reported once (or possible once for each expanded `for_each` occurrence.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.1
 - Go: go1.17.6 darwin/arm64
 - Terraform: 1.1.4

**Additional context**

**Comment by liamg** [comment]
@andrassy Thanks for the reprot - could this be because you are using the module(s) in multiple places so each instance is an occurrence of the module being used?

**Comment by andrassy** [comment]
🤔 Not this many usages, I don't think, @liamg.

Also, while it's not strictly a regression, when using --out now with format=json, the json is _also_ output to console. Under the current repetition situation this is giving me an ENORMOUS set of Console logs to wade through, even though the data is also written to file. Older versions didn't replicate the tfsec findings to Console, I think?

**Comment by liamg** [comment]
This stuff is very useful, thank you!

I'll address the JSON output issue now. I've tried a few basic setups and can't yet manage to reproduce the module issue so if you do find a valid case that'll be awesome. Could it otherwise be a combination of module usage instances + foreach/count? I'll keep exploring...

**Comment by andrassy** [comment]
The simplest thing I could do to get more check failures than I had expected was this:

```
module "lb" {
  source  = "snowplow-devops/alb/aws"
  version = "0.1.1"

  name                    = "snowplow-staging-iglu-lb"
  vpc_id                  = "vpc-00000000"
  subnet_ids              = ["subnet-00000000", "subnet-00000001"]
  health_check_path       = "/api/meta/health"
  ssl_certificate_arn     = "arn:aws:acm:us-east-1:000000000001:certificate/7400f139-bd15-48fa-a0eb-ba396b792b0e"
  ssl_certificate_enabled = true
}
```

But because the number of check failures is now humanly manageable (just 12 rather than the many thousands I was seeing before!), I could trace them through the referenced module. They relate to a series of security group rules created per subnet_id inside the module and they _do_ look like correct check failures! 🎉

🤔 I wonder, as a future enhancement, is there any way of either adding a reference to the module code that's triggering the check failure, or maybe even better, grouping errors by terraform line / check failure together (as one fix can resolve all the errors in a single stroke)?

Either way, I no longer believe this to be a bug. Thanks for your patience, @liamg.

**Comment by sergei-ivanov** [comment]
I can confirm I have the same problem with 1.0.0-rc.4.

**Comment by liamg** [comment]
@andrassy Thanks for digging into that. Yeah, I see that this output is far from ideal with respect to modules, especially when they become nested. I really like your idea of grouping results together, I'll take a look into this :+1:

**Comment by liamg** [comment]
I've raised a new issue here: https://github.com/aquasecurity/tfsec/issues/1403

Thanks for your help, closing this for now.

**Comment by sergei-ivanov** [comment]
Hm, I have top-level resources reported multiple times. I.e. even when there is no modules involved.

**Comment by sergei-ivanov** [comment]
Hi @liamg the problem does not seem to be related to resources _nested_ inside modules. Somehow the graph walk is affected even if modules are merely present. I managed to craft a minimal example for you.

```
$ tfsec --version
1.0.0-rc.5

$ uname -sri
Linux 5.4.0-94-generic x86_64
```

`test.tf`:
```hcl
module "label" {
  source      = "cloudposse/label/null"
  version     = "0.25.0"
  enabled     = true
  namespace   = "test"
  environment = "test"
}

resource "aws_security_group" "nodes" {
  name   = "${module.label.id}-asg"
  vpc_id = "123"
}
```

If I don't do a `terraform init`, I get one reported case of `aws-vpc-add-description-to-security-group`.
After I run `terraform init`, it gets reported twice.

**Comment by sergei-ivanov** [comment]
It also blows up `pre-commit` hook, because there's suddenly an overwhelming amount of output from tfsec, and we have a pretty large repo with over two hundred terraform modules. So this is a blocker for us.

**Comment by liamg** [comment]
@sergei-ivanov Ouch, yep, can reproduce here with your example. We're looking at it now.

**Comment by sergei-ivanov** [comment]
Oh, an important thing, this has cropped up as part an effort to upgrade to TF 1.1 and test whether the latest TFsec interoperates with it well (see #1188). My current terraform version:
```
$ terraform --version
Terraform v1.1.4
on linux_amd64
```
However, I briefly tried to revert back to terraform v1.0.11 and the problem is still there.
Mentioning it just in case it is somehow related to the recent changes in module resolution related to TF 1.1.

**Comment by liamg** [comment]
Found the issue, fix incoming. :man_facepalming:

**Comment by liamg** [comment]
Thanks for the info @sergei-ivanov - RC 7 is now building.

**Comment by sergei-ivanov** [comment]
I can confirm my issue has been fixed in RC7. Thanks!
