### ISSUE TITLE
Misreported aws-elastic-search-enable-domain-logging

### ISSUE THREAD

**Issue by sergei-ivanov** [aquasecurity/tfsec#1399]
**Describe the bug**
In some circumstances "Domain audit logging is not enabled" is misreported.

**To Reproduce**

Create an `aws_elasticsearch_domain` resource with multiple `log_publishing_options` blocks.

```hcl
resource "aws_elasticsearch_domain" "this" {

  domain_name           = "test"

  log_publishing_options {
    enabled                  = true
    log_type                 = "INDEX_SLOW_LOGS"
    cloudwatch_log_group_arn = "test"
  }

  log_publishing_options {
    enabled                  = true
    log_type                 = "SEARCH_SLOW_LOGS"
    cloudwatch_log_group_arn = "test"
  }

  log_publishing_options {
    enabled                  = true
    log_type                 = "ES_APPLICATION_LOGS"
    cloudwatch_log_group_arn = "test"
  }

  log_publishing_options {
    enabled                  = true
    log_type                 = "AUDIT_LOGS"
    cloudwatch_log_group_arn = "test"
  }
}

```

**Expected behavior**

No issue because `AUDIT_LOGS` has been configured.

**Desktop (please complete the following information):**
 - OS: Linux x86
 - TFsec: 1.0.0-rc.4

**Additional context**

Looks like the problem might be here:
https://github.com/aquasecurity/tfsec/blob/53706472e2b013416a79e9216f69118f012dbd0f/internal/pkg/adapter/aws/elasticsearch/adapt.go#L35-L36

Instead of inspecting the first block, the code should iterate through all available `resource.getBlocks(...)`.

**Comment by liamg** [comment]
Thanks, good spot. Fix incoming.

**Comment by sergei-ivanov** [comment]
I can confirm it's been fixed in RC6. Thanks!
