### ISSUE TITLE
Group multiple instances of a module-based result

### ISSUE THREAD

**Issue by liamg** [aquasecurity/tfsec#1403]
When an issue is detected inside a module, and the module is used multiple times in a parent or root module, the issue will be detected once for each use of the module.

It would be a better experience if all of these "duplicate" results were grouped, and additionally contained details of the usage locations of each module.

Raised in #1390

**Comment by liamg** [comment]
@andrassy RC8 is now building with this feature. Hope it helps!

**Comment by andrassy** [comment]
This is really nice! Thanks @liamg!

Am I right in saying there is no grouping in json (or other non-default) formatted output? That would be the icing on the cake! 🍰

**Comment by liamg** [comment]
> This is really nice! Thanks @liamg!
> 
> Am I right in saying there is no grouping in json (or other non-default) formatted output? That would be the icing on the cake! cake

That's correct, only in the default output :)
