### ISSUE TITLE
CONTRIBUTING.md is incorrect and out of date 

### ISSUE THREAD

**Issue by drewmullen** [aquasecurity/tfsec#1412]
1. Docs [state](https://github.com/aquasecurity/tfsec/blob/e0af1c95d5f468b97e3b026c3ed996d7d6071cf4/CONTRIBUTING.md?plain=1#L11) to use the `make new-check` command but that doesnt exist in [Makefile](https://github.com/aquasecurity/tfsec/blob/master/Makefile)

```
$ make new-check
make: *** No rule to make target `new-check'.  Stop.
```

2. Checks no longer appear to be stored where [directed](https://github.com/aquasecurity/tfsec/blob/e0af1c95d5f468b97e3b026c3ed996d7d6071cf4/CONTRIBUTING.md?plain=1#L41) `/internal/apps/tfsec/rules`:

**Comment by liamg** [comment]
Good catch, I'll work on this shortly :+1:

**Comment by drewmullen** [comment]
@liamg lmk if you want me to review it (test it out). i have a few checks i want to add
