### ISSUE TITLE
Provider flag to output which checks are being ignored

### ISSUE THREAD

**Issue by drewmullen** [aquasecurity/tfsec#1416]
**Is your feature request related to a problem? Please describe.**
Often checks are ignored where deemed appropriate. However, it is incumbent on the team reviewing the PR to **catch** which checks are being ignored. It would be great to have a flag that runs in CI which outputs which checks are ignored in a root module

**Describe the solution you'd like**
`tfsec --list-ignored-checks` would output a succinct list of which flags are being ignored

There could be a followup request here to allow users to provide an explanation when they ignore a check that would then be outputted as part of `--list-ignored-checks`

**Comment by sergei-ivanov** [comment]
Although it is currently not part of TFsec ignore format, I tend to add a one line description after each ignore, like this:

```hcl
# tfsec:ignore:aws-vpc-add-description-to-security-group-rule:exp:2022-03-01 - TODO: add description
# tfsec:ignore:aws-vpc-no-public-egress-sgr - False positive, this is by design
resource "aws_security_group_rule" "nodes_https_egress" {
  ...
}
```

Maybe TFsec should recognise free-form comments like that and output them.
Another useful feature would be to detect obsolete ignores, but that deserves a separate ticket (#1449).

**Comment by owenrumney** [comment]
Its perfectly valid for multiple ignores to be placed on the same line which makes free form comments error prone in the parsing. I would say its good practice to add a comment

I don't think it would be too much to add the `--list-ignored-checks` flag though

**Comment by liamg** [comment]
The `--include-ignored` flag now correctly includes all ignored checks without affecting the result of the scan. The new `--no-ignores` flag stops ignore rules having any effect, causing all previously ignored results to fail.
