### ISSUE TITLE
bug: wrong service reported for `enforce-http-token-imds` check on `aws_instance`

### ISSUE THREAD

**Issue by sergei-ivanov** [aquasecurity/tfsec#1433]
**Describe the bug**

TFSec reports `aws-autoscaling-enforce-http-token-imds` result for `aws_instance`.
It should only report `aws-ec2-enforce-http-token-imds`.

**To Reproduce**

Run TFsec against the "insecure" example from [here](https://aquasecurity.github.io/tfsec/v1.0.1/checks/aws/ec2/enforce-http-token-imds/#insecure-example).
Both `aws-ec2-enforce-http-token-imds` and `aws-autoscaling-enforce-http-token-imds` are reported.

**Expected behavior**
Only `aws-ec2-enforce-http-token-imds` is reported.

**Desktop (please complete the following information):**

```
$ uname -irs
Linux 5.4.0-94-generic x86_64

$ tfsec --version
1.0.1

$ terraform --version
Terraform v1.1.4
on linux_amd64
```

**Comment by sergei-ivanov** [comment]
Looks like there is a similar reporting issue with `aws-autoscaling-enable-at-rest-encryption` and `aws_instance` resources (when it reports that "Root block device is not encrypted").

**Comment by owenrumney** [comment]
Thanks @sergei-ivanov  - I can reproduce this so will work out whats going on
