### ISSUE TITLE
feat: detect obsolete ignores

### ISSUE THREAD

**Issue by sergei-ivanov** [aquasecurity/tfsec#1449]
**Is your feature request related to a problem? Please describe.**

There is a chance of obsolete `tfsec:ignore` annotations accumulating in the source files. This could be because the problem was fixed in a submodule but the ignore was not removed from the root module. Or because TFsec renamed or retired the check.

**Describe the solution you'd like**

Either a separate command line option `--detect-obsolete-ignores` or make it a default setting that always applies.
It should list obsolete ignores at an info/notice level, so that they do not cause CI pipeline failures.

**Describe alternatives you've considered**

Periodic auditing and removing by hand? Does not scale well, and it's a waste of humans' time.

**Additional context**

N/A

**Comment by simar7** [comment]
Our efforts have moved to Trivy, we have a similar discussion for this issue here https://github.com/aquasecurity/trivy/discussions/4390
