### ISSUE TITLE
bug: different results between running tfsec from top level vs running module by module

### ISSUE THREAD

**Issue by sergei-ivanov** [aquasecurity/tfsec#1452]
**Describe the bug**

I believe there's a general issue with running tfsec from the root of the tree, where the tree contains a number of modules, some independent, some referring to other modules in the tree. 

**To Reproduce**

For example, we have a huge git repo that has the following structure:
```
/
  aws/
    modules/
      iam-role-xxx/
      iam-role-yyy/
      lambda-xxx/
      lambda-yyy/
      s3-backup-storage/
      s3-log-storage/
      s3-static-website/
      ...
```
There are more than 200 terraform modules in there.

Please note that I previously initialised all modules with `terraform init`.
If I run `tfsec .` from the top level, I get some errors like below, and then I have a bunch of failing checks.
```
WARNING: Did you forget to 'terraform init'? The following modules failed to load:
 - ./modules/instance
 - terraform-aws-modules/vpc/aws
 - ../../../modules/kms
 - ../../../modules/iam-role-s3-replication
...
WARNING: Did you forget to 'terraform init'? The following modules failed to load:
 - cloudposse/label/null
WARNING: Did you forget to 'terraform init'? The following modules failed to load:
 - cloudposse/label/null
...
```

If on the other hand, I crawl all module directories with `find` command and run `tfsec` inside each of them, I don't get "Did you forget to 'terraform init'?" errors, but I do get fewer/different check failures.

**Expected behavior**

Consistent results irrespective of where TFsec is being run.

**Desktop (please complete the following information):**

```
$ uname -irs
Linux 5.4.0-94-generic x86_64

$ tfsec --version
1.0.4

$ terraform --version
Terraform v1.1.4
on linux_amd64
```

**Comment by liamg** [comment]
This may be because running in a higher level or root module will be passing variable values into the child modules, whereas running directly on the child modules will be using the `default` values for all variables.

**Comment by sergei-ivanov** [comment]
My assumption was that if I run `tfsec .` from the top-level folder, it would:
1. scan for and collect all nested module folders
2. run analysis for each of the modules in isolation (but resolving, interpolating, and recursing into each module's dependencies)
3. collate the results

Essentially what my bash script does, only much slower:
```shell
readarray -t module_dirs < <(find . -name .terraform -prune , -type f -name '*.tf' -printf '%h\n' | sort | uniq)
for module_dir in "${module_dirs[@]}"; do
  (
    cd "${module_dir}"
    terraform init -backend=false
    tfsec
  )
done

```

**Comment by sergei-ivanov** [comment]
Please let me know if you'd like me to craft an example. I tried earlier to produce something small that would demonstrate the problem, but so far I could not. I may need to spend more time on it.

**Comment by liamg** [comment]
So by default it will treat the highest level folder it finds containing *.tf files (usually the current directory) as the *root* module, and only load subdirectories when required by module declarations, to mimic what Terraform itself will do. So if you have an issue in a module but that module is not used via a module block, tfsec will not report an issue inside it.

This is assuming you're not specifying the `--force-all-dirs` option which is a lot more aggressive in what it parses.

**Comment by sergei-ivanov** [comment]
No, I am running with the default settings (the only override is `--concise-output` for the pre-commit hook). Which means that `--exclude-downloaded-modules` is off, and `--force-all-dirs` is off.

**Comment by liamg** [comment]
Yeah, I think that explains it then, so input variables are taken into account when loading a module from a parent vs loading it directly by scanning it's directory.
