### ISSUE TITLE
bug: Setting key_ring on google_kms_crypto_key triggers a go error

### ISSUE THREAD

**Issue by ivocalado** [aquasecurity/tfsec#1460]
**Describe the bug**
When I try to set the key_ring value for google_kms_crypto_key when the value came from a google_kms_key_ring resource a go stack trace is shown. 

**To Reproduce**
1. Defines a google_kms_key_ring
2. Defines a google_kms_crypto_key and set key_ring from the google_kms_key_ring
3. Run tfsec on the dir

**Expected behavior**
Perform the tfsec analysis and eventually reporting errors. 

**Screenshots**
![image](https://user-images.githubusercontent.com/2104998/151848279-755aa5cc-ae48-4101-bf0e-02b487a39ee8.png)

**Desktop (please complete the following information):**
Docker image aquasec/tfsec-ci:latest running any version of tfsec from 1.0 up to 1.0.6

**Comment by owenrumney** [comment]
Hey @ivocalado  -this should be fixed in 1.0.7

**Comment by ivocalado** [comment]
@owenrumney , I just took a look on 1.0.7 but a new error is triggered:

![image](https://user-images.githubusercontent.com/2104998/151868265-63dc7c65-60d1-4008-a7d1-54f823ab6b67.png)

**Comment by owenrumney** [comment]
Can you raise a fresh issue please, that appears to be unrelated
