### ISSUE TITLE
bug: tfsec raises a nil pointer dereference error

### ISSUE THREAD

**Issue by ivocalado** [aquasecurity/tfsec#1465]
**Describe the bug**
When I try to set the key_ring value for google_kms_crypto_key when the value came from a google_kms_key_ring resource a go stack trace is shown.

**To Reproduce**

1. Defines a google_kms_key_ring
2. Defines a google_kms_crypto_key and set key_ring from the google_kms_key_ring
3. Run tfsec on the dir

**Expected behavior**
Perform the tfsec analysis and eventually reporting errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/2104998/151871322-2d6fe717-9e1c-44d8-8587-de97e300729e.png)

**Desktop (please complete the following information):**
Docker image aquasec/tfsec-ci:latest running any version of tfsec version 1.0.7

**Comment by liamg** [comment]
@ivocalado Please could you try with the latest master (`go install github.com/aquasecurity/tfsec/cmd/tfsec@master`) and see if your issue is resolved. If not please reopen and supply a code example that reproduces the issue and i'll take another look.

**Comment by ivocalado** [comment]
The problem has been solved at master

**Comment by liamg** [comment]
@ivocalado Awesome, thanks, `v1.0.8` is building now with this fix.
