### ISSUE TITLE
feat: Ignore or disable violation level  

### ISSUE THREAD

**Issue by tomverhees** [aquasecurity/tfsec#1471]
**Is your feature request related to a problem? Please describe.**
I want to be able to disable a whole level of violation. For example the low error level i want to disable but still run the checks on medium, high, critical. 

**Describe the solution you'd like**
I would like to have this possible with a simple flag in the ci to do this. To disable the violation level : low, etc. that when you have 45 errors for low but the rest there are 0 errors it will still pass. 

**Describe alternatives you've considered**
 So I dont want to disable the checks manually per check. which would be an alternative i think. Also ignoring warning individually is not an option i like. 

currently this is what we do: 
`docker run --rm --user $(id -u):$(id -g) -t -v "$(pwd)/infrastructure:/src" -v $(Common.TestResultsDirectory):/test aquasec/tfsec /src -f junit --out /test/tsec-results.xml --soft-fail`

But eventuelly we would like to remove the -f flag

**Comment by owenrumney** [comment]
Hey @tomverhees  - I've been thinking of solving this with a `--fail-threshold` flag that you can pass the severity you want to fail on. We'll add it to the backlog

**Comment by tomverhees** [comment]
> Hey @tomverhees - I've been thinking of solving this with a `--fail-threshold` flag that you can pass the severity you want to fail on. We'll add it to the backlog

That would be great thanks!

**Comment by liamg** [comment]
We now have the `--minimum-severity` flag :)

**Comment by dnlopes** [comment]
It seems that the `minimum-severity` option is broken in the YAML version. I have the following config files

```yaml
severity_overrides:
  aws-cloudwatch-log-group-customer-key: LOW
  aws-lambda-enable-tracing: LOW
  aws-iam-no-policy-wildcards: LOW
minimum_severity: CRITICAL
```

and the JSON version

```json
{
  "minimum_severity": "CRITICAL",
  "severity_overrides": {
    "aws-cloudwatch-log-group-customer-key": "LOW",
    "aws-lambda-enable-tracing": "LOW",
    "aws-iam-no-policy-wildcards": "LOW"
  }
}
```

and when running tfsec the output is different. Using version `v1.16.2`

**Comment by shpml** [comment]
Having the same issue with config in a yaml file.

config.yaml
``` 
---
minimum_severity: CRITICAL
exclude:
  - aws-s3-enable-versioning
  - aws-s3-enable-bucket-logging
```

Results:
```
  counts
  ──────────────────────────────────────────
  modules downloaded   0
  modules processed    12
  blocks processed     410
  files read           83

  results
  ──────────────────────────────────────────
  passed               155
  ignored              0
  critical             3
  high                 6
  medium               15
  low                  0

  155 passed, 24 potential problem(s) detected.
  ```
  
Passing the flag in the `--minimum-severity CRITICAL` flag as an argument works fine 
  
```
tfsec --minimum-severity CRITICAL --config-file tfsec.yaml

  counts
  ──────────────────────────────────────────
  modules downloaded   0
  modules processed    12
  blocks processed     410
  files read           83

  results
  ──────────────────────────────────────────
  passed               1
  ignored              175
  critical             3
  high                 0
  medium               0
  low                  0

  1 passed, 175 ignored, 3 potential problem(s) detected.
```

**Comment by liamg** [comment]
Closing this and opening a bug report here: https://github.com/aquasecurity/tfsec/issues/1663
