### ISSUE TITLE
bug: Setting resource_labels on google_container_cluster triggers a go error

### ISSUE THREAD

**Issue by ivocalado** [aquasecurity/tfsec#1484]
**Describe the bug**
When I try to set the resource_labels value for google_container_cluster a go stack trace is shown.

**To Reproduce**
1. Defines a google_container_cluster
2. Set parameter resource_labels receiving a map(string)
3. Run tfsec on the dir

**Expected behavior**
Perform the tfsec analysis and eventually reporting errors. 

**Screenshots/Output**
![image](https://user-images.githubusercontent.com/2104998/152163022-b433f9cb-4e12-47bd-8af7-aa4215e1408a.png)

**System Info**
Docker image aquasec/tfsec-ci:latest running version of tfsec from 1.0.8

**Comment by liamg** [comment]
This should be resolved in `v1.0.9` - it's building now.

**Comment by ivocalado** [comment]
Thank you @liamg
