### ISSUE TITLE
bug: high CPU usage. go-cty bug detected

### ISSUE THREAD

**Issue by chris3ware** [aquasecurity/tfsec#1490]
I recently upgraded tfsec to v1.0.11 following issue #1479 

The error has gone and the findings explorer is updated OK, however, I have two folders in my workspace and the results are only displayed for one of them.

If I run tfsec from the CLI in directory A, it run without issue, and completes in a few seconds

If I run tfsec from the CLI in directory B, the following DEBUG messages can be seen in the output and CPU use goes up to 200% for a few minutes:

`[DEBUG][2022-02-02 18:50:04.163435 +0000 GMT m=+278.673758791] go-cty bug detected - failed to derive value from expression: runtime error: invalid memory address or nil pointer dereference` - this message is repeated numerous (1000's) of times.

**Comment by liamg** [comment]
Hi @chris3ware, thanks for the report, are you able to provide any example code to help us reproduce the issue? A minimal template that causes the issue with anything sensitive removed would be great if possible.

**Comment by chris3ware** [comment]
Hi @liamg, it's a big repository with lots of modules in the .terraform folder. However I have tracked the problem down I think.

tfsec doesn't like the conditional expression on the cidr_block definition below:

```hcl
resource "aws_security_group_rule" "ecs_backend_https_outbound" {
  type              = "egress"
  from_port         = 443
  to_port           = 443
  protocol          = "tcp"
  security_group_id = aws_security_group.ecs_backend_admin.id
  // If endpoints are enabled ECR is reachable via the private subnets
  cidr_blocks = var.vpce_enabled ? local.private_subnets_cidr_blocks : ["0.0.0.0/0"]
}
```
However I have fixed the problem by changing it to the correct syntax:

```hcl
cidr_blocks = var.vpce_enabled ? [local.private_subnets_cidr_blocks] : ["0.0.0.0/0"]
```

I suspect the reason for the high CPU is because the security group rule resource is part of a child module, which is downloaded to several .terraform directories, so it will scan and error many time over.

The newest release of child module removes this syntax anyway so I've upgraded the parents and tested and tfsec runs without issue.

**Comment by chris3ware** [comment]
I've upgrade each of the parent modules now, so this code is no longer present in the path tfsec is analysing. It's running without issue.
