### ISSUE TITLE
question: AWS ELB rule

### ISSUE THREAD

**Issue by chris3ware** [aquasecurity/tfsec#1494]
Hi, I just wondered if, following  #1293 the following AWS ELB rule should work?

aws-elbv2-http-not-used

I have the following terraform code: 

```hcl
resource "aws_lb_listener" "http" {
  load_balancer_arn = aws_lb.this.arn
  port              = 80
  protocol          = "HTTP"

  default_action {
    type = "redirect"

    redirect {
      protocol    = "HTTPS"
      port        = 443
      status_code = "HTTP_301"
    }
  }
}
```

This isn't being picked up in vscode extension, the CLI or PR Commenter.

**Comment by liamg** [comment]
Hi @chris3ware The rule allows the use of `HTTP` if it is purely a redirect to `HTTPS` :+1:

**Comment by chris3ware** [comment]
Nice one. Thanks for confirming.
