### ISSUE TITLE
bug: S3 enable-bucket-encryption allows default aws managed keys

### ISSUE THREAD

**Issue by markhowardform3** [aquasecurity/tfsec#1499]
The Unencrypted S3 bucket check is [documented](https://aquasecurity.github.io/tfsec/v1.0.11/checks/aws/s3/enable-bucket-encryption/) as checking that customer managed keys are being used. 

> S3 Buckets should be encrypted with customer managed KMS keys and not default AWS managed keys, in order to allow granular control over access to specific buckets.

The [actual check code](https://github.com/aquasecurity/tfsec/blob/master/internal/pkg/adapter/aws/s3/bucket.go#L59) only looks for the presence of an `sse_algorithm`, which is set for both default managed and customer managed keys

**To Reproduce**

Run tfsec with a bucket using default server side encryption (non-customer managed keys)
```
resource "aws_s3_bucket" "test" {
  bucket = "test"
  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
    }
  }
}
```

**Expected behavior**
tfsec identified unencrypted bucket

**System Info**
 - tfsec version: `v1.0.11`

**Comment by owenrumney** [comment]
@markhowardform3  - this will be releases later this morning :crossed_fingers:
