### ISSUE TITLE
question: AWS SQS false positive AWS015 aws-sqs-enable-queue-encryption while SSE-SQS enabled

### ISSUE THREAD

**Issue by goatwu1993** [aquasecurity/tfsec#1521]
AWS SQS provides two encryption
- SSE-SQS
- SSE-KMS

with terraform, you can enable SSE-SQS by sqs_managed_sse_enabled = true. Not sure if this is the best practice

**Comment by owenrumney** [comment]
@goatwu1993  - there are checks across a lot of the services to nudge you to use customer managed keys (SSE-KMS in this case). The benefits are that you have more granular control over the keys (rotation etc)

**Comment by goatwu1993** [comment]
Thanks for explaining 👍
