### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Abansal-ninja** [aquasecurity/tfsec#1527]
**Description**
Found bug with check actions like equals, contains, startwith is not detecting Tag values case sensitivity when creating a custom check to scan for AWS tags. Refer the below example for more info. 

**To Reproduce**
For ex: 
As we know that both AWS Tags keys and values are case sensitive.  In _tfcheck.yaml file if you define to check tag with fruit = apple using any of the above mentioned check action, where in the terraform code you have the tag specified with fruit = Apple. You noticed the case sensitivity between the tag values apple & Apple, then the custom check does not detect anything and passes on. 

1.Add a tag key and value in your terraform code as shown below [fruit = "Apple"]
![image](https://user-images.githubusercontent.com/97044710/153434092-2a4fd2b1-e878-45ad-8099-411c4caacd0f.png)

2. create a custom check with below matchspec. you may use any other actions as well.
![image](https://user-images.githubusercontent.com/97044710/153434264-a42f6ec6-5d59-4ea1-a173-245e0ebf2edd.png)

3. After executing tfsec, we get the below output.
![image](https://user-images.githubusercontent.com/97044710/153434305-720f6622-2887-4df6-9b1e-1e123910f98b.png)

**Expected behavior**
tfsec should detect the case sensitivity of AWS tag values as well with any of the tfsec check actions. 
Please specify if there is any available check action which can detect the tag values case sensitivity.

**System Info**

 - tfsec version: v1.1.4
 - terraform version: v1.1.2
 - OS: windows 10 (19043.1466)

**Comment by owenrumney** [comment]
Duplicate of #1526
