### ISSUE TITLE
Unable to ignore single instances of aws-iam-no-policy-wildcards

### ISSUE THREAD

**Issue by mogggggg** [aquasecurity/tfsec#1535]
**Describe the bug**
If I create a service policy with multiple wildcards I only seem to be able to ignore the whole resource, I'm unable to ignore specific instances of it.

**To Reproduce**
```hcl
data "aws_iam_policy_document" "service" {
  statement {
    sid    = "AllowCloudWatchLogs"
    effect = "Allow"

    actions = [
      "logs:CreateLogGroup",
    ]

    resources = ["*"] # tfsec:ignore:aws-iam-no-policy-wildcards
  }

  statement {
    sid    = "AllowS3Write"
    effect = "Allow"

    actions = [
      "s3:GetObject"
    ]

    resources = ["*"]
  }
}

```

That example will pick up 2 potential problems.

**System Info**

 - tfsec version: `v1.1.5`
 - terraform version: `0.15.3?`
 - OS: `MacOS`

**Comment by liamg** [comment]
We should have a fix for this later today :+1:
