### ISSUE TITLE
bug: exclude-path seems to not be working

### ISSUE THREAD

**Issue by chtakahashi** [aquasecurity/tfsec#1545]
**Describe the bug**
`--exclude-path` is broken as of either 1.2.0 or 1.2.1

**To Reproduce**
1. Clone https://github.com/tfsec/tfsec-example-project and `cd` into it
2. Run `tfsec`. You should see 54 potential problems detected
3. Run `tfsec --exclude-path modules`. You should still see 54 potential problems detected

**Expected behavior**
Based on there being 7 issues contained in the modules directory, I would expect to see 47 potential problems detected when using the --exclude-path flag in the above example.

**Screenshots/Output**
N/A

**System Info**

 - tfsec version: `v1.2.1`
 - terraform version: `1.1.2`
 - OS: `Mac OS Monterey v12.2.1`

**Example Code**
https://github.com/tfsec/tfsec-example-project

**Additional context**

**Comment by chtakahashi** [comment]
just updated to v1.3.0 and noting the same behavior

**Comment by owenrumney** [comment]
thanks @chtakahashi  - will take a look at this
