### ISSUE TITLE
bug: --concise-output not doing what's supposed to

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [aquasecurity/tfsec#1546]
First of all, thanks for the tool. It's been of great help. I've been using it for a few months already, and it's actually taught me a thing or two, while performing flawlessly.

**Describe the bug**

A recently noticed that the behaviour to `--concise-output` might have changed.

`--help` states `--concise-output               Reduce the amount of output and no statistics` but I'm getting statistics.

**To Reproduce**

```shell
$ tfsec --concise-output
```

**Expected behavior**

* no statistics

**Screenshots/Output**

```
  timings
  ──────────────────────────────────────────
  disk i/o             502.959µs
  parsing              8.770285ms
  adaptation           282.887µs
  checks               1.556913ms
  total                11.113044ms

  counts
  ──────────────────────────────────────────
  blocks               8
  modules              1
  files                5

  results
  ──────────────────────────────────────────
  ignored              0
  excluded             0
  critical             0
  high                 0
  medium               0
  low                  0
```

**System Info**

 - tfsec version: 1.2.1
 - terraform version: 0.15.3 (which reminds me, I have to update 😄)
 - OS: macOS 11.6.1

**Comment by paulo-ferraz-oliveira** [comment]
I'm now on `terraform 1.1.6` but it doesn't make a difference (I didn't expect it to, either, but want to be complete).

**Comment by owenrumney** [comment]
Thanks @paulo-ferraz-oliveira  - this seems to have come out of the changes to the formatters, will take a look and get it fixed for the next release

**Comment by paulo-ferraz-oliveira** [comment]
Many thanks. It's not impactful, though... it's just extra info. in our CI we really don't require.

**Comment by paulo-ferraz-oliveira** [comment]
Hi.

Just tested this.

I'm not sure the output I got is the expected one.

```
➜  prod git:(env) ✗ tfsec --concise-output
  timings
  ──────────────────────────────────────────
  disk i/o             3.554859ms
  parsing              558.264µs
  adaptation           146.888µs
  checks               1.716684ms
  total                5.976695ms

  counts
  ──────────────────────────────────────────
  blocks               8
  modules              1
  files                5

  results
  ──────────────────────────────────────────
  ignored              0
  excluded             0
  critical             0
  high                 0
  medium               0
  low                  0


No problems detected!

➜  prod git:(env) ✗ tfsec --version
v1.5.0
```

Thanks.

**Comment by sergei-ivanov** [comment]
Hi @owenrumney, I have just updated to v1.6.2 and the problem is only partially fixed.
The `--concise-output` flag has effect _only when there are issues found_. If there are _no_ issues found, statistic table is still printed regardless of the flag. This creates a lot of noise when tfsec is used as a pre-commit hook.
