### ISSUE TITLE
bug: data source google_iam_policy crashes tfsec

### ISSUE THREAD

**Issue by JamesWoolfenden** [aquasecurity/tfsec#1550]
**Describe the bug**
scanning the resource google_iam_policy  example given, crashes tfsec

**To Reproduce**
Steps to reproduce the behaviour:
Scan 
```
resource "google_project_iam_policy" "positive1" {
  project     = "your-project-id"
  policy_data = data.google_iam_policy.positive1.policy_data
}

data "google_iam_policy" "positive1" {
  binding {
    role = "roles/cloudkms.admin"

    members = [
      "user:jane@example.com",
    ]
  }

  binding {
    role = "roles/cloudkms.cryptoKeyDecrypter"

    members = [
      "user:jane@example.com",
    ]
  }
}
```

**Expected behavior**
results, results

**Screenshots/Output**
Scan error: job failed: runtime error: invalid memory address or nil pointer dereference
goroutine 26 [running]:
runtime/debug.Stack()
        C:/Program Files/Go/src/runtime/debug/stack.go:24 +0x65
github.com/aquasecurity/tfsec/internal/pkg/executor.(*infraRuleJob).Run.func1()
        D:/tools/go/pkg/mod/github.com/aquasecurity/tfsec@v1.4.0/internal/pkg/executor/pool.go:98 +0x45
panic({0xe45ae0, 0x16936e0})
        C:/Program Files/Go/src/runtime/panic.go:1038 +0x215
github.com/aquasecurity/defsec/rules/google/iam.glob..func7(0xc0000de800)
        D:/tools/go/pkg/mod/github.com/aquasecurity/defsec@v0.12.0/rules/google/iam/no_project_level_default_service_account_assignment.go:34 +0x347
github.com/aquasecurity/defsec/rules.RegisteredRule.Evaluate({{{0xf03867, 0xc}, {0xf461c6, 0x33}, {0xf49f47, 0x38}, {0xf60aab, 0x75}, {0xf390db, 0x29}, ...}, ...}, ...)
        D:/tools/go/pkg/mod/github.com/aquasecurity/defsec@v0.12.0/rules/register.go:24 +0x2a
github.com/aquasecurity/tfsec/pkg/rule.(*Rule).CheckAgainstState(0xc0003f8ea8, 0x636785)
        D:/tools/go/pkg/mod/github.com/aquasecurity/tfsec@v1.4.0/pkg/rule/check.go:15 +0x7b
github.com/aquasecurity/tfsec/internal/pkg/executor.(*infraRuleJob).Run(0xc00044bc28)
        D:/tools/go/pkg/mod/github.com/aquasecurity/tfsec@v1.4.0/internal/pkg/executor/pool.go:102 +0x87
github.com/aquasecurity/tfsec/internal/pkg/executor.(*Worker).Start.func1(0x0, 0xc0000afb00)
        D:/tools/go/pkg/mod/github.com/aquasecurity/tfsec@v1.4.0/internal/pkg/executor/pool.go:139 +0x2a
github.com/aquasecurity/tfsec/internal/pkg/executor.(*Worker).Start(0xc0000afb00)
        D:/tools/go/pkg/mod/github.com/aquasecurity/tfsec@v1.4.0/internal/pkg/executor/pool.go:144 +0xb6
created by github.com/aquasecurity/tfsec/internal/pkg/executor.(*Pool).Run
        D:/tools/go/pkg/mod/github.com/aquasecurity/tfsec@v1.4.0/internal/pkg/executor/pool.go:40 +0xef

HEAD version of TFSec 12/2/2022
Terraform v1.1.3
fail on win & mac

**Comment by liamg** [comment]
Thanks for the report, this is now fixed in `v1.4.1`. The release assets should be available in ~5 minutes.
