### ISSUE TITLE
bug: tfsec fail when directory is symlink

### ISSUE THREAD

**Issue by zotrix** [aquasecurity/tfsec#1554]
**Describe the bug**
tfsec fail when directory is symlink inside scan folder
 

**To Reproduce**
```
❯ mkdir ci run && cd run && ln -sf ../ci ci && touch 1.tf && tfsec .
Scan error: read /tmp/tfsec-test/run/run/ci: is a directory

/tmp/tfsec-test
❯ tree .
.
├── ci
└── run
    ├── 1.tf
    └── ci -> ../ci

3 directories, 1 file
```

**Expected behavior**
scan succeeded
 
**System Info**

 - tfsec version: `v1.4.1`
 - terraform version: `none`
 - OS: `macos 12` or `alpine linux`

**Comment by owenrumney** [comment]
Hey @zotrix  - If I've understood this correctly, the creation of 1.tf is what is stopping it entering the lower ci directory. 

We traverse the root downwards till we find a tf file and start there - if run had sibling directories with tf in them we would also scan them. One option is to use `--force-all-dirs` or don't touch `1.tf` (although I assume you have your reasons for doing that)

**Comment by zotrix** [comment]
@owenrumney 
this is emulation to show flow and error.  Main ci folder and folder with terraform files on same level, symlink inside ` folder with terraform files ` point to main ci folder. 
Our CI systems has CI folder (symlink to main folder) on same level that terraform files. And in  that case tfsec fail. I don't see code but guess is incorrect symlink handling.

**Comment by zotrix** [comment]
```
tfsec-test/run/run
❯ tfsec --force-all-dirs .
Scan error: read /tmp/tfsec-test/run/run/ci: is a directory
```

As you suggest i added ` --force-all-dirs` flag. But same issue

**Comment by owenrumney** [comment]
can you provide the output of `tfsec --debug` please

**Comment by zotrix** [comment]
```
tfsec-test/run/run via 💠 default
❯ tfsec --debug  .
[debug:parse][root] Added file /tmp/tfsec-test/run/run/1.tf.
Scan error: read /tmp/tfsec-test/run/run/ci: is a directory```

**Comment by owenrumney** [comment]
@zotrix - this should be fixed in the latest release, its just building now so will be there in 5mins

**Comment by zotrix** [comment]
Thanks!
