### ISSUE TITLE
question: --sort-severity flag not available for v1.4.2

### ISSUE THREAD

**Issue by kangman** [aquasecurity/tfsec#1557]
I see this merged in but I can't seem to find the flag

https://github.com/aquasecurity/tfsec/pull/1151/commits/f28f846bca100b73a8f6a224a6b913b4adb3bd5f

is this not in the latest release?

**Comment by owenrumney** [comment]
Hi @kangman - `--sort-severity` was removed in `v1.0.0` when we switched to sorting results by severity as the default
https://github.com/aquasecurity/tfsec/releases/tag/v1.0.0
