### ISSUE TITLE
question: How can I filter only CRITICAL and HIGH issues?

### ISSUE THREAD

**Issue by okanmenevseoglu** [aquasecurity/tfsec#1575]
I went through the --help flag and also the documentation but couldn't find a flag for a feature to filter (or non-filter) only specific issues (Not with a ID but with a label such as CRITICAL, HIGH etc.). Can someone help me if this is possible with a flag or is it not a feature (yet)?

**Comment by liamg** [comment]
Hi @okanmenevseoglu I'll add this feature for you shortly.

**Comment by okanmenevseoglu** [comment]
Thanks! Looking forward :)

**Comment by liamg** [comment]
@okanmenevseoglu You can now use `tfsec --minimum-severity HIGH` in the latest release.

**Comment by okanmenevseoglu** [comment]
Thank you! Nice work.
