### ISSUE TITLE
bug: False positives on several vault's provider resources

### ISSUE THREAD

**Issue by Wiston999** [aquasecurity/tfsec#1586]
**Describe the bug**

Rule ID `general-secrets-no-plaintext-exposure` is incorrectly triggered on several [Vault's provider](https://registry.terraform.io/providers/hashicorp/vault/latest/docs) resources.

List of resources that have triggered false positives (may be more than this):
- `vault_pki_secret_backend_root_cert`
  - `private_key_format` parameter
- `vault_token_auth_backend_role`
  - `token_period` parameter
  - `token_explicit_max_ttl` parameter
  - `token_max_ttl` parameter

**Expected behavior**

Those parameters don't actually store any sensitive information and so they shouldn't trigger any issue.

**Screenshots/Output**

**System Info**

 - tfsec version: 1.8.0
 - terraform version: 1.1.7
 - OS: Debian buster

**Example Code**

```
resource "vault_token_auth_backend_role" "worker_creator" {
  role_name              = "test-role-name"
  allowed_policies       = ["default"]
  orphan                 = true
  token_period           = "2592000"  # Offending parameter
  renewable              = true
  token_explicit_max_ttl = "0"        # Offending parameter
  token_max_ttl          = "2592000"  # Offending parameter
}

resource "vault_pki_secret_backend_root_cert" "apiserver_ca" {
  backend = vault_mount.apiserver_pki.path

  type                 = "internal"
  common_name          = "test Apiserver CA"
  ttl                  = 630720000
  format               = "pem"
  private_key_format   = "der" # Offending parameter
  key_type             = "rsa"
  key_bits             = 4096
  exclude_cn_from_sans = true
  ou                   = "some-team"
  organization         = "some-company"
}
```

**Additional context**

**Comment by liamg** [comment]
This is resolved in `v1.9.1` as we have removed "generic" checks like this one due to the high numbers of false positives.
