### ISSUE TITLE
bug: tfsec_checksums.txt not provided with 0.63.1 

### ISSUE THREAD

**Issue by vchokshi** [aquasecurity/tfsec#1598]
**Describe the bug**
tfsec_checksums.txt not provided in the release dir for 0.63.1.

We rely on this file for obvious reasons.

**To Reproduce**

[0.63.1] (https://github.com/aquasecurity/tfsec/releases/tag/v0.63.1)

Compared with 

[0.58.4] (https://github.com/aquasecurity/tfsec/releases/tag/v0.58.4)

(Compare with 

**Expected behavior**
The file should exist as checksums.txt to maintain backwards compatibility.

**Comment by owenrumney** [comment]
that was a bad release - we got a lot of missing assets - GitHub Action outage IIRC
