### ISSUE TITLE
bug: `--exclude-downloaded-modules` not working, reads .terraform files too.

### ISSUE THREAD

**Issue by thegrumpydude** [aquasecurity/tfsec#1600]
**Describe the bug**
The flag in the command line `--exclude-downloaded-modules` seems to have stopped working, the flag lets tfsec ignore any security issues in downloaded modules.

**To Reproduce**
1. Go to the location where tfsec is invoked
2. Invoke tfsec with `--exclude-downloaded-modules` 

**Expected behavior**
tfsec should ignore all files under `.terraform` folder

**Observed behavior**
tfsec fails for the issues in `.terraform` folder

**Screenshots/Output**
```bash
Result #13 LOW Log group is not encrypted.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 .terraform/modules/eks.k8s/main.tf Line 6
```

**System Info**

 - tfsec version: `v1.9.1`
 - terraform version: `v1.1.7`
 - OS: `macOS 12.3`

**Example Code**
Can be tested with AWS EKS Module

**Comment by chtakahashi** [comment]
I am newly noticing in v1.7.0 (upgrading from 1.15.4) that despite using `--exclude-downloaded-modules`, tfsec is scanning a .terraform directory for me again.

**Comment by ragchuck** [comment]
@liamg still not working for me #1677 :(

**Comment by liamg** [comment]
Going to track this here: https://github.com/aquasecurity/tfsec/issues/1677
