### ISSUE TITLE
feat: Custom checks should use a provider schema for context

### ISSUE THREAD

**Issue by jrobison-sb** [aquasecurity/tfsec#1625]
**Is your feature request related to a problem? Please describe.**

Custom checks should enforce the user's desired policy, but only if that policy is possible in the context of the provider schema.

As a specific example, a custom check should be able to enforce that all `aws_*` resources should have a given tag, but only if it is possible to tag the resource which is being checked. The `aws_instance` resource, for example, supports tags, so it should fail a custom check if the desired tag isn't present. But the `aws_route` resource does not support tagging, so it should pass the same check, because enforcing the policy in the custom check would be impossible for that resource type.

**Describe the solution you'd like**

Custom checks should have knowledge of the provider schema which is being checked and should only enforce a given attribute if that attribute is actually possible for the resource being checked.

**Additional context**

The source of truth for provider schema can be found via `terraform providers schema -json`, or whatever the golang equivalent would be.

**Comment by jrobison-sb** [comment]
One edge case I notice which would come up if this were implemented is that schemas are sometimes inconsistent. For example, almost every AWS resource uses a tagging schema which looks like this:
```
tags = {
  Name = "foo"
  CostCenter = "bar"
}
```

The inconsistency is that `aws_autoscaling_group` has a `tags` attribute in its schema as all the others do, but `aws_autoscaling_group` implements it differently:
```
resource "aws_autoscaling_group" "a" {
  tags = [
    {
      key                 = "Name"
      value               = "foo"
      propagate_at_launch = true
    },
    {
      key                 = "CostCenter"
      value               = "bar"
      propagate_at_launch = true
    }
  ]
}
```

If a user enforced a tagging policy in a custom check on `aws_*` resources without verbosely specifying individual `resourceLabels`, they'd bump into this edge case. It might be worth implementing some kind of `requiredLabels` negation, like `requiredLabels: ! aws_autoscaling_group`, or a new `excludeLabels` list.

**Comment by jrobison-sb** [comment]
.

**Comment by owenrumney** [comment]
I can see the value in this, but it isn't practical to implement.

We download provider and modules for the purposes of scanning but not using the conventional `terraform init`; that would presume to know the version of terraform in use and could come with its own headaches.

To use `terraform providers schema --json` we need to have the `.terraform` folder; I've looked at how Hashi do it internally and the overhead outweighs the benefits.

One option would be to enrich the existing `hasTags` `MatchSpec` to have a list of resources that are known to support Tags and keep that maintained. I'll take a look at the practicality of that

**Comment by jrobison-sb** [comment]
.

**Comment by jrobison-sb** [comment]
.
