### ISSUE TITLE
Custom check.json file not loading 

### ISSUE THREAD

**Issue by yatmengho** [aquasecurity/tfsec#1629]
**Describe the bug**
I created a custom_check.json to test custom checks for tfsec. However tfsec did not load the custom_check.json file.
The main.tf and custom_check.json are in the same directory as of C:\Users\P1333599\Desktop\scan\testing

**To Reproduce**
1. cd to C:\Users\P1333599\Desktop\scan\testing in VS Code
2. type the command "tfsec --custom-check-dir custom_check.json"
3. the output did not mention the loading of the custom check file even though i set it as it will fail the custom check

**Expected behavior**
The output should show the main.tf fail the custom check which is populated inside the custom_check.json

**Screenshots/Output**
$ tfsec --custom-check-dir custom_check.json

Result #1 HIGH Instance does not require IMDS access to require a token
────────────────────────────────────────────────────────────────────────────────
 main.tf Lines 1-7
───────┬────────────────────────────────────────────────────────────────────────
    1  │ resource "aws_instance" "testing" {
    2  │        ami           = "ami-0d527b8c289b4af7f"
    3  │        instance_type = "t3.micro"
    4  │        tags = {
    5  │            "ClusterServer" = "test"
    6  │               }
    7  │ }
───────┴────────────────────────────────────────────────────────────────────────
          ID aws-ec2-enforce-http-token-imds
      Impact Instance metadata service can be interacted with freely
  Resolution Enable HTTP token requirement for IMDS

  More Information
  - https://aquasecurity.github.io/tfsec/v1.14.0/checks/aws/ec2/enforce-http-token-imds/
  - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#metadata-options
────────────────────────────────────────────────────────────────────────────────

Result #2 HIGH Root block device is not encrypted.
────────────────────────────────────────────────────────────────────────────────
 main.tf Lines 1-7
───────┬────────────────────────────────────────────────────────────────────────
    1  │ resource "aws_instance" "testing" {
    2  │        ami           = "ami-0d527b8c289b4af7f"
    3  │        instance_type = "t3.micro"
    4  │        tags = {
    5  │            "ClusterServer" = "test"
    6  │               }
    7  │ }
───────┴────────────────────────────────────────────────────────────────────────
          ID aws-ec2-enable-at-rest-encryption
      Impact The block device could be compromised and read from
  Resolution Turn on encryption for all block devices

  More Information
  - https://aquasecurity.github.io/tfsec/v1.14.0/checks/aws/ec2/enable-at-rest-encryption/
  - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#ebs-ephemeral-and-root-block-devices
────────────────────────────────────────────────────────────────────────────────

  timings
  ──────────────────────────────────────────
  disk i/o             1.9564ms
  parsing              0s
  adaptation           0s
  checks               13.9643ms
  total                15.9207ms

  counts
  ──────────────────────────────────────────
  blocks                1
  modules            1
  files                   1

  results
  ──────────────────────────────────────────
  passed               1
  ignored              0
  critical                0
  high                   2
  medium             0
  low                     0

  1 passed, 2 potential problem(s) detected.

**System Info**
 - tfsec version: v1.14.0
 - terraform version: v1.0.1
 - OS: Windows 10

**Example Code**
main.tf

resource "aws_instance" "testing" {
	ami           = "ami-0d527b8c289b4af7f"
	instance_type = "t3.micro"
	tags = {
	    "ClusterServer" = "test"
	       }
}

custom_check.json

{
  "checks": [
    {
      "code": "CUS001",
      "description": "Custom check to ensure the CostCentre tag is applied to EC2 instances",
      "impact": "By not having CostCentre we can't keep track of billing",
      "resolution": "Add the CostCentre tag",
      "requiredTypes": [
        "resource"
      ],
      "requiredLabels": [
        "aws_instance"
      ],
      "severity": "ERROR",
      "matchSpec": {
        "name": "tags",
        "action": "contains",
        "value": "CostCentre"
      },
      "errorMessage": "The required CostCentre tag was missing",
      "relatedLinks": [
        "http://internal.acmecorp.com/standards/aws/tagging.html"
      ]
    }
  ]   
}

**Comment by owenrumney** [comment]
Hey @yatmengho looks like your passing a file to an argument that accepts a dir

The file name needs to be in the passed dir and end with _tfchecks.json

if you put it in .tfsec of the project root it will be picked up automatically

https://aquasecurity.github.io/tfsec/v1.15.0/guides/configuration/custom-checks/
