### ISSUE TITLE
bug: Chocolatey not on the latest verison

### ISSUE THREAD

**Issue by Official-James** [aquasecurity/tfsec#1633]
**Describe the bug**
If you use Chocolatey as the option to install tfsec, you are only able to download v1.8.0 which isn't the latest version. You have to use alternative options.

**To Reproduce**
1. Install Chocolatey if not already installed
2. Go to https://community.chocolatey.org/packages/tfsec
3. Run the install command
4. Install completes but on v1.8.0

**Expected behavior**
Expected latest version but does say in the software page on Chocolatey that 1.8.0 will be installed. Just expect it to be latest if its listed as an option to install from.

**Comment by owenrumney** [comment]
I'll update today - hopefully their approval process will have it available at some point today

Seems Scoop has a lot better automation if you're interested in looking at that

**Comment by owenrumney** [comment]
https://community.chocolatey.org/packages/tfsec/1.15.0
