### ISSUE TITLE
feat: Add parameter to control exit code based on severity

### ISSUE THREAD

**Issue by AErmie** [aquasecurity/tfsec#1648]
**Is your feature request related to a problem? Please describe.**
It would be helpful to be able to run TFSec and control the exit code based on severity, while still outputting all results.

**Describe the solution you'd like**
Something like combining the `--minimum-severity` parameter, with a `--hard-fail-on` option, so that all vulnerabilities are displayed, but TFSec will `exit-1` if there are any CRITICAL vulnerabilities specifically.

**Describe alternatives you've considered**
The [BridgeCrew Checkov](https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html) tool provides this type of option. Otherwise, we could use the `--minimum-severity` parameter, but would then miss out on seeing any other vulnerabilities, which could present a false-positive assumption.

**Additional context**
I am using the docker container method of executing TFsec.

**Comment by liamg** [comment]
Hi @AErmie, I think you can achieve this by combining `--minimum-severity` with `--include-ignored`.

**Comment by AErmie** [comment]
Hey @liamg, thanks for that suggestion. But, I'm not sure I follow how that combination would achieve the desired outcome.

The `--minimum-severity` command controls the "minimum severity of results to report." The desire is to see all the results, so setting `--minimum-severity` to CRITICAL is the same as not including the `--minimum-severity` command at all.

The `--include-ignored` command controls scanning of resources even if they have "ignore comments." 

The desired outcome is to show all results, but only `exit code 1` based on severity... meaning, if we set `--minimum-severity` to CRITICAL, and there is a HIGH vulnerability detected (and now CRITICAL vulnerabilities), we can't use something like `--soft-fail` because it suppresses the error code entirely.

**Comment by liamg** [comment]
Hi @AErmie I believe it would achieve exactly that desired outcome.

When you use `--minimum-severity`, it effectively _ignores_ all results with a severity lower than the one you specified.

When you use `--include-ignored`, it will show the ignored results in the output, but not affect the exist status.

With your example, with `include-ignored`, `--minimum-severity CRITICAL` and one `HIGH` result, tfsec would exit with status 0 but still output the `HIGH` result information.

**Comment by AErmie** [comment]
Thanks for the explanation @liamg, let me walk through this scenario in my pipeline. I'll report back the results.

**Comment by liamg** [comment]
Cool, closing this for now, please let me know if there are any problems with it.

**Comment by AErmie** [comment]
Hey @liamg, even though this approach works, there's one enhancement I'd like to see...

When using the `--include-ignored` command, and the command-line outputting the results, it would be more useful if it still showed the severity of the ignored vulnerability. This way, if a customer wants to address the vulnerabilities in a phased approach (ie. starting with CRITICAL), they can still see how many HIGH, etc. are present.

This should also apply to the results summary output at the end...

```CMD
results
  ──────────────────────────────────────────
  passed               35
  ignored              35
  critical             1
  high                 6
  medium               0
  low                  0
```

Let me know if you think that's reasonable, and if you'd like me to open a new issue/feature request for that.
