### ISSUE TITLE
docs(README.md): GitHub Security Alerts sentence ends prematurely

### ISSUE THREAD

**Issue by msamendinger** [aquasecurity/tfsec#1650]
Hi,

reading through the [GitHub Security Alerts](https://github.com/aquasecurity/tfsec#github-security-alerts) in the `README.md` file it seems to me that the sentence ["For more information about adding security alerts, check"](https://github.com/aquasecurity/tfsec/blob/3df262b183e7dffdcde0614ecca10a6d40fae6b5/README.md?plain=1#L209) ends prematurely.

Not sure what the original idea was where to link to but I could imagine to the [run-tfsec-with-sarif-upload action](https://github.com/marketplace/actions/run-tfsec-with-sarif-upload)
or the GitHub documentation on [Uploading a SARIF file to GitHub](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github).

**Comment by owenrumney** [comment]
thanks for pointing this out - will sort that out

**Comment by reedloden** [comment]
.
