### ISSUE TITLE
bug: Missing assets metadata when checking latest available release

### ISSUE THREAD

**Issue by bajalnyt** [aquasecurity/tfsec#1654]
**Describe the bug**

In our CI, we use the following github endpoint to locate the latest tfsec binary. However, as of today, the `assets` array is empty when I go to https://api.github.com/repos/aquasecurity/tfsec/releases/latest. 

**To Reproduce**
Run following curl
```
curl -sLO $(curl -s https://api.github.com/repos/aquasecurity/tfsec/releases/latest | jq '.assets[] | select( .name | contains("tfsec-linux-amd64"))| .browser_download_url' | tr -d '"')
```

**Expected behavior**

The tfsec binary should get downloaded
**Screenshots/Output**

**System Info**

 - tfsec version: NA
 - terraform version: NA
 - OS: Linux, CentOS

**Example Code**

**Additional context**

**Comment by mclavel** [comment]
The release process failed https://github.com/aquasecurity/tfsec/actions/runs/2096568560

**Comment by bajalnyt** [comment]
@liamg would you be able to restart it please 🙏

**Comment by liamg** [comment]
@bajalnyt Im afraid it's an issue with the windows build of a dependency - we need to test this in our builds before merging 😬

Working on a fix now, shouldn't be long.

**Comment by liamg** [comment]
I'll revert to the previous version in the meantime to unblock you.

**Comment by bajalnyt** [comment]
Ah, I see. Appreciate it - Thanks @liamg !

**Comment by liamg** [comment]
`v1.16.1` is now back to normal :)
