### ISSUE TITLE
feat: tfsec report on separate tab named `tfsec` in Azure DevOps

### ISSUE THREAD

**Issue by vanmash** [aquasecurity/tfsec#1657]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I'd love to see tfsec report on a separate tab in Azure DevOps.

**Describe alternatives you've considered**

Now I can put `tfsec` report on a test tab, but it is confusing. Please note Snyk (via its Snyk scan extension) puts their results on a tab named Snyk.

**Additional context**

**Comment by owenrumney** [comment]
We're working on Azure DevOps extension at the moment

**Comment by liamg** [comment]
This is in progress :)

**Comment by liamg** [comment]
Here you go, sorry about the delay:

https://marketplace.visualstudio.com/items?itemName=AquaSecurityOfficial.tfsec-official

Please raise any issues/feature requests on the [task repository](https://github.com/aquasecurity/tfsec-azure-pipelines-task).
