### ISSUE TITLE
question: Can the filename in JSON report be relative to the project?

### ISSUE THREAD

**Issue by okanmenevseoglu** [aquasecurity/tfsec#1659]
Hello,

I have a business requirement as the following;
- We would like to commit the TFSec results in JSON format in our code repository.
- Whenever another developer runs TFSec on their local, this file will be updated to see the new issues if exists easily.

At the moment, this works fine but with one issue. The **location.filename** parameter in the JSON file contains the full path of the user include also **/home/$username/$project-location/...**

Right now we are excluding filename completely with piping with`jq 'del(.. | .filename?)'` but it makes it harder to locate which file contains the issues.

So, my question is that is there a way to run TFSec with JSON natively to contain relative path to the application without computer specific project path or would it be possible to add it as a feature?

**Example:**
**Instead of:** `"filename": "/Users/omenevseoglu/IdeaProjects/contosso-project/main.tf"`
**Relative :** `"filename": "~/contosso-project/main.tf"` (or maybe based on where you run tfsec even `~/main.tf` is fine)

**PS:** I really like this project. So, keep up the good work!

Kr

**Comment by okanmenevseoglu** [comment]
I have implemented an improvement with jq to filter out at least the file-name. Not perfect but works: 
`tfsec . --format json | jq '.results[].location.filename |= sub("/^(.*)/|(.*)\/"; "")' > tfsec_report.json`

**Comment by liamg** [comment]
Hi @okanmenevseoglu - yes! This should actually be available later today/tomorrow!
