### ISSUE TITLE
how to exclude path with a regex pattern?

### ISSUE THREAD

**Issue by ericmenard** [aquasecurity/tfsec#1679]
I would like to exclude scan for all .terragrunt-cache subfolders and their subfolders from the following file structure

> > ./
├─ test
> ├── module1
> > ├── .terragrunt-cache/...
> ├── module2
> > ├── .terragrunt-cache/...
> ├── module3
> > ├── .terragrunt-cache/...
├─ prod
> ├── module1
> > ├── .terragrunt-cache/...
> ├── module2
> > ├── .terragrunt-cache/...
> ├── module3
> > ├── .terragrunt-cache/...

I'm looking to exclude **/.terragrunt-cache/*

Is it possible? 
Thanks

**Comment by sergeyshevch** [comment]
Same question. Terragrunt is very useful for us. And it will be good to exclude such folders
