### ISSUE TITLE
bug: Use of incorrect flag --tf-vars 

### ISSUE THREAD

**Issue by diogomaul** [aquasecurity/tfsec#1681]
**Describe the bug**
This is related to fix #651.

The implementation of the fix considered --tf-vars as the flag to be used to pass a terraform.tfvars file, but the correct flag is -var-file.  Terraform does not recognize --tf-vars of -tf-vars.

On the other side, terraform plan/apply works fine when you use the flag -var-file. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create any terraform code
2. Create a terraform.tfvars file
3. Run a plan command for your TF code passing the variables terraform.tfvars file:
    _terraform plan --tf-vars terraform.tfvars_
4. See error:
![TF-error](https://user-images.githubusercontent.com/37045051/163402022-12223445-53d5-4310-b8d4-a373a5ea918b.png)

**Expected behavior**
The expected behaviour would be a plan result, that can only be achieved following the correct sintax:
    _terraform plan -var-file terraform.tfvars_

![-var-file](https://user-images.githubusercontent.com/37045051/163404678-8c3372cb-7b19-4635-b3e6-95ecf6805fbf.png)

**System Info**

 - tfsec version: v1.15.0
 - terraform version: v1.1.6
 - OS: Tested both locally on Windows 11 and using ubuntu-latest in Azure DevOps

Please let me know if you need any additional information.

Thank you;

Diogo Maul

**Comment by owenrumney** [comment]
Hey @diogomaul  - thanks for pointing this out. 

I'm reluctant to remove the flag for fear of breaking existing flows in people's CI. I've added `--var-file` as a duplication of the flag to offer an alternative more consistent with Terraform

**Comment by diogomaul** [comment]
Hi @owenrumney, this is awesome! And yes, you are right regarding breaking this for people that already use the other (old?) flag. 

Thank you so much for the quick turnaround!

**Comment by owenrumney** [comment]
Hey @diogomaul  - this is finally available in v1.19.0 https://github.com/aquasecurity/tfsec/releases/tag/v1.19.0
