### ISSUE TITLE
bug: tfsec pulling template code from Google module

### ISSUE THREAD

**Issue by wyardley** [aquasecurity/tfsec#1684]
**Describe the bug**
When following code that includes a submodule of `terraform-google-modules/kubernetes-engine`, it seems that tfsec is trying to parse a `tf.templ` (template) file as hcl.

```
% ls  .tfsec/cache/f06e3965a3ac8a1fcf62439d58e4c9ff/autogen/main
README.md              cluster.tf.tmpl        firewall.tf.tmpl       masq.tf.tmpl           outputs.tf.tmpl        scripts/               variables_defaults.tf
auth.tf.tmpl           dns.tf.tmpl            main.tf.tmpl           networks.tf            sa.tf.tmpl             variables.tf.tmpl      versions.tf.tmpl
```

**To Reproduce**
1. Create a simple invocation of a submodule of terraform-google-modules/kubernetes-engine
1. Run `tfsec --force-all-dirs` on the directory

**Expected behavior**
`tfsec` would parse valid HCL.

**Screenshots/Output**
```
Error: scan failed: [...]/terraform/.tfsec/cache/f06e3965a3ac8a1fcf62439d58e4c9ff/autogen/main/networks.tf:17,1-2: Argument or block definition required; An argument or block definition is required here.
```

**System Info**

 - tfsec version: `v1.18.0`
 - terraform version: `v1.1.8`
 - OS: `darwin_amd64`

**Example Code**
```hcl
module "gke" {
  source                       = "terraform-google-modules/kubernetes-engine/google//modules/beta-private-cluster"
  [...]
 }
```

**Additional context**
lmk if I can help debug further. I came across this by accident when trying to identify another issue with tfsec not finding all my directories.

**Comment by wyardley** [comment]
Also, I'm wondering if this is an issue with `--force-all-dirs` recursively scanning the cache dir itself, in which case I guess the fix would be having tfsec not scan its own cache dir, which would probably be a good idea (I imagine skipping all `.terraform` directories would also be a good idea if it doesn't already).

I would skip using `--force-all-dirs`, but _not_ using it is giving me a different issue with not getting a lot of more deeply nested directories in our directory structure (similar to #567)

**Comment by wyardley** [comment]
commenting, since I can't edit labels

**Comment by owenrumney** [comment]
Hey @wyardley - I'm pretty confident that we're not trying to parse the tmpl files, we're only interested in `.tf` and `.tf.json`

Would you be able to put a small example together showing the problem so we can reproduce?

**Comment by owenrumney** [comment]
I was going off the screenshot in the initial description with the file type was `tf.tmpl` - we are only interested in files with the suffix `.tf` and `.tf.json` see - https://github.com/aquasecurity/defsec/blob/master/pkg/scanners/terraform/parser/parser.go#L148-L149

I see now I've looked at the provider directly that the autogen folder has templating in the .tf file - I was a bit slow there.

I don't think its practicable to second guess if something is a template or not, we need to expect the hcl is atleast syntactically correct.

I think the best solution is, as you say, globs for excluding paths `**/autogen/*` or similar

**Comment by wyardley** [comment]
Yes, and in fact, in this case, the other files in the `autogen` directory all have the `.tmpl` extension, so maybe an oversight? I opened
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1285 just in case that will work
