### ISSUE TITLE
bug: only text format output is valid

### ISSUE THREAD

**Issue by danjo133** [aquasecurity/tfsec#1691]
**Describe the bug**
Running with different formats give different/erronous output:

**To Reproduce**
`$ docker run --rm -v "$(pwd)/subfolder:/src" aquasec/tfsec:latest ./src --tfvars-file /src/dev.tfvars -e azure-storage-queue-services-logging-enabled --format text`

Has the (correct) output
```
results
──────────────────────────────────────────
passed               7
ignored              1
critical             0
high                 0
medium               0
low                  0
```

`$ docker run --rm -v "$(pwd)/subfolder:/src" aquasec/tfsec:latest ./src --tfvars-file /src/dev.tfvars -e azure-storage-queue-services-logging-enabled --format junit`

Has this output, which doesn't take the exclude/ignore into account and show the ignored as failure

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="tfsec" failures="1" tests="8"></testsuite>%

```
`$ docker run --rm -v "$(pwd)/subfolder:/src" aquasec/tfsec:latest ./src --tfvars-file /src/dev.tfvars -e azure-storage-queue-services-logging-enabled --format csv`

Has this output, which only contains the headers and nothing else:

`file,start_line,end_line,rule_id,severity,description,link,passed`

**Expected behavior**
Selecting a different format should not effect the contents of the output

**System Info**
 - tfsec version: aquasec/tfsec:latest      6b60363f07ee 
 - terraform version: 1.1.7, azurerm 2.99.0
 - OS: Linux

**Comment by JoeButler99** [comment]
https://github.com/aquasecurity/defsec/issues/587 - have dug in and raised separate issue in the upstream repo which handles the json output - my comments on this can be dealt with there.
