### ISSUE TITLE
feat: Add a new style for old encoding

### ISSUE THREAD

**Issue by littlejo** [aquasecurity/tfsec#1692]
Hello,

tfsec has a good output when i try on my laptop. But when i try to launch on Jenkins ci, my output is not the same: long pipe (│) is transformed into '[2m' character. I don't find a solution to change that in Jenkins, i don't have access to administrate Jenkins.

**Describe the solution you'd like**

Could you had a new style to replace long pipe into simple pipe?

**Comment by liamg** [comment]
I think this is due to colours - are you able to try the `--no-colour` parameter?

**Comment by owenrumney** [comment]
I think `--no-color` or `--no-colour` should resolve this in a CI run, please feel free to reopen if this doesn't solve the issue
