### ISSUE TITLE
bug: invalid submodule in tfsec repo

### ISSUE THREAD

**Issue by smelchior** [aquasecurity/tfsec#1730]
**Describe the bug**
https://github.com/aquasecurity/tfsec/commit/1c76aa72ffec6a8640bbd36f2aa16f2fa81bd404
added
.tfsec/cache/dbfa226ee274946ad2f78c29ef3df2b7
which is an invalid submodule reference which can cause issues when cloning this repo

**To Reproduce**
git clone git@github.com:aquasecurity/tfsec.git
cd tfsec/ && git submodule init

->
```
fatal: No url found for submodule path '.tfsec/cache/dbfa226ee274946ad2f78c29ef3df2b7' in .gitmodules
```
**Expected behavior**
successful clone

**Comment by rugilmore** [comment]
I am experiencing the same thing using version v1.21.1.
