### ISSUE TITLE
feat: Support "via" in json output format

### ISSUE THREAD

**Issue by francilioaraujo** [aquasecurity/tfsec#1732]
**Is your feature request related to a problem? Please describe.**
Lovely and text outputs have a "via" location. This helps when using modules, because the location points to the module's internal code. As far I could see, all other formats only outputs the "internal" location. Adding the "via" to other formats (specifically json) could helps in tooling and automations.

**Describe the solution you'd like**
A new field in the json output with the content similar to "via" from the lovely output.

**Describe alternatives you've considered**
None.

**Additional context**
Lovely output example:
```
  terraform-aws-modules/s3-bucket/aws/<REDACTED>/.terraform/modules/cf_log_bucket/main.tf:5-263
   via frontend.tf:92-122 (module.cf_log_bucket)
```
Json output example:
```
{
	"rule_id": "AVD-AWS-0088",
	"long_id": "aws-s3-enable-bucket-encryption",
	"rule_description": "Unencrypted S3 bucket.",
	"rule_provider": "aws",
	"rule_service": "s3",
	"impact": "The bucket objects could be read if compromised",
	"resolution": "Configure bucket encryption",
	"links": [
		"https://aquasecurity.github.io/tfsec/v1.21.0/checks/aws/s3/enable-bucket-encryption/",
		"https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#enable-default-server-side-encryption"
	],
	"description": "Bucket does not have encryption enabled",
	"severity": "HIGH",
	"warning": false,
	"status": 0,
	"resource": "module.cf_log_bucket",
	"location": {
		"filename": "terraform-aws-modules/s3-bucket/aws/<REDACTED>/.terraform/modules/cf_log_bucket/main.tf",
		"start_line": 5,
		"end_line": 263
	}
}
```

**Comment by mcdafydd** [comment]
This would be a nice way to provide better feedback in the IDE plugins when changing a module's input would resolve a rule failure.

**Comment by shinenelson** [comment]
I think this issue belongs in the [aquasecurity/defsec](https://github.com/aquasecurity/defsec) repository which defines all the formatters that this repository uses.

**Comment by shinenelson** [comment]
@simar7, this issue can also be closed since https://github.com/aquasecurity/defsec/pull/1383 has implemented this feature request.

However, I am not sure whether there would be a new release for tfsec at this time since [tfsec is joining the Trivy family](https://github.com/aquasecurity/tfsec/discussions/1994).

**Comment by simar7** [comment]
This is now supported in Trivy as our efforts have moved to it. The work is being tracked here https://github.com/aquasecurity/trivy/issues/4581
