### ISSUE TITLE
feat: Read config and custom rules from git repository folder

### ISSUE THREAD

**Issue by armanbaghajyan** [aquasecurity/tfsec#1739]
**Is your feature request related to a problem? Please describe.**
We want to keep all custom rules and conf in one place for easy management. We have terraform configurations in different repositories every time we need to pull configs from shared repo to scan with custom rules and configs

**Describe the solution you'd like**
Add possibility to set git url as config file and config folder location.

**Comment by owenrumney** [comment]
Hey @armanbaghajyan  - this has been added in #1774 and #1776

the `custom-check-url` and `config-file-url` arguments expect the path to a `json` or `yaml` file.

Hopefully this will be released today
