### ISSUE TITLE
bug:  Requesting module versions from registry, response 404

### ISSUE THREAD

**Issue by armanbaghajyan** [aquasecurity/tfsec#1742]
**Describe the bug**
For some reason, I am getting these error messages in tfsec  verbose outputs
```
[module:retrieve] Requesting module versions from registry using 'https://app.terraform.io/v1/modules/my_company/module_name/aws/versions'...
[debug:eval][root] Failed to load module 'unexpected status code for versions endpoint: 404'. Maybe try 'terraform init'?
[debug:eval][root] locating non-initialised module 'app.terraform.io/my_company/module_name/aws'...
```

I am running terraform init before running tfsec

Also, I am getting a following error message 
```[debug:parse][root] Error loading module metadata: open //builds/path/to/terraform_dir/.ci/terraform/.terraform/modules/modules.json: no such file or directory.```

But my .terraform folder is located under 
`//builds/path/to/terraform_dir/.ci/terraform/application_config/.terraform/modules/modules.json:`

I am using a soft link `main.tf` file is located in the `terraform` folder and symbolic link is under the `application_config` folder

**To Reproduce**
Create a directory structure like this
```
| main.tf
| app_config/
     |_main.tf (linked to ../main.tf
```
I am running `terraform init` in `app_config`  directory

**Comment by owenrumney** [comment]
Am I reading this correctly that it is on a share? I need to check the code, but I think the registry resolver is the last one to run and its possibly looking at that as a scheme when it shouldn't be

**Comment by owenrumney** [comment]
closing due to no further details - please feel free to reopen with more info
