### ISSUE TITLE
question: Was it intended for --workspace argument to pass terraform.workspace to tfsec

### ISSUE THREAD

**Issue by haodeon** [aquasecurity/tfsec#1756]
When reading the docs it seems to suggest that `--workspace` is only for passing ignore limits.

However I was pleasantly surprised to find in my testing it can be used to specify which workspace tfsec should evaluate `terraform.workspace` to. This means tfsec can use the `--workspace` parameter to perform map lookups, evaluate conditional expressions and use as a value in functions like `contains` .

If I omit --workspace parameter from tfsec scans I find tfsec struggles to parse my configuration properly and gives misleading results. It completely fails to expand for_each loops that use maps that have `terraform.workspace` as the key.

It would be great if the docs could clarify `--workspace` has further use than ignore limits. Neither the original feature request nor the PR which implements `--workspace` mention this.

**Comment by owenrumney** [comment]
Hey @haodeon - I think you've stumbled on a side effect here, the intention of `--workspace` is entirely about ignores. I'm not sure why you have problems when not running without specifying a workspace, by default it uses `--workspace default` if nothing is specified, that should really be there.

I'll take a look at the side effects and try to document at some point. If you feel you have enough insight, PR's are always welcome :-)
