### ISSUE TITLE
question: Specific resource to be found by custom check in tfsec

### ISSUE THREAD

**Issue by anurodh-ti** [aquasecurity/tfsec#1803]
Can we write a custom rule to check if the specific resource(we know the name and specifications) is violating a rule?
For example, In custom check file we usually define **required types**(let say resources in our case) and **required labels** (let say aws_instance), so this custom rule would check for all resources which has label aws instance and but if we want to be more specific, we even know the name of that specific resource we will check this rule for.
Can we add that as well and only get the results for that specific resource and not all resources of this type?

**Comment by simar7** [comment]
That's right at the moment it is not supported at that granularity. The most we can do is by resource type as you know.
