### ISSUE TITLE
feat: Add support to ignore rule with wildcard.

### ISSUE THREAD

**Issue by armanbaghajyan** [aquasecurity/tfsec#1804]
**Is your feature request related to a problem? Please describe.**
I want to add ignore rules depending on the workspace name, For example, if the workspace name contains a test then ignore rules for resources

**Describe the solution you'd like**
Right now it is possible to ignore the workspace with this
`#tfsec:ignore:AWS018:ws:development-test-app-1`

**Describe alternatives you've considered**
I want to be able to ignore the workspace with something like this
`#tfsec:ignore:AWS018:ws:*-test-*`

**Comment by simar7** [comment]
Thanks for the idea we're tracking this in Trivy https://github.com/aquasecurity/trivy/issues/5120
