### ISSUE TITLE
question: How can I try tfsec application on windows 10?

### ISSUE THREAD

**Issue by cemelma** [aquasecurity/tfsec#1805]
Hi everyone,

I want to use tfsec on intellij Ide. I installed the plugin intellij ide on the windows machine.
![image](https://user-images.githubusercontent.com/1357281/175331513-878e3eab-faf9-41d9-ada2-0b41a186f0b6.png)

what should i enter "specific tfsec path"
![image](https://user-images.githubusercontent.com/1357281/175332211-b00b6890-dfe1-4b04-a974-7809eb6677e9.png)
when i click the run tfsec, i am getting a error like this. 
![image](https://user-images.githubusercontent.com/1357281/175331839-744a9a73-0eb1-49e8-b2b9-f48942a34ecf.png)
![image](https://user-images.githubusercontent.com/1357281/175332286-38264d78-9901-427c-89c4-af85a91c2f18.png)

Thanks,

**Comment by owenrumney** [comment]
Hi @cemelma  - you need to also install tfsec for windows 

https://aquasecurity.github.io/tfsec/v1.26.0/guides/installation/

You have a number of options - Chocolatey, Scoop or downloading the latest release from releases
https://github.com/aquasecurity/tfsec/releases/tag/v1.26.0
