### ISSUE TITLE
question: docker run --rm -v "$(pwd):/src" aquasec/tfsec /src not scanning the current repository path!

### ISSUE THREAD

**Issue by vehbirestelica** [aquasecurity/tfsec#1814]
Hello all,
I wanted to use tfsec in Jenkins, following your documentation, first I pulled tfsec-ci docker image and then ran the command docker run --rm -v "$(pwd):/src" aquasec/tfsec /src as shown in the read.me file. But this command doesn't get the current path of the repository pulled from bitbucket. I've also tried this locally on my laptop and it worked without changing anything!
<img width="359" alt="image" src="https://user-images.githubusercontent.com/34625772/177156216-6250605f-cfff-4f3b-ae7d-86c318309b64.png">  
<img width="840" alt="image" src="https://user-images.githubusercontent.com/34625772/177156556-c1a029fc-7d5c-4ef4-a23b-c254c5785f89.png">

As you can see, the images above show different results, even though I used the same command...

Any suggestion?

**Comment by liamg** [comment]
You can ensure the docker container can "see" your code using:
```
docker run --rm --entrypoint ls -v `pwd`:/src aquasec/tfsec -la /src
```

**Comment by vehbirestelica** [comment]
Yes, I have already done that. It does find every terraform file that I have, but still wont scan them. 
The following command will print this: 
drwxr-xr-x    4 root     root            48 Jul  5 08:11 .
drwxr-xr-x    1 root     root            17 Jul  7 07:14 ..
drwxr-xr-x    2 root     root             6 Jul  5 08:11 <project.name>
drwxr-xr-x    3 root     root            69 Jul  5 12:59 terraform

**Comment by liamg** [comment]
This looks like a permissions issue. Your project + terraform directories only allow execute to the root user. To list files, the execute permission should be allowed to the non-root user that tfsec runs as in the container, i.e. you should have `drwxrwxr-x` on directories for tfsec to scan. Alternatively you could run the tfsec scan as root with the docker option `--user 0:0`.

**Comment by liamg** [comment]
Interesting - what output do you get if you append `--debug` to the command?

**Comment by vehbirestelica** [comment]
<img width="875" alt="image" src="https://user-images.githubusercontent.com/34625772/177740086-105da639-e07d-457f-a993-5c4dc450d981.png">

**Comment by liamg** [comment]
Sorry, I mean without the `--entrypoint ls` and `-la` parameters.

**Comment by vehbirestelica** [comment]
it prints: 
       docker: Error response from daemon: pull access denied for ls, repository does not exist or may require 'docker login'.
See 'docker run --help'.
- with user 0:0:
       user not found.

**Comment by liamg** [comment]
It looks like you still have `ls` in your command. 

Try:
```
docker run --rm -v `pwd`:/src aquasec/tfsec --debug /src
```

**Comment by vehbirestelica** [comment]
Yes, sorry!
+ docker run --rm -v /var/jenkins_home/workspace/<project_name>:/src aquasec/tfsec --debug /src
32:23.447718935 system.info                      APP       tfsec
32:23.447750178 system.info                      VERSION   v1.26.0
32:23.447754041 system.info                      OS        linux
32:23.447756957 system.info                      ARCH      amd64
32:23.447760165 system.info                      KERNEL    Linux version 5.4.172-90.336.amzn2.x86_64 (mockbuild@ip-10-0-54-229) (gcc version 7.3.1 20180712 (Red Hat 7.3.1-13) (GCC)) #1 SMP Wed Jan 19 23:08:01 UTC 2022
32:23.447764536 system.info                      TERM      
32:23.447767616 system.info                      SHELL     
32:23.447770622 system.info                      GOVERSION go1.18.3
32:23.447774135 system.info                      GOROOT    /opt/hostedtoolcache/go/1.18.3/x64
32:23.447777239 system.info                      CGO       false
32:23.447780862 system.info                      CPUCOUNT  2
32:23.447783887 system.info                      MAXPROCS  2
32:23.447786671 system.info                      WORKDIR   /
32:23.447790774 system.info                      UID       1000
32:23.447794548 system.info                      EUID      1000
32:23.447797462 system.info                      DOCKER    true
32:23.447800388 system.info                      CI        false
32:23.447803417 system.info                      HOSTNAME  47c311513037
32:23.447806607 system.info                      TEMP      /tmp
32:23.447809831 system.info                      PATHSEP   /
32:23.447812892 system.info                      CMD       tfsec --debug /src
32:23.447828404 cmd                              Command args=[]string{"/src"}
32:23.447844568 cmd                              Determined path dir=/src
32:23.447882290 cmd                              Determined path root=/
32:23.447885507 cmd                              Determined path rel=src
32:23.447930486 terraform.scanner                Scanning [&{/ /}] at 'src'...
32:23.448141592 terraform.scanner                no root modules found
32:23.448146546 cmd                              Exit code based on results: 0
[0m  [1mtimings[0m
  ──────────────────────────────────────────
[0m[0m  [2mdisk i/o            [0m 0s
[0m[0m  [2mparsing             [0m 0s
[0m[0m  [2madaptation          [0m 0s
[0m[0m  [2mchecks              [0m 0s
[0m[0m  [2mtotal               [0m 0s
[0m
[0m  [1mcounts[0m
  ──────────────────────────────────────────
[0m[0m  [2mmodules downloaded  [0m 0
[0m[0m  [2mmodules processed   [0m 0
[0m[0m  [2mblocks processed    [0m 0
[0m[0m  [2mfiles read          [0m 0
[0m
[0m  [1mresults[0m
  ──────────────────────────────────────────
[0m[0m  [2mpassed              [0m 0
[0m[0m  [2mignored             [0m 0
[0m[0m  [2mcritical            [0m 0
[0m[0m  [2mhigh                [0m 0
[0m[0m  [2mmedium              [0m 0
[0m[0m  [2mlow                 [0m 0
[0m
[0m
[32m[1mNo problems detected!

[0mFinished: SUCCESS

Still shows not problems!!

**Comment by vehbirestelica** [comment]
+ docker run --rm --entrypoint ls -v /var/jenkins_home/workspace/<project_name>:/src aquasec/tfsec -lR /src
/src:
total 0
drwxr-xr-x    2 root     root             6 Jul  5 08:11 <project_name>
drwxr-xr-x    3 root     root            69 Jul  5 12:59 terraform

/src/<project_name>:
total 0

/src/terraform:
total 0
-rwxr-xr-x    1 root     root             0 Jul  5 12:59 hostname
-rwxr-xr-x    1 root     root             0 Jul  5 12:59 hosts
drwxr-xr-x    4 root     root            35 Jul  4 14:41 modules
-rwxr-xr-x    1 root     root             0 Jul  5 12:59 resolv.conf

/src/terraform/modules:
total 0
drwxr-xr-x    2 root     root             6 Jul  4 12:30 acm
drwxr-xr-x    2 root     root             6 Jul  4 14:41 client-vpn

/src/terraform/modules/acm:
total 0

/src/terraform/modules/client-vpn:
total 0
Finished: SUCCESS

**Comment by vehbirestelica** [comment]
Same results as I see...
+ docker run --rm --user 0:0 --entrypoint ls -v /var/jenkins_home/workspace/<project_name>:/src aquasec/tfsec -lR /src
/src:
total 0
drwxr-xr-x    2 root     root             6 Jul  5 08:11 <project_name>
drwxr-xr-x    3 root     root            69 Jul  5 12:59 terraform

/src/<project_name>:
total 0

/src/terraform:
total 0
-rwxr-xr-x    1 root     root             0 Jul  5 12:59 hostname
-rwxr-xr-x    1 root     root             0 Jul  5 12:59 hosts
drwxr-xr-x    4 root     root            35 Jul  4 14:41 modules
-rwxr-xr-x    1 root     root             0 Jul  5 12:59 resolv.conf

/src/terraform/modules:
total 0
drwxr-xr-x    2 root     root             6 Jul  4 12:30 acm
drwxr-xr-x    2 root     root             6 Jul  4 14:41 client-vpn

/src/terraform/modules/acm:
total 0

/src/terraform/modules/client-vpn:
total 0
Finished: SUCCESS

**Comment by liamg** [comment]
Very strange, I think this is a problem with your local docker rather than tfsec then. I wonder if this applies: https://stackoverflow.com/questions/34504156/docker-volume-not-mounting-any-files
