### ISSUE TITLE
bug: --exclude not forking for custom rules with comma seperation

### ISSUE THREAD

**Issue by armanbaghajyan** [aquasecurity/tfsec#1826]
I have 2 custom rules which I want to exclude
with default rules ID s I can do like this
```tfsec -G -e aws-ec2-enable-at-rest-encryption,aws-ec2-enforce-http-token-imds```
But for custom rules, this is not working
```tfsec -G -e custom-custom-resource-param1,custom-custom-resource-param2```
```tfsec -G -e custom-custom-resource-param1 -e custom-custom-resource-param2```
tfsec was not able to ignore these rules but if I will only for one rule it is working.

**Comment by simar7** [comment]
Our efforts have moved to Trivy. Please file a discussion in the Trivy repo if you see fit.
