### ISSUE TITLE
feat: Ignore checks in tfvars file

### ISSUE THREAD

**Issue by chris3ware** [aquasecurity/tfsec#1835]
**Is your feature request related to a problem? Please describe.**

I am using the `github_repository` resource with `for_each` to manage resources as they are defined in a `tfvars` file. For some of these repositories I need to ignore certain checks, for example `github-repositories-private` and `github-repositories-enable_vulnerability_alerts`, but for others I do not. To ignore the check I have to place the `tfsec:ignore:<check>` in the main configuration file, as below, which will ignore for all the repositories in the list.

```hcl

main.tf

resource "github_repository" "this" {
  for_each    = { for repo in var.repositories : repo.name => repo }
  name        = each.value.name
  description = each.value.description
  #tfsec:ignore:github-repositories-private
  visibility = each.value.visibility
  #tfsec:ignore:github-repositories-enable_vulnerability_alerts
  vulnerability_alerts = try(each.value.vulnerability_alerts, false)
}

terraform.tfvars

repositories = [
  {
    name                      = "Public Repo",
    description              = "Alerts not applicable here because runtime not supported",
    visibility                   = "public",
    vulnerability_alerts = false
  },
  {
    name                      = "Private Repo",
    description              = "Alerts required here",
    visibility                   = "private",
    vulnerability_alerts = true
  },
```

**Describe the solution you'd like**

I'd like to be able to place the ignore comment in the tfvars file to enable more granular control over which resources checks are ignored for when using loops.

**Describe alternatives you've considered**

Use one resource block per repository.

**Additional context**

tfsec version is v1.26.3

**Comment by chris3ware** [comment]
Commenting to prevent closure

**Comment by marccarre** [comment]
@chris3ware, you probably found the solution already, but apparently the `ignore` annotation needs to go on the `resource`/`module` itself, e.g.:

```hcl
#tfsec:ignore:github-repositories-private
resource "github_repository" "this" {
  # ...
}
```

**Comment by chris3ware** [comment]
> @chris3ware, you probably found the solution already, but apparently the `ignore` annotation needs to go on the `resource`/`module` itself, e.g.:
> 
> 
> 
> ```hcl
> 
> #tfsec:ignore:github-repositories-private
> 
> resource "github_repository" "this" {
> 
>   # ...
> 
> }
> 
> ```

Hi, agreed, this is fine for a single resource. However the issue is querying how resources created using for_each can be ignored if required.

If, for example, you create 10 resources from a single resource block with different attributes defined using a variable - you may want to exclude some, but not others because each resource could have different attributes. In the GitHub example, some repos could be private and others public.

**Comment by simar7** [comment]
We've improved the trivyignore capabilities in the latest release of trivy, you can find more details here https://aquasecurity.github.io/trivy/v0.45/docs/configuration/filtering/#trivyignoreyaml
