### ISSUE TITLE
feat: New rules to detect DNS mis-configurations

### ISSUE THREAD

**Issue by bubbletroubles** [aquasecurity/tfsec#1836]
**Is your feature request related to a problem? Please describe.**
DNS zones can be configured with relative (partially qualified) or absolute (fully qualified) entries. A common misconfiguration is to define absolute NS servers. They should always be suffixed with a `.` to signify its an absolute (fully qualified) DNS record.

**Describe the solution you'd like**
When configuring NS servers, ensure there is a trailing `.` on the entry.

**Describe alternatives you've considered**
none

**Comment by nikpivkin** [comment]
Hi @bubbletroubles !

Which provider and resource do you mean?

**Comment by bubbletroubles** [comment]
This one - https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/dns_zone.html

**Comment by nikpivkin** [comment]
@bubbletroubles Could you give an example of an misconfiguration? I don't really understand your idea.

**Comment by bubbletroubles** [comment]
See this issue/pull request for more details

https://github.com/hashicorp/terraform-provider-azurerm/pull/17699

**Comment by simar7** [comment]
hi @bubbletroubles thanks, if we're willing to submit us a pull request we will be happy to look into it. Our efforts have moved to Trivy so the new rule will be written in defsec (Trivy's rule engine and policy/rule repo). You can see an example here https://github.com/aquasecurity/defsec/blob/master/rules/cloud/policies/aws/rds/disable_public_access.rego
