### ISSUE TITLE
bug: custom tfchecks names (IDs) are prefixed with 'custom-custom'

### ISSUE THREAD

**Issue by aleksandary** [aquasecurity/tfsec#1838]
Hello,

This is noticed on tfsec version v1.26.3 (latest).

I am creating a custom checks and noticed that they are prefixed with 'custom-custom'.

In the yaml it looks like this:
`code: rds-iam-authentication`

But on the error message can be seen this:
`ID custom-custom-rds-iam-authentication`

Am I missing something or it's a bug?

Thank you!

**Comment by aleksandary** [comment]
unstale

**Comment by nikpivkin** [comment]
Hi @aleksandary !

This is fixed in [Trivy](https://github.com/aquasecurity/trivy).

/cc @simar7
