### ISSUE TITLE
bug: After `v1.27.0` not all `#tfsec:ignore:` directives are working

### ISSUE THREAD

**Issue by stevehipwell** [aquasecurity/tfsec#1842]
**Describe the bug**

After upgrading tfsec to v1.27.0 from v1.26.3 a number of `#tfsec:ignore:` directives are no longer working.

The rules which are failing on the workspace where I noticed this are:

- aws-ec2-no-public-egress-sgr
- aws-ec2-enforce-launch-config-http-token-imds

**To Reproduce**
1. Upgrade to use v1.27.0 and use ignore directives

**Expected behavior**

I expect the ignores to continue working.

**Output of your tfsec command with --debug flag**

**System Info**

 - tfsec version: 1.27.0
 - terraform version: v1.2.6
 - OS: ALL

**Example Code**

**Additional context**

**Comment by owenrumney** [comment]
Hi @stevehipwell  - are you saying that ignores like `#tfsec:ignore:aws-vpc-no-public-egress=sgr` is not longer ignoring?

We've moved some checks around but it should be backward compatible. I'll check based on this assumption

**Comment by stevehipwell** [comment]
@owenrumney yes that's correct. I saw it happen in real time as pipelines before the release were passing and as soon as the release dropped the same pipelines on the same code were failing.

**Comment by owenrumney** [comment]
I've found the issue, just working it through now https://github.com/aquasecurity/defsec/pull/782

**Comment by owenrumney** [comment]
@stevehipwell  - v1.27.1 is building now, should be with us in 5-10mins

**Comment by stevehipwell** [comment]
@owenrumney I can confirm that this has fixed my issue.
