### ISSUE TITLE
bug: --exclude-path not working for .terraform

### ISSUE THREAD

**Issue by themr97** [aquasecurity/tfsec#1844]
For us --exclude-downloaded-modules was not working so we decided to use --exclude-path .terraform to remove downloaded modules from check but for some reason the examples in .terraform modules are also considered as issue
![tfsecissue](https://user-images.githubusercontent.com/23507448/182361843-5933dd1d-e704-440d-a00f-a7b1a3464f49.png)

**Comment by liamg** [comment]
Hi @themr97 - I believe `--exclude-downloaded-modules` and `--exclude-path` will be fixed in today's release - should be available in the next hour or so.

**Comment by CaseyLabs** [comment]
Hi @liamg, I just ran into this bug as well when upgrading from 1.7.0 to 1.7.2, and it appears to be present in the latest release as well.

**Comment by liamg** [comment]
Are you using `--force-all-dirs`? It will force all directories to be scanned, whereas omitting the option will scan any directories which are explicitly loaded in via modules etc. (i.e. should behave as terraform itself does) - i'll take a look at this today either way.
