### ISSUE TITLE
Individual causes list the wrong line number for modules

### ISSUE THREAD

**Issue by acdha** [aquasecurity/tfsec#1845]
tfsec: v1.27.1

I have noticed an interesting display issue with a bunch of for_each module references: the file and line number displayed at the top of the report and for the code fragment are correct but under “Individual Causes” it displays the filename for the module but the line number for the file which referenced it. 

```
Results #1-18 HIGH IAM policy document uses sensitive action 'lambda:DeleteEventSourceMapping' on wildcarded resource '*' (18 similar results)
───────────────────────────────────────────────────────────────────────────────────────────
  microservices/iam.tf:59
   via main.tf:463-482 (module.microservices["alerts"])
───────────────────────────────────────────────────────────────────────────────────────────
    1    data "aws_iam_policy_document" "deployment_policy" {
    .  
   59  [     resources = ["*"]
  ...  
  303    }
───────────────────────────────────────────────────────────────────────────────────────────
  Individual Causes
  - microservices/iam.tf:463-482 (module.microservices["alerts"]) 16 instances
  - microservices/iam.tf:463-482 (module.microservices["alerts"]) 2 instances
───────────────────────────────────────────────────────────────────────────────────────────
```

I think this would make the most sense as `microservices/iam.tf:59` since the value it used for that particular module instance is clearly indicated immediately afterwards in parentheses.

**Comment by simar7** [comment]
Our efforts have moved to Trivy. Please file a discussion in the Trivy repo if you see fit.
