### ISSUE TITLE
bug: Azure NSG checks not working as expected

### ISSUE THREAD

**Issue by DevMan01** [aquasecurity/tfsec#1855]
**Describe the bug**
I'm getting multiple warnings on some Azure NSG's:
- azure-network-disable-rdp-from-internet
- azure-network-no-public-ingress
- azure-network-ssh-blocked-from-internet

This is perplexing as my NSG rules clearly state that access is allowed, but only from dedicated CIDR ranges.

**To Reproduce**
1. Within an Azure NSG policy add example code as mentioned below.
2. Perform a the following tfsec command `tfsec . --format junit --out tfsec_test_results.xml`
3. Review tfsec_test_results.xml and find unfounded critical notification.

**Expected behavior**
The example NSG clearly states that only certain hosts from a defined CIDR prefix should be allowed through the rules. This should qualify and not be flagged as a critical vulnerability.

**Output of your tfsec command with --debug flag**
https://pastebin.com/cuei0VA7
- Expires in 1 year.

**System Info**

 - tfsec version: v1.27.1
 - terraform version: 1.27
 - OS: Red Hat 4.8.5-44

**Example Code**
https://pastebin.com/5aXYchEf
- Expires in 1 year.

**Additional context**
Work around using # ignore statements.

**Comment by DevMan01** [comment]
Bumping this so it doesn’t go stale.

**Comment by nikpivkin** [comment]
Hi @DevMan01 !

It seems the sample code is no longer available, could you update the link so that I can investigate this?
