### ISSUE TITLE
bug: tfsec v1.27.5 displayed aquasecurity.github.io links all result in 404

### ISSUE THREAD

**Issue by mdebord-dlr** [aquasecurity/tfsec#1871]
**Describe the bug**
aquasecurity.github.io links generated with tfsec v1.27.5 all result in 404

**To Reproduce**
1. Run 1 or more tests that have failed checks with v1.27.5
2. Navigate to the displayed check documentation URL
3. Note that the link 404's

**Expected behavior**
Links navigate to a working page

**Output**

Some examples: 
```
|   More Information
|   - https://aquasecurity.github.io/tfsec/v1.27.5/checks/aws/elb/drop-invalid-headers/
|   - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb#drop_invalid_header_fields
```

```
|   More Information
|   - https://aquasecurity.github.io/tfsec/v1.27.5/checks/aws/elb/alb-not-public/
|   - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb
```

**System Info**

 - tfsec version: `v1.27.5`

**Comment by liamg** [comment]
Thanks, it looks like the GitHub action failed to deploy the docs - looking into it now...

**Comment by liamg** [comment]
The latest docs are now live :partying_face:
