### ISSUE TITLE
feat: add GCP storage bucket customer-managed encryption key check

### ISSUE THREAD

**Issue by ryan-jan** [aquasecurity/tfsec#1880]
I would like to propose a PR to add a check to ensure that GCP storage buckets are configured to use customer-managed encryption keys, much like the compute instance `disk_encryption_customer_key.go` check that already exists. 

I have a working fork ready to go if this is something that would be accepted?

**Comment by liamg** [comment]
Hi @ryan-jan this sounds great, a PR would be very welcome!

**Comment by nikpivkin** [comment]
@simar7 This can be closed https://github.com/aquasecurity/defsec/commit/1645d060e81736f95ccd067eefb5d7c211c223a4
