### ISSUE TITLE
bug: AWS no-public-ip-subnet has no documentation

### ISSUE THREAD

**Issue by gbloquel** [aquasecurity/tfsec#1881]
**Describe the bug**
In the release tfsec 1.27.6 you have upgraded the defsec to [v0.73.0](https://github.com/aquasecurity/defsec/releases/tag/v0.73.0)
The release defsec introduces a new rule [no_public_ip_subnet](https://github.com/aquasecurity/defsec/blob/1e5198eb8c8625f90370640e7a53e9d49a715dcb/internal/rules/aws/ec2/no_public_ip_subnet.go)
If this rule is detected you have the message
```
          ID aws-ec2-no-public-ip-subnet
      Impact The instance is publicly accessible
  Resolution Set the instance to not be publicly accessible

  More Information
  - https://aquasecurity.github.io/tfsec/v1.27.6/checks/aws/ec2/no-public-ip-subnet/
  - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/subnet#map_public_ip_on_launch
```
But for the [link](https://aquasecurity.github.io/tfsec/v1.27.6/checks/aws/ec2/no-public-ip-subnet/) returned the documentation is unavailable then 404

**To Reproduce**
 

**Expected behavior**
The documencation must be written

**Output of your tfsec command with --debug flag**

**System Info**
 - tfsec version: `1.27.6`
 - terraform version: `1.2.8`
 - OS: `?`

**Example Code**

**Additional context**

**Comment by jphilaine** [comment]
We have the same problem with the rule: "aws-cloudtrail-ensure-cloudwatch-integration"

```
          ID aws-cloudtrail-ensure-cloudwatch-integration
      Impact Realtime log analysis is not available without enabling CloudWatch logging
  Resolution Enable logging to CloudWatch

  More Information
  - https://aquasecurity.github.io/tfsec/v1.27.5/checks/aws/cloudtrail/ensure-cloudwatch-integration/
  - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudtrail
```
