### ISSUE TITLE
question: Custom checks using resource identifier

### ISSUE THREAD

**Issue by yatmengho** [aquasecurity/tfsec#1882]
Hi,

Just to check. Can custom checks able to check on the identifier naming?

For example, can the custom checks be designed in such a way it can detect the value "identifier1"?

resource "aws_instance" "identifier1" {
 ami = "ami-0d527b8c289b4af7f"
 instance_type = "t3.micro"
 tags = {
    "ClusterServer" = "test"
  }
}

**Comment by duxbuse** [comment]
This would be really great since there is no way of adding custom fields to TF resources

**Comment by simar7** [comment]
dupe of https://github.com/aquasecurity/tfsec/issues/1803
