### ISSUE TITLE
question: How can we specify access rights to specific folders without breaking security check

### ISSUE THREAD

**Issue by lazarillo** [aquasecurity/tfsec#1888]
[This IAM policy](https://aquasecurity.github.io/tfsec/v1.20.0/checks/aws/iam/no-policy-wildcards/) says that no wildcards should be used in policies.  However, I cannot understand how to *truly use principals of least privilege* without using the wildcard.

Here is our example:

```
data "aws_iam_policy_document" "example" {
  statement {
    sid = "allow S3 read-only access"
    actions = [
      "s3:GetObject",
      "s3:ListMultipartUploadParts",
      "s3:ListObjects"
    ]
    resources = ["arn:aws:s3:::my-example-bucket/my-folder/*"]
  }
}
```

This gives me rights to **only the folder `my-folder`** within the bucket `my-example-bucket`.  But if I follow the best practice suggested on that link, I would have to do the following:

```
data "aws_iam_policy_document" "example" {
  statement {
    sid = "allow S3 read-only access"
    actions = [
      "s3:GetObject",
      "s3:ListMultipartUploadParts",
      "s3:ListObjects"
    ]
    resources = [aws_s3_bucket.my-example-bucket.arn]
  }
}
```

This, on the other hand, forces me to give access to the entire bucket.  It is not clear to me how I can share only a particular folder and everything under its tree, instead of sharing the entire bucket, while not triggering this `tfsec` issue.

**Comment by lazarillo** [comment]
I don't understand why this is stale.  I'm asking the right way to handle it.  But because no one knows, this will be closed.  I don't understand how you want me to raise it.

**Comment by TLaue** [comment]
I am asking myself the same question. What is the intended behaviour for instance with "s3:GetObject"?

**Comment by marcemv90** [comment]
Bump, we are also interesting in how to handle those situations.

**Comment by nikpivkin** [comment]
Hi @lazarillo!

The developers efforts have moved to Trivy.

S3 service is an exception to this rule:

My config:
```tf
resource "aws_iam_role" "this" {
  name = "test_role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Sid    = ""
        Principal = {
          Service = "s3.amazonaws.com"
        }
      },
    ]
  })
}

resource "aws_iam_role_policy" "this" {
  name   = "test_policy"
  role   = aws_iam_role.this.id
  policy = data.aws_iam_policy_document.this.json
}

data "aws_iam_policy_document" "this" {
  statement {
    sid = "allow S3 read-only access"
    actions = [
      "s3:GetObject",
      "s3:ListMultipartUploadParts",
      "s3:ListObjects"
    ]
    resources = ["arn:aws:s3:::my-example-bucket/my-folder/*"]
  }
}
```

Trivy output:
```bash
trivy config . -d
2023-09-01T22:15:13.562+0700    DEBUG   Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2023-09-01T22:15:13.572+0700    DEBUG   cache dir:  /Users/tososomaru/Library/Caches/trivy
2023-09-01T22:15:13.572+0700    DEBUG   Module dir: /Users/tososomaru/.trivy/modules
2023-09-01T22:15:13.572+0700    INFO    Misconfiguration scanning is enabled
2023-09-01T22:15:13.573+0700    DEBUG   Policies successfully loaded from disk
2023-09-01T22:15:13.597+0700    DEBUG   Walk the file tree rooted at '.' in parallel
2023-09-01T22:15:13.598+0700    DEBUG   Scanning Terraform files for misconfigurations...
2023-09-01T22:15:13.949+0700    DEBUG   OS is not detected.
2023-09-01T22:15:13.949+0700    INFO    Detected config files: 2
2023-09-01T22:15:13.949+0700    DEBUG   Scanned config file: .
2023-09-01T22:15:13.949+0700    DEBUG   Scanned config file: main.tf
```

/cc @simar7

**Comment by nikpivkin** [comment]
What kind of check you mean? Trivy [checks](https://github.com/aquasecurity/trivy-iac/blob/9030770c9f735ad1c682e66c2ac62a99b933069e/internal/adapters/terraform/aws/iam/convert.go#L45) `aws_iam_policy_document` data sources.

**Comment by skadz** [comment]
@nikpivkin I have code that fails when the policy is inline tfsec fails with:

aws-iam-no-policy-wildcards

If I change the code to an aws_iam_policy_document (and terraform shows NO CHANGES)

tfsec and trivy both pass without issue

**Comment by skadz** [comment]
This passes like this, but if you switch the policy to the inline one (which causes ZERO changes), it fails

`data "aws_iam_policy_document" "healthscribe_s3_policy_doc" {
  count = var.healthscribe ? length(var.healthscribe_output_buckets) : 0

  statement {
    sid = "HealthscribeS3Access${count.index}"
    actions = [
      "s3:PutObject",
      "s3:GetBucketVersioning",
      "s3:GetObjectVersion",
      "s3:GetObject"
    ]
    resources = [
      "${var.healthscribe_output_buckets[count.index]}/*",
      "${var.healthscribe_output_buckets[count.index]}"
    ]
  }
}


resource "aws_iam_policy" "healthscribe_s3_policy" {
  count = var.healthscribe ? length(var.healthscribe_output_buckets) : 0

  name        = "healthscribe_s3_policy_${count.index}"
  path        = "/"
  description = "Healthscribe S3 Policy (${var.healthscribe_output_buckets[count.index]})"
  policy      = data.aws_iam_policy_document.healthscribe_s3_policy_doc[count.index].json

  # policy = <<POLICY
  # {
  #     "Version": "2012-10-17",
  #     "Statement": [
  #         {
  #             "Sid": "HealthscribeS3Access${count.index}",
  #             "Effect": "Allow",
  #             "Action": [
  #               "s3:GetObject",
  #               "s3:GetObjectVersion",
  #               "s3:GetBucketVersioning",
  #               "s3:PutObject"
  #             ],
  #             "Resource": [
  #               "${var.healthscribe_output_buckets[count.index]}/*",
  #               "${var.healthscribe_output_buckets[count.index]}"
  #             ]
  #         }
  #     ]
  # }
  # POLICY
}
`

**Comment by nikpivkin** [comment]
I see what you mean. Please note that I did not remove the test check, but used `aws_iam_policy_document` as in the issue [description](https://github.com/aquasecurity/tfsec/issues/1888#issue-1364346485). I'll investigate this and create an issue.

**Comment by nikpivkin** [comment]
@skadz Track https://github.com/aquasecurity/trivy/issues/5552
