### ISSUE TITLE
feat: Yandex Cloud terraform provider support

### ISSUE THREAD

**Issue by rufusnufus** [aquasecurity/tfsec#1889]
**Is your feature request related to a problem? Please describe.**

We want to scan our IaC, however there is no support for [Yandex Cloud terraform provider ](https://github.com/yandex-cloud/terraform-provider-yandex). For now, `tfsec` shows zero problems.

**Describe the solution you'd like**

It would be great if `tfsec` will support [Yandex Cloud terraform provider](https://github.com/yandex-cloud/terraform-provider-yandex)

**Describe alternatives you've considered**

**Additional context**

**Comment by rufusnufus** [comment]
this is still a feature report =)

**Comment by simar7** [comment]
At the moment we don't have plans to add this. Please feel free to open an issue in the Trivy repo if you see fit.
