### ISSUE TITLE
question: pod security policy rule

### ISSUE THREAD

**Issue by wyardley** [aquasecurity/tfsec#1904]
Based on:
https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/
my understanding is that pod security policies are deprecated in / as of Kubernetes 1.21

Does that affect the rule mentioned here?
https://aquasecurity.github.io/tfsec/v1.28.0/checks/google/gke/enforce-pod-security-policy/

**Comment by userbradley** [comment]
I would make the assumption that it will be removed at some point as it's been deprecated on GKE too

https://github.com/aquasecurity/tfsec/issues/1879

**Comment by wyardley** [comment]
Thanks. Will close and follow that issue
