### ISSUE TITLE
bug: broken link to bucket encryption customer key warning for GCS

### ISSUE THREAD

**Issue by wyardley** [aquasecurity/tfsec#1905]
**Describe the bug**
tfsec 1.28 has the following output for a bucket without customer managed encryption key defined
```
          ID google-storage-bucket-encryption-customer-key
      Impact Using unmanaged keys does not allow for proper key management.
  Resolution Encrypt Cloud Storage buckets using customer-managed keys.

  More Information
  - https://aquasecurity.github.io/tfsec/v1.28.0/checks/google/storage/bucket-encryption-customer-key/
  - https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket#encryption
```

**To Reproduce**
1. Go to https://aquasecurity.github.io/tfsec/v1.28.0/checks/google/storage/bucket-encryption-customer-key/
2. Get a 404

**Expected behavior**
Documentation is found

**Output of your tfsec command with --debug flag**

**System Info**

 - tfsec version: `1.28.0`
 - terraform version: `1.3.0`
 - OS: `Darwin 21.6.0 arm64`

**Example Code**

**Additional context**
Separately, I'm a bit curious about the motivation behind this policy. While I'm glad it's low severity, I've generally found that Google's key policies are reasonable and line up with most people's compliance / security needs; I generally find it sensible to use theirs unless there's a compelling reason to use customer managed ones (esp. with the possibility of permanently losing access to data if a key is somehow destroyed).

**Comment by wyardley** [comment]
Hi folks - I think this is still an issue

**Comment by PaSalva** [comment]
Hello. Any update on this issue?

**Comment by wyardley** [comment]
I'm going to close this since it's unlikely it will be fixed / improved now that tfsec is deprecated / moving to Trivy.
