### ISSUE TITLE
question: Regarding digitalocean enforce-https

### ISSUE THREAD

**Issue by designermonkey** [aquasecurity/tfsec#1907]
Regarding: https://aquasecurity.github.io/tfsec/v1.27.5/checks/digitalocean/compute/enforce-https/

Digitalocean require an http route to be present to allow redirection of HTTP to https, yet this rule still triggers as a false positive. Would it be possible to change the rule to look for the presence of the `redirect_http_to_https` part of the terraform code and not trigger the rule if it is present?

**Comment by designermonkey** [comment]
It's stale with no response!

**Comment by nikpivkin** [comment]
Sounds reasonable 
@simar7 WDYT?

**Comment by simar7** [comment]
Yeah fair enough I have opened this as an improvement to track in Trivy: https://github.com/aquasecurity/trivy/issues/5111
