### ISSUE TITLE
bug: Security Vulnerabilities created with no Severity

### ISSUE THREAD

**Issue by AgnellusX1** [aquasecurity/tfsec#1908]
**Describe the bug**
The Security Vulnerabilities that are created in the GitHub Security Tab, do not have vulnerabilities assigned to it

**Expected behavior**
Vulnerability Levels should ideally be set as Critical, High, Medium, Low, Info.
This is actually the output of the scan, but vulnerabilities aren't created using them

Using the latest Github Actions

**System Info**
 - tfsec version: `1.28.0`
 - terraform version: `?`
 - OS: `?`

**Additional context**
<img width="968" alt="Screenshot 2022-09-29 at 11 56 49 AM" src="https://user-images.githubusercontent.com/43168803/192955825-6d1d1f1e-fef5-4463-8f01-b377b4cc15af.png">

**Comment by nikpivkin** [comment]
How did you upload the result to Github?

Now the efforts of developers are focused on the development and support of [Trivy](https://github.com/aquasecurity/trivy). You can upload the results of the Trivy scan to Github using [trivy-action](https://github.com/aquasecurity/trivy-action).

/cc @simar7
