### ISSUE TITLE
bug: Tfsec fails during parsing

### ISSUE THREAD

**Issue by AlexLudwigITDienstleistungen** [aquasecurity/tfsec#1915]
**Describe the bug**
tfsec fails with the following error when parsing azurerm_key_vault_key module:
`panic: not a string`

**To Reproduce**
1. Run tfsec

**Expected behavior**
No panic error.

**Output of your tfsec command with --debug flag**
`C:\Users\ludwig\source\repos\Infrastructre as Code\terraform\environment>tfsec --debug
21:24.161220000 system.info                      APP       tfsec.exe
21:24.314357800 system.info                      VERSION   v1.28.0
21:24.316534400 system.info                      OS        windows
21:24.322233400 system.info                      ARCH      amd64
21:24.323375300 system.info                      KERNEL
21:24.323993600 system.info                      TERM
21:24.325111800 system.info                      SHELL
21:24.325735600 system.info                      GOVERSION go1.18.5
21:24.326278600 system.info                      GOROOT    /opt/hostedtoolcache/go/1.18.5/x64
21:24.327379700 system.info                      CGO       false
21:24.328466400 system.info                      CPUCOUNT  8
21:24.329552000 system.info                      MAXPROCS  8
21:24.329777800 system.info                      WORKDIR   C:\Users\ludwig\source\repos\Infrastructre as Code\terraform\environment
21:24.330856700 system.info                      UID       -1
21:24.331400200 system.info                      EUID      -1
21:24.332525400 system.info                      DOCKER    false
21:24.334527500 system.info                      CI        false
21:24.339850600 system.info                      HOSTNAME  ITS549
21:24.340419200 system.info                      TEMP      C:\Users\ludwig\AppData\Local\Temp
21:24.341700100 system.info                      PATHSEP   \
21:24.342317400 system.info                      CMD       tfsec --debug
21:24.343220400 cmd                              Command args=[]string{}
21:24.344218000 cmd                              Determined path dir=C:\Users\ludwig\source\repos\Infrastructre as Code\terraform\environment
21:24.345220200 cmd                              Determined path root=C:
21:24.345220200 cmd                              Determined path rel=Users\ludwig\source\repos\Infrastructre as Code\terraform\environment
21:24.346809800 terraform.scanner                Scanning [&{C: C:}] at 'Users\ludwig\source\repos\Infrastructre as Code\terraform\environment'...
21:24.349089500 terraform.scanner.rego           Loaded 4 embedded libraries.
21:24.390033900 terraform.scanner.rego           Loaded 117 embedded policies.
21:24.488053000 terraform.scanner                Scanning root module 'Users\ludwig\source\repos\Infrastructre as Code\terraform\environment'...
21:24.488053000 terraform.parser.<root>          Setting project/module root to 'Users\ludwig\source\repos\Infrastructre as Code\terraform\environment'
21:24.492017600 terraform.parser.<root>          Parsing FS from 'Users/ludwig/source/repos/Infrastructre as Code/terraform/environment'
21:24.496021500 terraform.parser.<root>          Parsing 'Users\ludwig\source\repos\Infrastructre as Code\terraform\environment\config.tf'...
21:24.497019000 terraform.parser.<root>          Added file Users\ludwig\source\repos\Infrastructre as Code\terraform\environment\config.tf.
21:24.498019200 terraform.parser.<root>          Parsing 'Users\ludwig\source\repos\Infrastructre as Code\terraform\environment\data.tf'...
21:24.500039700 terraform.parser.<root>          Added file Users\ludwig\source\repos\Infrastructre as Code\terraform\environment\data.tf.
21:24.501041900 terraform.parser.<root>          Parsing 'Users\ludwig\source\repos\Infrastructre as Code\terraform\environment\test_gitlab_test.tf'...
21:24.503018600 terraform.parser.<root>          Added file Users\ludwig\source\repos\Infrastructre as Code\terraform\environment\test_gitlab_test.tf.
21:24.504022100 terraform.parser.<root>          Parsing 'Users\ludwig\source\repos\Infrastructre as Code\terraform\environment\key_vault.tf'...
21:24.506018600 terraform.parser.<root>          Added file Users\ludwig\source\repos\Infrastructre as Code\terraform\environment\key_vault.tf.
21:24.511886400 terraform.parser.<root>          Parsing 'Users\ludwig\source\repos\Infrastructre as Code\terraform\environment\local.tf'...
21:24.513897800 terraform.parser.<root>          Added file Users\ludwig\source\repos\Infrastructre as Code\terraform\environment\local.tf.
21:24.516894800 terraform.parser.<root>          Parsing 'Users\ludwig\source\repos\Infrastructre as Code\terraform\environment\network.tf'...
21:24.519887400 terraform.parser.<root>          Added file Users\ludwig\source\repos\Infrastructre as Code\terraform\environment\network.tf.
21:24.519887400 terraform.parser.<root>          Parsing 'Users\ludwig\source\repos\Infrastructre as Code\terraform\environment\providers.tf'...
21:24.521908800 terraform.parser.<root>          Added file Users\ludwig\source\repos\Infrastructre as Code\terraform\environment\providers.tf.
21:24.524886600 terraform.parser.<root>          Parsing 'Users\ludwig\source\repos\Infrastructre as Code\terraform\environment\terraform.tf'...
21:24.528712900 terraform.parser.<root>          Added file Users\ludwig\source\repos\Infrastructre as Code\terraform\environment\terraform.tf.
21:24.529293700 terraform.parser.<root>          Parsing 'Users\ludwig\source\repos\Infrastructre as Code\terraform\environment\terraform_agents.tf'...
21:24.530811500 terraform.parser.<root>          Added file Users\ludwig\source\repos\Infrastructre as Code\terraform\environment\terraform_agents.tf.
21:24.531318400 terraform.parser.<root>          Parsing 'Users\ludwig\source\repos\Infrastructre as Code\terraform\environment\variables.tf'...
21:24.532949900 terraform.parser.<root>          Added file Users\ludwig\source\repos\Infrastructre as Code\terraform\environment\variables.tf.
21:24.533120500 terraform.parser.<root>          Parsing 'Users\ludwig\source\repos\Infrastructre as Code\terraform\environment\virtual_machine_windows.tf'...
21:24.537839700 terraform.parser.<root>          Added file Users\ludwig\source\repos\Infrastructre as Code\terraform\environment\virtual_machine_windows.tf.
21:24.540324200 terraform.parser.<root>          Evaluating module...
21:24.543243200 terraform.parser.<root>          Read 38 block(s) and 3 ignore(s) for module 'root' (11 file[s])...
21:24.545198000 terraform.parser.<root>          Added 0 variables from tfvars.
21:24.545763200 terraform.parser.<root>          Error loading module metadata: open Users\ludwig\source\repos\Infrastructre as Code\terraform\environment\.terraform\modules\modules.json: invalid argument.
21:24.546934900 terraform.parser.<root>          Working directory for module evaluation is 'C:\Users\ludwig\source\repos\Infrastructre as Code\terraform\environment'
21:24.547501800 terraform.parser.<root>.evaluator Filesystem key is '98d6a362eb8a41f901f5a1635aca87711499f306803437f93a9fa0f398dc83b6'
...
21:26.455127900 terraform.parser.<root>.evaluator Finished processing 34 submodule(s).
21:26.456328900 terraform.parser.<root>.evaluator Starting post-submodule evaluation...
21:26.460131900 terraform.parser.<root>.evaluator Module evaluation complete.
21:26.460131900 terraform.parser.<root>          Finished parsing module 'root'.
21:26.464559200 terraform.executor               Adapting modules...
panic: not a string

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Value.AsString({{{0x0?, 0x0?}}, {0x0?, 0x0?}})
        /home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.10.0/cty/value_ops.go:1256 +0x138
github.com/aquasecurity/defsec/internal/adapters/terraform/azure/keyvault.adaptKey(0xc0009e1980)
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.76.0/internal/adapters/terraform/azure/keyvault/adapt.go:154 +0x1ca
github.com/aquasecurity/defsec/internal/adapters/terraform/azure/keyvault.(*adapter).adaptVaults(0xc001ee4bb8, {0xc0025bbe60, 0x23, 0xc001ee4bc8?})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.76.0/internal/adapters/terraform/azure/keyvault/adapt.go:74 +0x14b1
github.com/aquasecurity/defsec/internal/adapters/terraform/azure/keyvault.Adapt({0xc0025bbe60, 0x23, 0x24})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.76.0/internal/adapters/terraform/azure/keyvault/adapt.go:20 +0xd3
github.com/aquasecurity/defsec/internal/adapters/terraform/azure.Adapt({_, _, _})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.76.0/internal/adapters/terraform/azure/adapt.go:30 +0x2b7
github.com/aquasecurity/defsec/internal/adapters/terraform.Adapt({0xc0025bbe60, 0x23, 0x24})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.76.0/internal/adapters/terraform/adapt.go:20 +0x7e
github.com/aquasecurity/defsec/pkg/scanners/terraform/executor.(*Executor).Execute(0xc0015db900, {0xc0025bbe60?, 0x23, 0x24})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.76.0/pkg/scanners/terraform/executor/executor.go:96 +0x11a
github.com/aquasecurity/defsec/pkg/scanners/terraform.(*Scanner).ScanFSWithMetrics(0xc0002064b0, {0x1ceee50, 0xc0000340f8}, {0x256afdc6a50?, 0xc000bb0620?}, {0xc000037683, 0x45})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.76.0/pkg/scanners/terraform/scanner.go:210 +0x75a
github.com/aquasecurity/tfsec/internal/app/tfsec/cmd.Root.func1(0xc000160780, {0xc001041930, 0x0, 0x1})
        /home/runner/work/tfsec/tfsec/internal/app/tfsec/cmd/root.go:83 +0x633
github.com/spf13/cobra.(*Command).execute(0xc000160780, {0xc0000763d0, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000160780)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        /home/runner/work/tfsec/tfsec/cmd/tfsec/main.go:12 +0x25`

unfortunately i had to shorten the debug output because of the maximum comment length.

**System Info**
 - tfsec version: `1.28.0`
 - terraform version: `1.3.1`
 - OS: `Windows 10`

**Example Code**
`module "key_vaukt_key_demo-gitlab-runner1" {
  source       = "../modules/AzureRM/key_vault/key_vault_key"
  name         = "demo-gitlab-runner1-gitlab-runner-admin"
  key_vault_id = module.key_vault.id
  key_size     = 8192
  key_type     = "RSA"
  key_opts     = tolist(["decrypt", "encrypt", "sign"])
  depends_on   = [module.key_vault.id]
}`
`resource "azurerm_key_vault_key" "akv-key" {
  name            = var.name
  key_vault_id    = var.key_vault_id
  key_type        = var.key_type
  key_size        = var.key_size
  key_opts        = var.key_opts
}`
`variable "name" {
  type        = string
  description = "(Required) Specifies the name of the Key Vault Key. Changing this forces a new resource to be created."
}
variable "key_vault_id" {
  type        = string
  description = "(Required) The ID of the Key Vault where the Key should be created. Changing this forces a new resource to be created."
}
variable "key_type" {
  type        = string
  description = "(Required) Specifies the Key Type to use for this Key Vault Key. Possible values are EC (Elliptic Curve), EC-HSM, RSA and RSA-HSM. Changing this forces a new resource to be created."
}
variable "key_size" {
  type        = number
  description = "(Optional) Specifies the Size of the RSA key to create in bytes. For example, 1024 or 2048. Note: This field is required if key_type is RSA or RSA-HSM. Changing this forces a new resource to be created."
  nullable    = true
  default     = null
}
variable "key_opts" {
  type        = list(string)
  description = "(Required) A list of JSON web key operations. Possible values include: decrypt, encrypt, sign, unwrapKey, verify and wrapKey. Please note these values are case sensitive."
}`

**Additional context**
Without this resource, tfsec runs with the following output:
C:\Users\ludwig\source\repos\Infrastructre as Code\terraform\environment>tfsec
  timings
  ──────────────────────────────────────────
  disk i/o             25.5077ms
  parsing              308.4069ms
  adaptation           1.0026ms
  checks               125.6952ms
  total                460.6124ms

  counts
  ──────────────────────────────────────────
  modules downloaded   0
  modules processed    34
  blocks processed     1066
  files read           148

  results
  ──────────────────────────────────────────
  passed               17
  ignored              3
  critical             0
  high                 0
  medium               0
  low                  0

No problems detected!

**Comment by AndreasMWalter** [comment]
We have a similar, although different issue:
When using the time_offset resource to fill expiration date, it will work with:
`time_offset.expiration.id` as input. However time_offset.expiration.id is the current date...
`time_offset.expiration.rf3339` which is the actual offset resource will `panic not a string` even though it is a string...
![image](https://user-images.githubusercontent.com/38529659/196169952-8668f278-6c79-4059-a377-17ee99f1471b.png)

```terraform 
resource "azurerm_key_vault_key" "customer_managed_key" {
  name                 = "cmk-${var.name_infix}-${local.stage}"
  key_vault_id       = module.keyvault.key_vault_id
  key_type            = "RSA-HSM"
  key_size             = 4096
  key_opts            = ["decrypt", "encrypt", "sign", "unwrapKey", "verify", "wrapKey"]
  expiration_date = time_offset.expiration.rfc3339
}
```

**Comment by AlexLudwigITDienstleistungen** [comment]
Any new Informations to this issue? The issue is still persistent in Version 1.28.1.

**Comment by deggy9** [comment]
any updates on this?

**Comment by nikpivkin** [comment]
Hi @AlexLudwigITDienstleistungen !

This has been [fixed](https://github.com/aquasecurity/defsec/issues/1024). You can use Trivy to scan the configuration, because tfsec is [part of it](https://github.com/aquasecurity/tfsec/discussions/1994).

/cc @simar7
