### ISSUE TITLE
feat: Support for versined version of kubernetes resources

### ISSUE THREAD

**Issue by ugrave** [aquasecurity/tfsec#1919]
**Is your feature request related to a problem? Please describe.**
The kubernetes checks doesn`t consider the new versionses resources of the kubernetes provider
(https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/guides/versioned-resources)

For ex. the check for ingress and egress are not considered for kubernetes_network_policy_v1 resource.

**Describe the solution you'd like**
tfsec should also check versioned resources.

**Comment by nikpivkin** [comment]
Hi @ugrave !

I created the [issue](https://github.com/aquasecurity/trivy/issues/5115) in Trivy.

/cc @simar7
