### ISSUE TITLE
feat: Adding support for Civo as Cloud provider

### ISSUE THREAD

**Issue by dirsigler** [aquasecurity/tfsec#1920]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to see Civo added as a supported Cloud provider.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by liamg** [comment]
If anyone wants to take a look at this, we have a new [contributing guide](https://github.com/aquasecurity/defsec/blob/master/CONTRIBUTING.md) that gives an overview of adding a new cloud provider.

**Comment by dirsigler** [comment]
Would love to give it a try.
