### ISSUE TITLE
bug: network policy is enabled by default using gke dataplane-v2

### ISSUE THREAD

**Issue by rd-michel** [aquasecurity/tfsec#1921]
**Describe the bug**
network policy is enabled by default when gke is configured with "dataplane-v2".

reference:
https://cloud.google.com/kubernetes-engine/docs/concepts/dataplane-v2#security

**To Reproduce**
1. enable dataplane-v2 in your kubernetes cluster
2. network policy will be listed as "disabled" in the google console cluster overview page
3. hover over the "pencil/edit" button to see the usage hint
"network policy is immutable when dataplane v2 is enabled"

**Expected behavior**
the plugin "https://aquasecurity.github.io/tfsec/v1.28.0/checks/google/gke/enable-network-policy/" should take into account that dataplane-v2 enabled network policy by default

**Output of your tfsec command with --debug flag**
Check: CKV_GCP_12: "Ensure Network Policy is enabled on Kubernetes Engine Clusters"
	FAILED for resource: module.kubernetes.google_container_cluster.example_cluster

**System Info**

 - tfsec version: v1.28.0
 - terraform version: v1.3.2
 - OS: gke 1.24.3-gke.2100

**Example Code**
resource "google_container_cluster" "example_cluster" {
  project     = test_project
  name        = test_cluster
  ..
  datapath_provider = "ADVANCED_DATAPATH"   # to enable dataplane-v2
}

**Comment by rd-michel** [comment]
still an issue

**Comment by nikpivkin** [comment]
Hi @rd-michel !

I opened the [issue](https://github.com/aquasecurity/trivy/issues/5012) in Trivy.

/cc @simar7
