### ISSUE TITLE
bug: aws-s3-encryption-customer-key error shows when using Cloudfront OAI

### ISSUE THREAD

**Issue by Kishore-abhimanyu** [aquasecurity/tfsec#1925]
**Describe the bug**
When using CloudFront OAI and using s3 bucket for storing the logs, currently AWS doesn't support encryption using SSE-KMS and it only supports encryption using SSE-S3. If we use SSE-KMS key the OAI is not working as expected

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a CloudFront OAI resource
2. Add encryption using S3 key

**Expected behaviour**
The error is not expected to be shown as it not supported by AWS

**System Info**
 - tfsec version: `v1.21.0`
 - terraform version: `v1.2.1`
 - OS: `Linux and Mac`

**Comment by nikpivkin** [comment]
it seems that aws now supports encryption with AWS KMS keys: https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingKMSEncryption.html
