### ISSUE TITLE
bug: unable to ignore aws-rds-enable-deletion-protection

### ISSUE THREAD

**Issue by mheiges** [aquasecurity/tfsec#1935]
**Describe the bug**

I am unable to locally ignore `aws-rds-enable-deletion-protection` in my modules. None of these work

```
# tfsec:ignore:aws-rds-enable-deletion-protection
 module "rds" {
   source = "../../modules/rds"

  deletion_protection = false
```

```
 module "rds" {
   source = "../../modules/rds"

  deletion_protection = false # tfsec:ignore:aws-rds-enable-deletion-protection
```

```
 module "rds" {
   source = "../../modules/rds"

  # tfsec:ignore:aws-rds-enable-deletion-protection
  deletion_protection = false
```

The rule is ignored if I exclude it from the global config.yml file

```
exclude:
  - aws-rds-enable-deletion-protection
```

**Output of your tfsec command with --debug flag**

```
Result #1 MEDIUM Instance does not have Deletion Protection enabled
────────────────────────────────────────────────────────────────────────────────
  modules/rds/rds.tf:46
────────────────────────────────────────────────────────────────────────────────
   46      deletion_protection      = var.deletion_protection
────────────────────────────────────────────────────────────────────────────────
  Rego Package builtin.aws.rds.aws0177
     Rego Rule deny
────────────────────────────────────────────────────────────────────────────────
```

It also does not report the rule name, so perhaps `aws-rds-enable-deletion-protection` is not correct. Do Rego packages need a different ignore syntax?

**System Info**

 - tfsec version: `v1.28.1`
 - terraform version: `v1.3.1`
 - OS: `Linux`

**Comment by chbiel** [comment]
same with
`Result #1 MEDIUM Instance does not have IAM Authentication enabled `

does not give an ignorable ID, but
```
 Rego Package builtin.aws.rds.aws0176
     Rego Rule deny
```

**Comment by dkgrayson** [comment]
> same with `Result #1 MEDIUM Instance does not have IAM Authentication enabled `
> 
> does not give an ignorable ID, but
> 
> ```
>  Rego Package builtin.aws.rds.aws0176
>      Rego Rule deny
> ```

Same issue here.

**Comment by seanturner026** [comment]
Same here! Honestly I was coming to github to make an issue about how there's only the id `aws0176` instead of the rule name so that I can do `tfsec:ignore:iam-auth-blahblah`

**Comment by itaysk** [comment]
> Do Rego packages need a different ignore syntax?
No they don't. For example, to ignore the RDS deletion protection check, you can refer to it by any of the following IDs:

```
aws-rds-enable-deletion-protection
AVD-AWS-0177
enable-deletion-protection
```

**Comment by Phylu** [comment]
This somehow seems to be related to #1936. Whenever I try to test my terraform code that uses the `terraform-aws-modules/rds/aws` module, it fails with the error:

```
Result #1 MEDIUM Instance does not have Deletion Protection enabled
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  ../../../../../../terraform-aws-modules/rds/aws/Users/phylu/terraform/folder_1/folder_2/folder_3/.terraform/modules/mssql.db/modules/db_instance/main.tf:93
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Failed to render code: failed to read file from result filesystem (&extrafs.filesystem{root:"/", underlying:"/"}): open //terraform-aws-modules/rds/aws/Users/janosch.maier/terraform/folder_1/folder_2/folder_3/.terraform/modules/mssql.db/modules/db_instance/main.tf: no such file or directory──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Rego Package builtin.aws.rds.aws0177
     Rego Rule deny
```

If I try to disable the rule, none of the following works:
```
# tfsec:ignore:enable-deletion-protection
# tfsec:ignore:AVD-AWS-0177
# tfsec:ignore:aws-rds-enable-deletion-protection
# tfsec:ignore:aws0177
```

When I change line `93` in the corresponding file in the `.terraform/modules` folder manually to the following, I don't get the error anymore:
```
  deletion_protection      = true
```

**Comment by simar7** [comment]
hi all, I've done some digging into this and found the following:

Input `main.tf`:
```terraform
#tfsec:ignore:aws-rds-encrypt-instance-storage-data
#tfsec:ignore:aws-rds-specify-backup-retention
#tfsec:ignore:aws-rds-enable-performance-insights
resource "aws_db_instance" "rds_instance" {
  name      = "db"
  deletion_protection = false #tfsec:ignore:AVD-AWS-0177
}
```

Observe that the `enable-deletetion-protection` is the same as `AVD-AWS-0177` and is ignored beside the line that defines `deletion_protection = false`. The reason for this is because `deletion_protection` exists as a variable and is set in the terraform file, therefore to ignore it, we must set the ignore on the same line (or above it). This behaviour is documented here https://github.com/aquasecurity/tfsec/blob/master/docs/guides/configuration/ignores.md#ignoring-issues

While in the case of rules such as `enable-performance-insights`, we don't have the associated variable present within the block (in other words, `performance_insights_enabled = true` or `performance_insights_enabled = false` is missing). In this case we must define the ignore on the block as a whole. 

When running this with `v1.28.1`:
```shell
docker run --rm -it -v "$(pwd):/src" aquasec/tfsec:v1.28.1 /src --debug
<snip>
48:24.703574560 terraform.executor               Applying ignores...
48:24.703589796 terraform.executor               Ignored 'aws-rds-enable-performance-insights' at 'src/main.tf:4-7'.
48:24.703595994 terraform.executor               Ignored 'aws-rds-encrypt-instance-storage-data' at 'src/main.tf:4-7'.
48:24.703604784 terraform.executor               Ignored 'aws-rds-specify-backup-retention' at 'src/main.tf:4-7'.
48:24.703609597 terraform.executor               Ignored 'aws-rds-enable-deletion-protection' at 'src/main.tf:6'.
48:24.703639147 cmd                              Exit code based on results: 0
<snip>
  results
  ──────────────────────────────────────────
  passed               2
  ignored              4
  critical             0
  high                 0
  medium               0
  low                  0


No problems detected!
```

Finally as @itaysk mentioned, either of them can be used to ignore the same rule:
```
#tfsec:ignore:aws-rds-enable-deletion-protection
#tfsec:ignore:AVD-AWS-0177
#tfsec:ignore:enable-deletion-protection
```

**Comment by mheiges** [comment]
To clarify, adding the ignore annotation directly in the `aws_db_instance` resource works fine. I'm trying to use the ignore annotation in a module block so I can ignore the rule in selected implementations of a shared module. If I add the ignore in the `aws_db_instance` resource in the module then it effectively becomes a global ignore.

**Comment by simar7** [comment]
> To clarify, adding the ignore annotation directly in the `aws_db_instance` resource works fine. I'm trying to use the ignore annotation in a module block so I can ignore the rule in selected implementations of a shared module. If I add the ignore in the `aws_db_instance` resource in the module then it effectively becomes a global ignore.

Right - in that case having it specified as mentioned below should do the trick.
```terraform
resource "aws_db_instance" "rds_instance" {
  name      = "db"
  deletion_protection = false #tfsec:ignore:AVD-AWS-0177
}```

**Comment by mheiges** [comment]
> To clarify, adding the ignore annotation directly in the `aws_db_instance` resource works fine. I'm trying to use the ignore annotation in a module block so I can ignore the rule in selected implementations of a shared module. If I add the ignore in the `aws_db_instance` resource in the module then it effectively becomes a global ignore.

For example, I have a shared module `modules/rds` with

```
resource "aws_db_instance" "rds" {
  deletion_protection = var.deletion_protection
```

In implementation "testing" of that shared module, I want to ignore the rule

```
module "testing" {
  source = "modules/rds"
  deletion_protection = false # tfsec:ignore:aws-rds-enable-deletion-protection
}
```

In implementation "production" of that shared module, I want the warning

```
module "production" {
  source = "modules/rds"
  deletion_protection = false # tfsec should warn if this is not enabled
}
```


If I put the ignore in the shared module's resource block

```
resource "aws_db_instance" "rds" {
  deletion_protection = var.deletion_protection # tfsec:ignore:aws-rds-enable-deletion-protection
```

it becomes a global ignore for the shared module. That is, the "production" implementation does not give a warning like it should.

**Comment by sms-astanley** [comment]
> same with `Result #1 MEDIUM Instance does not have IAM Authentication enabled `
> 
> does not give an ignorable ID, but
> 
> ```
>  Rego Package builtin.aws.rds.aws0176
>      Rego Rule deny
> ```

This bug seems to have been introduced in v1.28.1  Not seeing this issue in v1.28.0.

https://github.com/aquasecurity/tfsec/pull/1932

**Comment by khalilkasmiheyjobs** [comment]
After struggeling for a couple of hours with this issue, i turned out the simple fix would be to downgrade the `tfsec` version from `1.28.1` to `1.28.0`. 
But why tho? 
the `tfsec` version `1.28.0` was using the version `v0.76.0` of `[defsec](https://github.com/aquasecurity/defsec)` while `tfsec` version `1.28.1` is using version `v0.82.2` of `defsec`.
It's worth mentioning that AWS rego scanning support was added `defsec` in version `[v0.77.0](https://github.com/aquasecurity/defsec/releases/tag/v0.77.0)`.
since this change happened, `tfsec` version `1.28.1` was by default evaluating rego rules including `aws.0177` and `aws.0176`

Even though i tried ignoring these two rules with what has been mentioned above  

```
#tfsec:ignore:aws-rds-enable-deletion-protection
#tfsec:ignore:AVD-AWS-0177
#tfsec:ignore:enable-deletion-protection
```

It didn't work. ALSO there is no `tfsec` rule for `enable-deletion-protection` sooooo there's that !

**Comment by seanturner026** [comment]
Still a bug, not stale

**Comment by davidjeddy** [comment]
Ran into this as well. Using a RDS module from a vendor, tfsec invoked via `tfsec . --concise-output --exclude-downloaded-modules --no-color`.

**Comment by khalilkasmiheyjobs** [comment]
> downgrade the `tfsec` version from `1.28.1` to `1.28.0`

did you try to downgrade the tfsec version from 1.28.1 to 1.28.0

**Comment by areg-gareginyan-im** [comment]
> > downgrade the `tfsec` version from `1.28.1` to `1.28.0`
> 
> did you try to downgrade the tfsec version from 1.28.1 to 1.28.0

Looks like its not available on `brew`, I'll try to find my way around that and let you know. Thank you for pointing that out!

**Comment by adhish2001** [comment]
> Same issue on Apple M1 using TFSec 1.28.1. I have found a workaround without downgrading.
> 
> In `.tfsec-config.yml` specify:
> 
> ```
> ---
> exclude:
>   # Add IDs of checks to ignore them
>   - aws-rds-enable-deletion-protection
> ```
> 
> And then run TFSec using that config file. If using `terraform_tfsec` precommit hook:
> 
> ```
>       - id: terraform_tfsec
>         files: ^.*.tf$
>         # Configure tfsec by creating and updating the config file below.
>         args: [--args=--config-file=__GIT_WORKING_DIR__/.tfsec-config.yml]
> ```
> 
> Note that this will exclude the check on all resources. It is thus not a proper resolution to the issue but an optional workaround.

Used this work around. The bug exists for AVD-AWS-0177 and AVD-AWS-0176. Had to go on their aqau vulnerabilities site to find the ids. It doesn't look like they updated it for AVD-AWS-0176. 

Created a config.yml and added 
`exclude:
  - aws-rds-enable-deletion-protection
  - aws-rds-enable-iam-auth
  - AVD-AWS-0177
  - AVD-AWS-0176`

**Comment by simar7** [comment]
We've improved the trivyignore capabilities in the latest release of trivy, you can find more details here https://aquasecurity.github.io/trivy/v0.45/docs/configuration/filtering/#trivyignoreyaml

**Comment by whyman10x** [comment]
Is anyone planning on a tfsec fork to fix stuff like this? Just silly to have to pin an old version, and have the current version broken.

**Comment by itaysk** [comment]
@whyman10x tfsec merged into Trivy and it has been being maintained and evolved there https://github.com/aquasecurity/trivy
