### ISSUE TITLE
bug: `--exclude-downloaded-modules` doesn't exclude all modules in v1.28.1

### ISSUE THREAD

**Issue by syphernl** [aquasecurity/tfsec#1936]
**Describe the bug**

After upgrading tfsec to v1.28.1 we're seeing that one of our "downloaded modules" is still being checked. 

```shell
❯ docker run --rm -it -v "$(pwd):/src" aquasec/tfsec:v1.28.1 /src --exclude-downloaded-modules

WARNING: A tfvars file was found but not automatically used. Did you mean to specify the --tfvars-file flag?

Result #1 MEDIUM Instance does not have IAM Authentication enabled 
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  ../git::https:/github.com/cloudposse/terraform-aws-rds.git?ref=0.38.6/src/.terraform/modules/rds_postgres_db/main.tf:72
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Failed to render code: failed to read file from result filesystem (&extrafs.filesystem{root:"/", underlying:"/"}): open //git::https:/github.com/cloudposse/terraform-aws-rds.git?ref=0.38.6/src/.terraform/modules/rds_postgres_db/main.tf: no such file or directory────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Rego Package builtin.aws.rds.aws0176
     Rego Rule deny
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

In version v1.28.0 this is working fine:
```shell
❯ docker run --rm -it -v "$(pwd):/src" aquasec/tfsec:v1.28.0 /src --exclude-downloaded-modules

WARNING: A tfvars file was found but not automatically used. Did you mean to specify the --tfvars-file flag?
  timings
  ──────────────────────────────────────────
  disk i/o             18.177334ms
  parsing              24.821444587s
  adaptation           73.08141ms
  checks               560.786489ms
  total                25.47348982s

  counts
  ──────────────────────────────────────────
  modules downloaded   9
  modules processed    175
  blocks processed     8039
  files read           897

  results
  ──────────────────────────────────────────
  passed               11
  ignored              219
  critical             0
  high                 0
  medium               0
  low                  0


No problems detected!

```

**To Reproduce**

1. Run tfsec v1.28.1 on code with external module with the `--exclude-downloaded-modules` flag
2. See error
3. Run tfsec v1.28.0 on code with external module with the `--exclude-downloaded-modules` flag
4. See no problems detected

**Expected behavior**

**Output of your tfsec command with --debug flag**

**System Info**

 - tfsec version: `1.28.1`
 - terraform version: `1.3.3`
 - OS: `Ubuntu 22.10` & `Alpine 3.16`

**Example Code**
```hcl
module "rds_postgres_db" {
  source    = "git::https://github.com/cloudposse/terraform-aws-rds.git?ref=0.38.6"
  name      = "db"
}
```

**Additional context**

**Comment by chtakahashi** [comment]
seeing the same behavior on 1.28.1

**Comment by syphernl** [comment]
Still relevant.

**Comment by sblack4** [comment]
[This only affects the latest release, v1.28.1 ](https://github.com/aquasecurity/tfsec/issues/1935#issuecomment-1364343851)

I was able to work-around it by uninstalling and installing v1.28.0

```
brew uninstall tfsec
curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | TFSEC_VERSION=v1.28.0 bash
```

**Comment by syphernl** [comment]
This is still relevant.

**Comment by yury-kustov-improvado** [comment]
This is still relevant.

**Comment by syphernl** [comment]
A workaround could be:

```shell
tfsec --exclude-path ".terraform"
```

**Comment by nikpivkin** [comment]
Hi @syphernl !

You can use Trivy to scan misconfigurations, since tfsec is [now](https://github.com/aquasecurity/tfsec/discussions/1994) part of Trivy.

Trivy report for the above code:
```bash
trivy config main.tf -d
2023-08-11T00:56:04.330+0700    DEBUG   Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
2023-08-11T00:56:04.378+0700    DEBUG   cache dir:  /Users/tososomaru/Library/Caches/trivy
2023-08-11T00:56:04.378+0700    DEBUG   Module dir: /Users/tososomaru/.trivy/modules
2023-08-11T00:56:04.378+0700    INFO    Misconfiguration scanning is enabled
2023-08-11T00:56:04.378+0700    DEBUG   Policies successfully loaded from disk
2023-08-11T00:56:04.403+0700    DEBUG   Walk the file tree rooted at 'main.tf' in parallel
2023-08-11T00:56:04.403+0700    DEBUG   Scanning Terraform files for misconfigurations...
2023-08-11T00:56:08.463+0700    DEBUG   OS is not detected.
2023-08-11T00:56:08.463+0700    INFO    Detected config files: 2
2023-08-11T00:56:08.463+0700    DEBUG   Scanned config file: .
2023-08-11T00:56:08.463+0700    DEBUG   Scanned config file: git::https:/github.com/cloudposse/terraform-aws-rds.git?ref=0.38.6/main.tf

git::https:/github.com/cloudposse/terraform-aws-rds.git?ref=0.38.6/main.tf (terraform)
======================================================================================
Tests: 12 (SUCCESSES: 8, FAILURES: 4, EXCEPTIONS: 0)
Failures: 4 (UNKNOWN: 0, LOW: 1, MEDIUM: 2, HIGH: 0, CRITICAL: 1)

MEDIUM: Instance has very low backup retention period.
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
RDS backup retention for clusters defaults to 1 day, this may not be enough to identify and respond to an issue. Backup retention periods should be set to a period that is a balance on cost and limiting risk.

See https://avd.aquasec.com/misconfig/avd-aws-0077
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 git::https:/github.com/cloudposse/terraform-aws-rds.git?ref=0.38.6/main.tf:64
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  22   resource "aws_db_instance" "default" {
  ..   
  64 [   backup_retention_period     = var.backup_retention_period
  ..   
  93   }
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


CRITICAL: Security group rule allows egress to multiple public internet addresses.
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Opening up ports to connect out to the public internet is generally to be avoided. You should restrict access to IP addresses or ranges that are explicitly required where possible.

See https://avd.aquasec.com/misconfig/avd-aws-0104
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 git::https:/github.com/cloudposse/terraform-aws-rds.git?ref=0.38.6/main.tf:196
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 189   resource "aws_security_group_rule" "egress" {
 190     count             = module.this.enabled ? 1 : 0
 191     description       = "Allow all egress traffic"
 192     type              = "egress"
 193     from_port         = 0
 194     to_port           = 0
 195     protocol          = "-1"
 196 [   cidr_blocks       = ["0.0.0.0/0"]
 197     security_group_id = join("", aws_security_group.default.*.id)
 198   }
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


LOW: Instance does not have performance insights enabled.
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Enabling Performance insights allows for greater depth in monitoring data.

For example, information about active sessions could help diagose a compromise or assist in the investigation

See https://avd.aquasec.com/misconfig/avd-aws-0133
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 git::https:/github.com/cloudposse/terraform-aws-rds.git?ref=0.38.6/main.tf:74
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  22   resource "aws_db_instance" "default" {
  ..   
  74 [   performance_insights_enabled          = var.performance_insights_enabled
  ..   
  93   }
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────


MEDIUM: Instance does not have Deletion Protection enabled
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Ensure deletion protection is enabled for RDS database instances.

See https://avd.aquasec.com/misconfig/n/a
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 git::https:/github.com/cloudposse/terraform-aws-rds.git?ref=0.38.6/main.tf:67
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  22   resource "aws_db_instance" "default" {
  ..   
  67 [   deletion_protection         = var.deletion_protection
  ..   
  93   }
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

Regards,
Nikita P.

/cc @simar7

**Comment by simar7** [comment]
> Hi @syphernl !
> 
> You can use Trivy to scan misconfigurations, since tfsec is [now](https://github.com/aquasecurity/tfsec/discussions/1994) part of Trivy.
> 
> Trivy report for the above code:
> 
> ```shell
> trivy config main.tf -d
> 2023-08-11T00:56:04.330+0700    DEBUG   Severities: ["UNKNOWN" "LOW" "MEDIUM" "HIGH" "CRITICAL"]
> 2023-08-11T00:56:04.378+0700    DEBUG   cache dir:  /Users/tososomaru/Library/Caches/trivy
> 2023-08-11T00:56:04.378+0700    DEBUG   Module dir: /Users/tososomaru/.trivy/modules
> 2023-08-11T00:56:04.378+0700    INFO    Misconfiguration scanning is enabled
> 2023-08-11T00:56:04.378+0700    DEBUG   Policies successfully loaded from disk
> 2023-08-11T00:56:04.403+0700    DEBUG   Walk the file tree rooted at 'main.tf' in parallel
> 2023-08-11T00:56:04.403+0700    DEBUG   Scanning Terraform files for misconfigurations...
> 2023-08-11T00:56:08.463+0700    DEBUG   OS is not detected.
> 2023-08-11T00:56:08.463+0700    INFO    Detected config files: 2
> 2023-08-11T00:56:08.463+0700    DEBUG   Scanned config file: .
> 2023-08-11T00:56:08.463+0700    DEBUG   Scanned config file: git::https:/github.com/cloudposse/terraform-aws-rds.git?ref=0.38.6/main.tf
> 
> git::https:/github.com/cloudposse/terraform-aws-rds.git?ref=0.38.6/main.tf (terraform)
> ======================================================================================
> Tests: 12 (SUCCESSES: 8, FAILURES: 4, EXCEPTIONS: 0)
> Failures: 4 (UNKNOWN: 0, LOW: 1, MEDIUM: 2, HIGH: 0, CRITICAL: 1)
> 
> MEDIUM: Instance has very low backup retention period.
> ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
> RDS backup retention for clusters defaults to 1 day, this may not be enough to identify and respond to an issue. Backup retention periods should be set to a period that is a balance on cost and limiting risk.
> 
> See https://avd.aquasec.com/misconfig/avd-aws-0077
> ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>  git::https:/github.com/cloudposse/terraform-aws-rds.git?ref=0.38.6/main.tf:64
> ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>   22   resource "aws_db_instance" "default" {
>   ..   
>   64 [   backup_retention_period     = var.backup_retention_period
>   ..   
>   93   }
> ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
> 
> CRITICAL: Security group rule allows egress to multiple public internet addresses.
> ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
> Opening up ports to connect out to the public internet is generally to be avoided. You should restrict access to IP addresses or ranges that are explicitly required where possible.
> 
> See https://avd.aquasec.com/misconfig/avd-aws-0104
> ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>  git::https:/github.com/cloudposse/terraform-aws-rds.git?ref=0.38.6/main.tf:196
> ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>  189   resource "aws_security_group_rule" "egress" {
>  190     count             = module.this.enabled ? 1 : 0
>  191     description       = "Allow all egress traffic"
>  192     type              = "egress"
>  193     from_port         = 0
>  194     to_port           = 0
>  195     protocol          = "-1"
>  196 [   cidr_blocks       = ["0.0.0.0/0"]
>  197     security_group_id = join("", aws_security_group.default.*.id)
>  198   }
> ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
> 
> LOW: Instance does not have performance insights enabled.
> ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
> Enabling Performance insights allows for greater depth in monitoring data.
> 
> For example, information about active sessions could help diagose a compromise or assist in the investigation
> 
> See https://avd.aquasec.com/misconfig/avd-aws-0133
> ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>  git::https:/github.com/cloudposse/terraform-aws-rds.git?ref=0.38.6/main.tf:74
> ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>   22   resource "aws_db_instance" "default" {
>   ..   
>   74 [   performance_insights_enabled          = var.performance_insights_enabled
>   ..   
>   93   }
> ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> 
> 
> MEDIUM: Instance does not have Deletion Protection enabled
> ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
> Ensure deletion protection is enabled for RDS database instances.
> 
> See https://avd.aquasec.com/misconfig/n/a
> ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>  git::https:/github.com/cloudposse/terraform-aws-rds.git?ref=0.38.6/main.tf:67
> ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>   22   resource "aws_db_instance" "default" {
>   ..   
>   67 [   deletion_protection         = var.deletion_protection
>   ..   
>   93   }
> ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> ```
> 
> Regards, Nikita P.
> 
> /cc @simar7

In addition to what Nikita has said, you can also read on how to ignore certain directories as such https://aquasecurity.github.io/trivy/v0.44/docs/configuration/skipping/#skip-files
