### ISSUE TITLE
Ignore rule for workspace by wildcard feat: 

### ISSUE THREAD

**Issue by armanbaghajyan** [aquasecurity/tfsec#1937]
**Is your feature request related to a problem? Please describe. **
I was able to setup ignore rules per workspace, but I should specify full name of workspace I have different workspaces related different apps and environments

**Describe the solution you'd like**
It would be good to have ability to setup workspace ignore rule with wildcard.
example:  
`tfsec:ignore:AWS006:exp:2221-01-02 #tfsec:ignore:AWS018:ws:development-*`

**Comment by owenrumney** [comment]
I think this makes sens and should be easy enough to resolve

**Comment by simar7** [comment]
Thanks for the idea, we've moved our efforts to Trivy so we'll be tracking this there https://github.com/aquasecurity/trivy/issues/5120
