### ISSUE TITLE
bug: VPC flow logs documentation link is broken

### ISSUE THREAD

**Issue by Octogonapus** [aquasecurity/tfsec#1940]
```
          ID aws-ec2-require-vpc-flow-logs-for-all-vpcs
      Impact Without VPC flow logs, you risk not having enough information about network traffic flow to investigate incidents or identify security issues.
  Resolution Enable flow logs for VPC

  More Information
  - https://aquasecurity.github.io/tfsec/v1.28.1/checks/aws/ec2/require-vpc-flow-logs-for-all-vpcs/
```

That link lands you on a 404 page.

**Comment by Octogonapus** [comment]
The link is still broken

**Comment by Octogonapus** [comment]
The link is still broken. Please remove stalebot.

**Comment by brsolomon-deloitte** [comment]
Go away stalebot.

**Comment by taskooh** [comment]
I also have same issue.

**Comment by brsolomon-deloitte** [comment]
> Same issue here, is this being looked at?

[Probably not](https://github.com/aquasecurity/tfsec/issues/2047).

**Comment by simar7** [comment]
Our efforts have moved to Trivy and we now have AVD that documents all such misconfigurations in much more detail. You can find an example here https://avd.aquasec.com/misconfig/aws/ec2/vpc-flow-logs-enabled/
