### ISSUE TITLE
Add URI handler to use Github PAT to download `--config-file-url` for a private github repo

### ISSUE THREAD

**Issue by nitrocode** [aquasecurity/tfsec#1943]
I'd like to re-use the config file from a private repo. How can I do that with `--config-file-url` ? Is there a way I can pass in my PAT ?

```sh
export GITHUB_TOKEN=$(gh config get -h github.com oauth_token)
```

Is there a way to use an `ssh` url ?

https://superuser.com/a/1687399

Doing something like this would be ideal because then it would re-use my current ssh configuration instead of a PAT

```
tfsec --config-file-url ssh://git@github.com/foo/bar
```

**Comment by owenrumney** [comment]
Hey @nitrocode - only http[s] is supported for config download https://github.com/aquasecurity/tfsec/blob/master/internal/app/tfsec/cmd/flags.go#L318 

So you could use something like 

```
tfsec --config-file-url https://raw.githubusercontent.com/aquasecurity/tfsec/master/_examples/with_config_overrides/.tfsec/config.yml
```

**Comment by nitrocode** [comment]
Are you saying that it is not possible to download a remote config file from a private GitHub repo?

Perhaps then this question can serve as a feature request for an ssh handler.

**Comment by nitrocode** [comment]
Let's make it unstale then :D

**Comment by nitrocode** [comment]
Let's make it unstale then :D

**Comment by nitrocode** [comment]
Unstale

**Comment by simar7** [comment]
Our efforts have moved to Trivy. Please file a discussion in the Trivy repo if you see fit.
