### ISSUE TITLE
tfsec does not see variables in the modules

### ISSUE THREAD

**Issue by igimot** [aquasecurity/tfsec#1948]
We use our repo with custom google modules for terraform. We set default variables in modules. But when we run tfsec, tfsec doesn't see the variables and we have warning. But if we set variables in the main project all is fine and we don't see warning. For us, it is not convenient and is a problem. How can we force tfsec to read variables from the modules?

**Comment by mad-it** [comment]
I have the same issue. For example using the following module: https://github.com/terraform-aws-modules/terraform-aws-s3-bucket with the most basic setup like the following snippet gives S3 bucket level warnings which are are all blocked by the module variables.:
```tf
module "s3_bucket" {
  source  = "terraform-aws-modules/s3-bucket/aws"
  version = "3.6.0"

  bucket = var.bucket_name

  # S3 bucket-level Public Access Block configuration
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true

  acl = "private"
}
```

I am currently forced to add the following on top of the module because its not interpolating correctly:
```  # tfsec:ignore:aws-s3-block-public-acls
  # tfsec:ignore:aws-s3-block-public-policy
  # tfsec:ignore:aws-s3-ignore-public-acls
  # tfsec:ignore:aws-s3-no-public-buckets
  # tfsec:ignore:aws-s3-specify-public-access-block
```

**Comment by Joerg-L** [comment]
we are observing the same issue with module code.
Our postgres module has some default configuration parameter defined, which are not recognized by tfsec

```
locals {
  pgconfig_default = {
    "log_connections" = "on"
    "log_checkpoints" = "on"
    "connection_throttling" = "on"
  }
  pgconfig = merge( local.pgconfig_default, var.config_settings )
}

resource "azurerm_postgresql_configuration" "postgresql_configuration" {
  for_each = local.pgconfig
  name                = each.key
  resource_group_name = var.resource_group_name
  server_name         = azurerm_postgresql_server.postgresql_server.name
  value               = each.value
}
```

Wrong failed tests are

- Ensure server parameter 'connection_throttling' is set to 'ON' for PostgreSQL Database Server
- Ensure server parameter 'log_checkpoints' is set to 'ON' for PostgreSQL Database Server
- Ensure server parameter 'log_connections' is set to 'ON' for PostgreSQL Database Server

**Comment by Joerg-L** [comment]
So, how can this be fixed?

**Comment by mitchmartinkanso** [comment]
This issue is still ongoing and prevents additional problems when trying to use a wrapper around the community modules as tfsec doesn't see the exceptions.

**Comment by nikpivkin** [comment]
Hi @igimot !

Our efforts have moved to Trivy. 

It seems I can't reproduce the problem using Trivy.

Config:
```tf
variable "versioning" {
  type = bool
  default = true
}

resource "aws_s3_bucket" "this" {
  versioning {
    enabled = var.versioning
  }
}
```

Trivy output:
```
trivy config . | grep "versioning enabled"
2023-09-02T16:44:43.311+0700    INFO    Misconfiguration scanning is enabled
2023-09-02T16:44:43.664+0700    INFO    Detected config files: 2
```

/cc @simar7
