### ISSUE TITLE
feat:  I want tfsec to tests the value of the aws s3 bucket policy setting "aws:SecureTransport".

### ISSUE THREAD

**Issue by piroz** [aquasecurity/tfsec#1950]
**Does your feature request relate to a problem? Please describe it.** 

I want tfsec to tests the value of the aws s3 bucket policy setting "aws:SecureTransport".

Because this is the setting [mentioned](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-s3-5) in the AWS Foundational Security Best Practices.

**Describe the solution you want** 
tfsec tests if a policy exists to deny non-secure transports in the aws_s3_bucket_policy resource.

**Comment by simar7** [comment]
hi it seems like you want to add a new policy to tfsec. We've moved our efforts to Trivy, you can start a new discussion in the Trivy repo regarding this and if you'd wish submit us a PR with this new policy. We'd be happy to review it.
