### ISSUE TITLE
bug: Pinned terraform reusable modules not visible by tfsec

### ISSUE THREAD

**Issue by wenqiglantz** [aquasecurity/tfsec#1954]
**Describe the bug**
Hi, I have an app calling a set of reusable terraform modules located in a different internal github repo.  I originally had the source defined as the following:
```
module "cluster_alb" {
  source = "github.com/<MY-ORG>/<MY-REPO>/terraform/modules/ecs/cluster_alb"
...
}
```
However, when I ran tflint, it failed, complaining that the terraform module needs to be pinned. See error below:
![image](https://user-images.githubusercontent.com/13189654/204650718-b1a2a6ee-9c22-40f3-9580-e8cb1af0c463.png)

I then revised that source line to be pinned, like this:

```
module "cluster_alb" {
  source = "github.com/<MY-ORG>/<MY-REPO>//terraform/modules/ecs/cluster_alb?ref=latest"
...
}
```

Now tflint passes fine!  But I notice when I ran tfsec on command line with that pinned terraform module, it returned 0 problem found.  See screenshot below:
![image](https://user-images.githubusercontent.com/13189654/204652133-77a7a263-3e3a-437c-b2eb-a367f5d04644.png)

However, if I revert my pinned terraform module to the original line (without being pinned with "?ref=latest"), my tfscan result returned the following (only showing the last portion of the result as there are many issues found):
![image](https://user-images.githubusercontent.com/13189654/204652639-61e6f349-dc57-46dd-b408-e74ff89b9a6f.png)

My question is why tfsec doesn't seem to recognize the pinned terraform module?  

**To Reproduce**
My app is in a private repo, so I cannot share the details here to replicate.  But I am providing the output from 'tfsec --debug' in the attachment, please review details there.

**Expected behavior**
tfsec should be able to recognize the pinned terraform module located in a remote internal github repo.

**Output of your tfsec command with --debug flag**
Please see attached file for detailed output.

**System Info**

 - tfsec version: `v1.22.1`
 - terraform version: `v1.2.8`
 - OS: `windows 10 enterprise`

**Example Code**

**Additional context**

[tfsec-debug.txt](https://github.com/aquasecurity/tfsec/files/10117605/tfsec-debug.txt)

**Comment by wenqiglantz-agi** [comment]
I am still waiting for tfsec team to respond to this issue.  Please don't close it.

**Comment by wenqiglantz** [comment]
Please remove stale label.  I am still waiting to hear from tfsec team regarding this issue.

**Comment by owenrumney** [comment]
this looks like its a problem in the module resolution not handling the explicit version. That is actually in https://github.com/aquasecurity/defsec so I'll get it transferred over there and work on it from there

**Comment by nikpivkin** [comment]
Hi @wenqiglantz !

I opened the [issue](https://github.com/aquasecurity/trivy/issues/5007) in Trivy.

/cc @simar7

**Comment by simar7** [comment]
Tracking here https://github.com/aquasecurity/trivy/issues/5007
