### ISSUE TITLE
bug: SARIF URI scheme "git" did not match the checkout URI scheme "file"

### ISSUE THREAD

**Issue by DavidSpek** [aquasecurity/tfsec#1955]
Related to: https://github.com/aquasecurity/tfsec/issues/1811
**Describe the bug**
When using Trivy to scan IaC code that is using the [GKE workload identity submodules](https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/latest/submodules/workload-identity), the following error appears in the GitHub action trying to upload the results:

```console
Run github/codeql-action/upload-sarif@v2
Uploading results
Waiting for processing to finish
  Analysis upload status is pending.
  Analysis upload status is failed.
  Error: Code Scanning could not process the submitted SARIF file:
  SARIF URI scheme "git" did not match the checkout URI scheme "file"
  Error: Code Scanning could not process the submitted SARIF file:
  SARIF URI scheme "git" did not match the checkout URI scheme "file"
      at Object.waitForProcessing (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:307:[19](https://github.com/pluralsh/plural-artifacts/actions/runs/3584609309/jobs/6031511497#step:5:21))
      at async run (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:53:13)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:68:9)
```

The sarif result in question looks like this:

```json
{
          "ruleId": "AVD-GCP-0007",
          "ruleIndex": 0,
          "level": "error",
          "message": {
            "text": "Artifact: git::https:/github.com/terraform-google-modules/terraform-google-kubernetes-engine?ref=v24.0.0/modules/workload-identity/main.tf\nType: terraform\nVulnerability AVD-GCP-0007\nSeverity: HIGH\nMessage: Service account is granted a privileged role.\nLink: [AVD-GCP-0007](https://avd.aquasec.com/misconfig/avd-gcp-0007)"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "git::https:/github.com/terraform-google-modules/terraform-google-kubernetes-engine?ref=v24.0.0/modules/workload-identity/main.tf",
                  "uriBaseId": "ROOTPATH"
                },
                "region": {
                  "startLine": 89,
                  "startColumn": 1,
                  "endLine": 89,
                  "endColumn": 1
                }
              },
              "message": {
                "text": "git::https:/github.com/terraform-google-modules/terraform-google-kubernetes-engine?ref=v24.0.0/modules/workload-identity/main.tf"
              }
            }
          ]
        }
```

The code we are seeing this issue in can be found [here](https://github.com/pluralsh/plural-artifacts/blob/main/dagster/terraform/gcp/main.tf#L13).

**To Reproduce**
1. Create a terraform file and reference a submodule ([see here](https://github.com/pluralsh/plural-artifacts/blob/main/dagster/terraform/gcp)).
2. Run `trivy fs --security-checks vuln,secret,config --format sarif . > sarif.json`
3. Open the `sarif.json` and search for ` "uri": "git::https:`

**System Info**
GitHub action.

**Example Code**
[See here](https://github.com/pluralsh/plural-artifacts/blob/main/dagster/terraform/gcp)

**Additional context**

**Comment by MaciejSzatkowski** [comment]
We hit same issue while scanning Terraform code with remote modules references - SARIF file cannot be uploaded (repo details obfuscated):
`Run github/codeql-action/upload-sarif@v[2](https://github.com/xxx/yyy/actions/runs/1234/jobs/5678#step:6:2)
  with:
    sarif_file: trivy-results.sarif
    checkout_path: /home/runner/work/xxx/yyy
    token: ***
    matrix: null
    wait-for-processing: true
Uploading results
  Processing sarif files: ["trivy-results.sarif"]
  Uploading results
  Successfully uploaded results
Waiting for processing to finish
  Analysis upload status is pending.
  Analysis upload status is failed.
Error: Code Scanning could not process the submitted SARIF file:
SARIF URI scheme "git" did not match the checkout URI scheme "file", SARIF URI scheme "git" did not match the checkout URI scheme "file"
Error: Code Scanning could not process the submitted SARIF file:
SARIF URI scheme "git" did not match the checkout URI scheme "file", SARIF URI scheme "git" did not match the checkout URI scheme "file"
    at Object.waitForProcessing (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:[3](https://github.com/xxx/yyy/actions/runs/1234/jobs/5678#step:6:3)28:23)
    at async run (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:[5](https://github.com/xxx/yyy/actions/runs/1234/jobs/5678#step:6:5)5:13)
    at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:[7](https://github.com/xxx/yyy/actions/runs/1234/jobs/5678#step:6:7)0:[9](https://github.com/xxx/yyy/actions/runs/1234/jobs/5678#step:6:10))`

Trivy v0.37.2 was used:
`Status: Downloaded newer image for ghcr.io/aquasecurity/trivy:0.37.2`

**Comment by lwa144** [comment]
got the same error:
Code Scanning could not process the submitted SARIF file:
SARIF URI scheme "alcl-xxl-job" did not match the checkout URI scheme "file",...

Could you help?

**Comment by amar-mandai** [comment]
Any Updates on this. Hit the same issue while scanning terraform code.

**Comment by nikpivkin** [comment]
Hi @DavidSpek !
I opened the [issue](https://github.com/aquasecurity/trivy/issues/5003) in Trivy.

/cc @simar7

**Comment by simar7** [comment]
Closing and tracking with https://github.com/aquasecurity/trivy/issues/5003
