### ISSUE TITLE
feat: Allow configuration with environment variables in addition to flags

### ISSUE THREAD

**Issue by itspngu** [aquasecurity/tfsec#1956]
**Is your feature request related to a problem? Please describe.**

Specifying non-standard config file locations, output options, etc. is currently possible using command line arguments, e.g. `tfsec . --config-file=my-tfsec.yaml`. While this is fine in CI or for quick one-off commands, it can get unwieldy quickly if you're trying to use the same set of default options across systems/repos/use-cases.

**Describe the solution you'd like**
Ideally, everything that needs to be configured using command line arguments could also be configured using environment variables, e.g.: `TFSEC_CONFIG_FILE=my-tfsec.yaml tfsec .`. For starters, basic options that are often changed, would suffice - mostly the config file location and output options such as `--debug` or `--no-color`, as far as I'm concerned.

**Describe alternatives you've considered**

Wrapping `tfsec` with a shell script that is distributed within our org in some manner. Not ideal.

**Additional context**

This is a fairly common way to configure tooling in ops land, especially for HashiCorp products (which I'm aware `tfsec` is not). I'd  consider it a valuable enhancement and would be happy to work on a basic implementation if needed.

**Comment by owenrumney** [comment]
This makes sense and I think it can be fairly easily achieved using the cobra library already in use

**Comment by nitrocode** [comment]
Yes, this would be great. I think with cobra, you'll have to integrate viper (same github author).

This is how atlantis sets it up.

```go
	// Configure viper to accept env vars prefixed with ATLANTIS_ that can be
	// used instead of flags.
	s.Viper.SetEnvPrefix("ATLANTIS")
	s.Viper.SetEnvKeyReplacer(strings.NewReplacer("-", "_"))
	s.Viper.AutomaticEnv()
	s.Viper.SetTypeByDefaultValue(true)

	c.SetUsageTemplate(usageTmpl(stringFlags, intFlags, boolFlags))
	// If a user passes in an invalid flag, tell them what the flag was.
	c.SetFlagErrorFunc(func(c *cobra.Command, err error) error {
		s.printErr(err)
		return err
	})
```

and then binds each flag

```go
	// Set string flags.
	for name, f := range stringFlags {
		usage := f.description
		if f.defaultValue != "" {
			usage = fmt.Sprintf("%s (default %q)", usage, f.defaultValue)
		}
		c.Flags().String(name, "", usage+"\n")
		s.Viper.BindPFlag(name, c.Flags().Lookup(name)) // nolint: errcheck
		if f.hidden {
			c.Flags().MarkHidden(name) // nolint: errcheck
		}
	}
```

See https://github.com/runatlantis/atlantis/blob/bddbb88620d94b8b4f52997e568ce9d6cfc3e882/cmd/server.go#L616

See github.com/spf13/viper
