### ISSUE TITLE
bug: resource "aws_dynamodb_table" "name" is marked with aws-dynamodb-enable-at-rest-encryption

### ISSUE THREAD

**Issue by FlaviuIuga** [aquasecurity/tfsec#1959]
**Describe the bug**
resource "aws_dynamodb_table" "name" is marked with aws-dynamodb-enable-at-rest-encryption issue even if dynamodb tables are encripted by default with AWS owned CMS key if server_side_encryption is not specified.

**To Reproduce**
1. run tfsec on aws_dynamodb_table resources 
example:
resource "aws_dynamodb_table" "name_of_table" {
  name         = "name_of_table"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "Id"

  attribute {
    name = "Id"
    type = "S"
  }

  point_in_time_recovery {
    enabled = true
  }
}

**Expected behavior**
no tfsec issue is found

**Output of your tfsec command with --debug flag**
Result #1 HIGH Table encryption is not enabled. 
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  ***/main.tf:**
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 ┌ resource "aws_dynamodb_table" "name_of_table" {
    4  │   name         = "name_of_Table"
    5  │   billing_mode = "PAY_PER_REQUEST"
    6  │   hash_key     = "Id"
    7  │
    8  │   attribute {
    9  │     name = "Id"
   10  │     type = "S"
   11  └   }

  ...
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
          ID aws-dynamodb-enable-at-rest-encryption
      Impact Data can be freely read if compromised
  Resolution Enable encryption at rest for DAX Cluster

  More Information
  - https://aquasecurity.github.io/tfsec/v1.26.3/checks/aws/dynamodb/enable-at-rest-encryption/
  - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dax_cluster#server_side_encryption

**System Info**

 - tfsec version: `v1.26.3`
 - terraform version: `v1.1.9`
 - OS: `ubuntu`

**Comment by nikpivkin** [comment]
Hi @FlaviuIuga !

I opened the [issue](https://github.com/aquasecurity/trivy/issues/5005) in Trivy.

/cc @simar7
