### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by aureliomarcoag** [aquasecurity/tfsec#1962]
**Describe the bug**
TFSec reports that IAM policy document uses sensitive action on wildcarded resource for actions that cannot be restricted to a specific ARN:
* `logs:ListLogDeliveries`
* `logs:CreateLogDelivery`
* `logs:GetLogDelivery`
* `logs:GetLogDelivery`
* `logs:UpdateLogDelivery`
* `logs:DeleteLogDelivery`

**To Reproduce**
1. Create a policy like this including actions such as `logs:CreateLogDelivery` on a wildcarded resource (for full code see *Example Code* below)
2. Run tfsec
4. The following issue is detected: `Result #1 HIGH IAM policy document uses sensitive action 'logs:ListLogDeliveries' on wildcarded resource '*'`

**Expected behavior**
tfsec shouldn't report on these since they can only be used with wildcard resources. We contacted AWS support to confirm, and they also linked the relevant documentation page: https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazoncloudwatchlogs.html#amazoncloudwatchlogs-actions-as-permissions

Quote from this page:
`The Resource types column indicates whether each action supports resource-level permissions. If there is no value for this column, you must specify all resources ("*") in the Resource element of your policy statement.`

This is indeed the case for each of the actions reported above.

**Output of your tfsec command with --debug flag**
N/A

**System Info**

 - tfsec version: `v1.28.1`
 - terraform version: `v1.3.6`
 - OS: `Manjaro Linux`

**Example Code**
```
data "aws_iam_policy_document" "test" {
  statement {
    actions = [
      "logs:ListLogDeliveries",
      "logs:CreateLogDelivery",
      "logs:GetLogDelivery",
      "logs:UpdateLogDelivery",
      "logs:DeleteLogDelivery",
    ]
    resources = [
      "*"
    ]
  }
}

resource "aws_iam_policy" "test" {
  name = "test"
  policy = data.aws_iam_policy_document.test.json
}
```

**Comment by chrfritsch** [comment]
This is a problem and should be fixed
