### ISSUE TITLE
bug: Module level ignored are not recognized when using --force-all-dirs from a parent directory

### ISSUE THREAD

**Issue by Jorge-Rodriguez** [aquasecurity/tfsec#1970]
**Describe the bug**
Warnings are still displayed when running with `--force-all-dirs` even if a module level ignore is present and the command is run from any of the parent directories of the one containing the terraform files.

**To Reproduce**
1. Use a module that would normally raise an issue
```
module "this_raises_an_issue" {
  [...]
}
```
2. Add a module level ignore
```
#tfsec:ignore:error-raised-by-module
module "this_raises_an_issue" {
  [...]
}
```
3. Run `tfsec --force-all-dirs` from the parent directory of the one holding the offending terraform files

**Expected behavior**
The ignored issue is not displayed on the tfsec report

**System Info**

 - tfsec version: `v1.28.1`
 - terraform version: `v1.3.6`
 - OS: `linux`

**Example Code**

```
#tfsec:ignore:aws-s3-enable-versioning
module "my_bucket" {
  source = "../../modules/s3-bucket"
  name = "my-bucket-name"
}
```
Minimal s3-bucket resources
```
resource "aws_s3_bucket" "this" {
  bucket = var.name
}
variable "name" {
  type = string
}
```

**Additional context**
When running `tfsec --force-all-dirs` from the directory containing the terraform files with the module level ignore, as opposed to its parent, the results are as expected and the issue is ignored.

**Comment by owenrumney** [comment]
This is expected behavior. `force-all-dirs` with run as normal, but in addition, will scan the module itself; at this time the module ignore isn't taken into account

**Comment by Jorge-Rodriguez** [comment]
@owenrumney do I understand it correctly that the ignore is both taken into account when evaluating the root module and then also ignored when evaluating the module itself?

**Comment by simar7** [comment]
Our efforts have moved to Trivy, please file a discussion there if you see fit.
