### ISSUE TITLE
question: Tfsec custom check in root of repo

### ISSUE THREAD

**Issue by userbradley** [aquasecurity/tfsec#1975]
Hey!

We're using a monorepo and at the top level of the repo I would like to have the `.tfsec` directory with the config file and custom checks.

The issue is when I navigate to any folder below that doesn't have the `.tfsec` directory in, it doesn't include the checks.

I know there is the preferred method of using ` tfsec --config-file ../../.tfsec` but this is tedious and not something I remember to do each time.

Let me know if I went wrong here at all.

**Comment by userbradley** [comment]
Still active.

**Comment by userbradley** [comment]
Still active...

**Comment by simar7** [comment]
Our efforts have moved to Trivy. Please open a discussion there if you see fit.
