### ISSUE TITLE
bug:  AKS api_server_access_profile

### ISSUE THREAD

**Issue by philwelz** [aquasecurity/tfsec#1977]
**Describe the bug**

TFsec does not recognize new `api_server_access_profile` block for `azurerm_kubernetes_cluster` resource.

**Output of your tfsec command with --debug flag**

```
Result #1 CRITICAL Cluster does not limit API access to specific IP addresses. 
─────────────────────────────────────────────────────────────────────────────────────────────────
  aks.tf:87-175
─────────────────────────────────────────────────────────────────────────────────────────────────
   87  ┌ resource "azurerm_kubernetes_cluster" "aks" {
   88  │   name                            = "aks
   ..  
─────────────────────────────────────────────────────────────────────────────────────────────────
          ID azure-container-limit-authorized-ips
      Impact Any IP can interact with the API server
  Resolution Limit the access to the API server to a limited IP range
```

**System Info**

 - tfsec version: `v1.28.1`
 - terraform version: `v1.3.7`
 - OS: `MacOs`

**Example Code**

```terraform
resource "azurerm_kubernetes_cluster" "aks" {
  name                            = "aks"

  api_server_access_profile {
    authorized_ip_ranges = local.ip_whitelist
  }
```

**Additional context**

Until the Release of AzureRM 4.0.0 the `api_server_access_profile` block and the solo option `api_server_authorized_ip_ranges` are valid. Afterwards only the block will be supported furthermore.

**Comment by MO-Ludovic-Paret** [comment]
+1 It's embarrassing to deactivate this rule until it is updated

**Comment by Eliaxie** [comment]
up, this is important, api_server_authorized_ip_ranges will be deprecated soon

**Comment by jamestrousdale** [comment]
+1, this is a serious gap. It's very bad to have to add this ignore just to future-proof our code in preparation for `api_server_authorized_ip_ranges` deprecation.

**Comment by nikpivkin** [comment]
Hi @philwelz !

tfsec is now part of trivy and I couldn't reproduce it in Trivy.

```shell
trivy config . -f json | jq '.Results[]?.Misconfigurations[]?.Title'
2023-08-17T13:14:56.357+0700    INFO    Misconfiguration scanning is enabled
2023-08-17T13:14:56.710+0700    INFO    Detected config files: 2
"Ensure AKS logging to Azure Monitoring is Configured"
"Ensure RBAC is enabled on AKS clusters"
"Ensure AKS cluster has Network Policy configured"
```

/cc @simar7
