### ISSUE TITLE
bug: install linux script sha256 checksum not working correctly 

### ISSUE THREAD

**Issue by aiell0** [aquasecurity/tfsec#1986]
**Describe the bug**
When trying to install tfsec using the install linux script, it fails with the following error:

```
=====================================
Looking up the latest version...
Downloading tfsec v1.28.1
Downloaded successfully
Validate checksum
sha256sum: unrecognixzed option `--ignore-missing`
Try `sha256sum --help` for more information.
Failed to verify checksum
```

Additionally, once this was fixed, the checksum is verified against the entire checksums txt file, which fails. There is a need to extract only the checksum you need and verify that that instead of the entire file.

**To Reproduce**
1. Run the command `curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash` on a linux machine

**Expected behavior**
```
============================================
Looking up the latest version...
Downloading tfsec v.1.28.1
Downloading tfsec-linux-amd64...
Downloaded file "tfsec-linux-amd64" successfully
Downloading tfsec-checkgen-linux-amd64...
Downloaded "tfsec-checkgen-linux-amd64" successfully
Downloading tfsec_checksums.txt...
Downloaded file "tfsec_checksums.txt" successfully
Checksum verified successfully
```

**Output of your tfsec command with --debug flag**
N/A

**System Info**

 - tfsec version: `v1.28.1`
 - terraform version: `n/a`
 - OS: `linux/amd64 and darwin`

**Example Code**
n/a

**Additional context**
None

**Comment by neilherbertuk** [comment]
I'm getting almost the same on the latest alpine, however, my error is`sha256sum: unrecognized option: quiet`

Nil

**Comment by chb0github** [comment]
I would say that, as a matter of implementation of the install script, it should:
1. use sh and not bash, since with alpine you need to add bash
2. remove (or make optional) the checksum switch, so that it can be externalized. 

Alternative is to figure out which version of checksum you have., Which is different between mac and linux for sure, and then switch-case your way to the write command and args

**Comment by aiell0** [comment]
Just for everyone's reference, https://github.com/aquasecurity/tfsec/pull/1987 was merged recently.

@chb0github I don't disagree with your suggestions, but felt that it was out of scope for the PR I had open. I don't have it in me to make the changes you're suggesting so will leave it up to someone else to tackle it :)

**Comment by adamgerhartz** [comment]
> I'm getting almost the same on the latest alpine, however, my error is`sha256sum: unrecognized option: quiet`

I was getting the same issue. I created an `install_linux.sh` inside of my `hashicorp/terraform:1.5` container and commented out the `--quiet` flag, and it worked after that.

It must be that BusyBox's version of `sha256sum` is different than GNU's version

**Comment by simar7** [comment]
Closed via https://github.com/aquasecurity/tfsec/pull/1987
