### ISSUE TITLE
bug: azure-storage-use-secure-tls-policy complains unnecessarily

### ISSUE THREAD

**Issue by tbutler-qontigo** [aquasecurity/tfsec#1991]
**Describe the bug**
azurerm now defaults to TLS1_2: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#min_tls_version

tfsec should not complain that "Storage account uses an insecure TLS version" when no version is explicitly specified and the version of azurerm being used uses TLS1_2 by default

**To Reproduce**
1.  use the azurerm provider to define a storage account and do NOT specify the min_tls_version
2. Run tfsec against the script 
3. See error

**Expected behavior**
No error is reported about the min tls version since it is already correctly TLS1_2 by default.

**Comment by tbutler-qontigo** [comment]
Switch to `trivy` :)
The maintainers are focusing there efforts on that product and I guess `tfsec` will be archived at some point.

**Comment by simar7** [comment]
This has been resolved in Trivy.
