### ISSUE TITLE
bug: SARIF outputs wrong path for nested local terraform modules

### ISSUE THREAD

**Issue by PeterBurner** [aquasecurity/tfsec#1996]
**Describe the bug**
When using locally resolved modules, the SARIF output wrongly attaches all issues to the root module import.

**Suggestion**
Please bump defsec to > v0.83.0.

**Additional context**
 - https://github.com/aquasecurity/defsec/issues/1147
 - https://github.com/aquasecurity/defsec/pull/1202

**Comment by kernle32dll** [comment]
Done via https://github.com/aquasecurity/tfsec/commit/4732a5ae4a027a75ef00a6d1a1ecff0b98679907
