### ISSUE TITLE
question: tfsec's future and ongoing maintenance

### ISSUE THREAD

**Issue by wyardley** [aquasecurity/tfsec#1997]
Is there going to be a broader announcement about [this](https://github.com/aquasecurity/tfsec/pull/1961), and will tfsec continue to be updated / maintained actively as it was before?

**Comment by tinder-tder** [comment]
check out https://github.com/aquasecurity/trivy/pull/3708/files

the current lack of support of inline ignore comments is keeping us from using trivy in our pipelines

**Comment by wyardley** [comment]
I played around with trying to get it to work yesterday, and while some things were possible to setup, I wasn't super impressed. Unless I'm missing something, it's not possible to disable the other config checks / types (see discussion link below).

Some of my complaints so far:

* It seems to find a ton of extra random stuff if it's embedded in module code (https://github.com/aquasecurity/trivy/issues/3754)
* It requires a lot of weird workarounds to handle junit output (https://github.com/aquasecurity/trivy/issues/3753)
* Doesn't support multiple output formats in the same run (https://github.com/aquasecurity/trivy/issues/720)
* It doesn't seem possible (or easy) to _just_ look at Terraform configs (https://github.com/aquasecurity/trivy/discussions/3755)

**Comment by tinder-tder** [comment]
yea its all or nothing, we have a wiz license so we may migrate to that, they have ignore support it looks like

**Comment by wyardley** [comment]
I found https://github.com/aquasecurity/tfsec/discussions/1994 as well

**Comment by tinder-tder** [comment]
trivy also doesnt look like it outputs all findings at once in some cases.  I have a module that tfsec catches 2 findings and when done with trivy it exits with 1, but if i fix it, the second finding is reported.  Also the current tfsec doc links are broken now

**Comment by itaysk** [comment]
Hi there. seems like you already found the announcement where we shared our intention to move to Trivy. about specific migration challenges, I saw you opened an issues, we'll take a look as soon as next week. hopefully we can resolve all blockers by the next release which is scheduled for end of March.

**Comment by wyardley** [comment]
In the meantime, would be great if folks could move any issues which relate to the scanning engine over to defsec.

would also hope that you would add a note to the readme and issue template, as the current announcement is not at all obvious.

**Comment by wyardley** [comment]
Even if adding new features like #1990 (which would be convenient for sure) are now frozen, would also be great if another release with security library updates, bump to latest version of defsec, etc could still go out.

From the above, it’s clear that trivy is a way off from really serving the same function, and regardless, migration is not necessarily trivial for everyone’s use cases.

**Comment by giorod3** [comment]
> trivy also doesnt look like it outputs all findings at once in some cases. I have a module that tfsec catches 2 findings and when done with trivy it exits with 1, but if i fix it, the second finding is reported. Also the current tfsec doc links are broken now

Hi @wyardley, I am working on ensuring that all features of TFsec are migrated into Trivy. Can you elaborate more on this Trivy bug.

**Comment by giorod3** [comment]
> Even if adding new features like #1990 (which would be convenient for sure) are now frozen, would also be great if another release with security library updates, bump to latest version of defsec, etc could still go out.
> 
> From the above, it’s clear that trivy is a way off from really serving the same function, and regardless, migration is not necessarily trivial for everyone’s use cases.

Hi @wyardley, we are working on merging the open PR's including upgrading libraries before we deprecate TFsec completely. As well as ensuring parity between TFsec and Trivy. Thank you for helping look over Trivy, if you have any other feedback that would be helpful as well.

**Comment by wyardley** [comment]
> Can you elaborate more on this Trivy bug.

@giorod3 that was @tinder-tder’s comment you’re responding to, I think.

**Comment by wyardley** [comment]
@giorod3 I think I've opened most of the issues for things I've noticed so far. Those were the main things that came up when I took a pass at migrating our existing stuff over. But for sure having some way to _only_ scan for terraform code, as well as smarter detection of what "files" are actually inline of configs (see #3754) -- tfsec seems to be somewhat smarter about that now, so maybe should be a different issue for that higher level issue?

Main other thoughts:
Would be great if it were made more obvious that this project is deprecated - maybe pin an issue at the top of issues, and put something at the top of the project README here.

And, it would be great if someone could comb the open issues here and move things like #1978, etc. over to defsec, as presumably they relate to the scanning engine and not to tfsec itself.

**Comment by giorod3** [comment]
> 

Hi @wyardley, I am going over the open issues now and seeing what will make our final cut of tfsec before we stop supporting. I can't promise we will fix everything but we will try to fix the most pressing issues. We are also reviewing our docs and updating them to reflect the coming changes. 

Please be patient as this will take me a few weeks. (tfsec was not actively maintained for the last few months after Liam left)

**Comment by itaysk** [comment]
closing this as requests/discussion can continue on specific issues

**Comment by wyardley** [comment]
@giorod3 Hi - any update on this?
