### ISSUE TITLE
question: Is AWS009 Default Severity accurate?

### ISSUE THREAD

**Issue by Almenon** [aquasecurity/tfsec#2001]
I'm surprised that AWS009 has a default severity of `CRITICAL`. Is this really the level it should default to? 

Personally critical for me is open *ingress* to a instance, not *egress*. One can safely have a open egress as long as ingress rules (and app/code) are secure. I could see this being a critical severity issue for certain very paranoid companies that rarely talk to the outside world, but it seems like the severity for most companies would be minor. 

https://aquasecurity.github.io/tfsec/v1.28.1/checks/aws/ec2/no-public-egress-sgr/

**Comment by simar7** [comment]
It is subjective. We think the current severity is justified.
