### ISSUE TITLE
bug: URl doesn't exists - aquasecurity.github.io/tfsec/v1.28.1/checks/google/storage/bucket-encryption-customer-key/

### ISSUE THREAD

**Issue by kborovoy** [aquasecurity/tfsec#2004]
Results # LOW Storage bucket encryption does not use a customer-managed key.
***
More Information
  -  https://aquasecurity.github.io/tfsec/v1.28.1/checks/google/storage/bucket-encryption-customer-key/

**Comment by giorod3** [comment]
Hi @kborovoy can you provide more information please

**Comment by atimofti** [comment]
The URL returns 404 : https://aquasecurity.github.io/tfsec/v1.28.1/checks/google/storage/bucket-encryption-customer-key/

**Comment by shafaypro** [comment]
Anyupdate on this?

**Comment by kborovoy** [comment]
@giorod3 @simar7

**Comment by simar7** [comment]
Our efforts have moved to Trivy. This check is now available here https://avd.aquasec.com/misconfig/google/storage/avd-gcp-0066/
