### ISSUE TITLE
question: How to use the --custom-check-url option with a GitHub repository

### ISSUE THREAD

**Issue by heriberto-mb** [aquasecurity/tfsec#2006]
@owenrumney

We have thought about having a set of checks in a GitHub repository. I'm trying to use the following command:

`tfsec terraform --exclude-downloaded-modules --custom-check-url https://github.com/Jackson-National/tfsec-custom-rules/tree/main/.tfsec`

The check runs fine locally, however, it is not picking up the check when I use **--custom-check-url**

Inside of that URL, there is a file called **tfsec_check_modules.yml** which I expected it to pick it up, but that's not the case. I will be adding more check files in that URL, 1 file per check. My idea is to define just the URL where multiple .yml files would exist.

**Comment by owenrumney** [comment]
I see that repo is blocked by IP so I'm guessing you're using enterprise github?

If you have a GitHub PAT in your env, does it work?

Might need to update the code that does the downloading to grab that and set a Bearer on the request.

I'm not working for aqua anymore I'm afraid, so I can't make any commitments about when that could happen

**Comment by heriberto-mb** [comment]
Thanks for the quick response @owenrumney

Yes, we are using an enterprise github
It works when I use the --custom-check-dir option:
tfsec terraform --exclude-downloaded-modules --custom-check-dir .tfsec

But for some reason it doesn't like the Git repository (--custom-check-url), possibly because the github format of the file. (I also tried specifying the raw format URL, but still doesn't pick it up).

Do you think it will pick up all the .yml files that contain a rule in that URL?

If you can send me an example using that URL option I would appreciate it.

**Comment by rlindooren** [comment]
_Although this is an old(er) and closed issue, perhaps the following could be useful for others that end up here while searching for the same thing._

This is how you can use a custom checks file that is part of a private repository:

```
GITHUB_TOKEN=....

CUSTOM_CHECKS_REF="main"
CUSTOM_CHECKS_URL="https://${GITHUB_TOKEN}@raw.githubusercontent.com/<YourOrg>/<YourRepo>/${CUSTOM_CHECKS_REF}/tfsec/custom_tfchecks.yaml"

tfsec --custom-check-url="${CUSTOM_CHECKS_URL}" .
```

In my case I use a single file that contains all checks.
Not sure if you can refer to a directory, my feeling is that this is not supported but haven't tried it.
