### ISSUE TITLE
feat: Add module location details to the location column in markdown output

### ISSUE THREAD

**Issue by murukesh-mohanan-paidy** [aquasecurity/tfsec#2014]
**Is your feature request related to a problem? Please describe.**

Currently, the markdown output shows the final location of the problem (e.g., in  `some/module/file.tf:10-15`), but doesn't say anything about the place where the module is instantiated. This results in *identical* output rows in the Markdown table for each instance of a problematic module. Compare the outputs:

<details><summary>Plain <code>tfsec</code></summary>

```
% tfsec

Results #1-20 HIGH Repository does not have vulnerability alerts enabled, (20 similar results)
───────────────────────────────────────────────
  githubrepo/main.tf:1-26
   via repos.tf:58-64 (module.some-repo)
───────────────────────────────────────────────
    1  ┌ resource "github_repository" "default" {
    2  │   name        = var.repository_name
    3  │   description = var.description
    4  │
    5  │   has_downloads = false
    6  └   has_issues    = false
   ..
───────────────────────────────────────────────
  Individual Causes
  - githubrepo/main.tf:9-15 (module.repo-one)
  - githubrepo/main.tf:17-26 (module.repo-two)
  - githubrepo/main.tf:28-38 (module.another-repo)
  - githubrepo/main.tf:26-37 (module.a-fourth-repo)
  - ...
 ```
</details>

<details><summary><code>tfsec --format markdown</code></summary>

# [tfsec] Results
## Failed: 20 issue(s)
| # | ID | Severity | Title | Location | Description |
|---|----|----------|-------|----------|-------------|
|  1 | `github-repositories-enable_vulnerability_alerts` | *HIGH* | _GitHub repository has vulnerability alerts disabled._ | `githubrepo/main.tf:1-26` | Repository does not have vulnerability alerts enabled, |
|  2 | `github-repositories-enable_vulnerability_alerts` | *HIGH* | _GitHub repository has vulnerability alerts disabled._ | `githubrepo/main.tf:1-26` | Repository does not have vulnerability alerts enabled, |
|  3 | `github-repositories-enable_vulnerability_alerts` | *HIGH* | _GitHub repository has vulnerability alerts disabled._ | `githubrepo/main.tf:1-26` | Repository does not have vulnerability alerts enabled, |
|  4 | `github-repositories-enable_vulnerability_alerts` | *HIGH* | _GitHub repository has vulnerability alerts disabled._ | `githubrepo/main.tf:1-26` | Repository does not have vulnerability alerts enabled, |
|  5 | `github-repositories-enable_vulnerability_alerts` | *HIGH* | _GitHub repository has vulnerability alerts disabled._ | `githubrepo/main.tf:1-26` | Repository does not have vulnerability alerts enabled, |

</details>

**Describe the solution you'd like**

It would be more helpful if the location output in Markdown matched the one in the default (`foo/bar.tf:9-15 (module.repo-one)` - which in itself is not _quite_ accurate, as the line numbers aren't for `foo/bar.tf`, but whichever `baz.tf` where `module.repo-one` is actually instantiated, but that's a problem for another issue).

**Describe alternatives you've considered**

- Generate Markdown ourselves from the JSON output
- Use the default output with code formatting

**Comment by simar7** [comment]
Our efforts have moved to Trivy. Please file a discussion in the Trivy repo if you see fit.
