### ISSUE TITLE
feat: I want to be able to set tfvars file in the tfsec config file

### ISSUE THREAD

**Issue by thibaultserti** [aquasecurity/tfsec#2035]
**Is your feature request related to a problem? Please describe.**

I use a monorepo and I have differents names for my tfvars across my terraform stacks. Wen I run tfsec with the tfsec pre-commit I have no way to set dynamically the tfvars file parameter.

**Describe the solution you'd like**

I want to be able to specify the tfvars file in each of my tfsec.json config file, so my pre-commit uses the appropriate tfvars when running against each stack.

**Describe alternatives you've considered**

I wanted to pass dynamic variables to the tfsec pre-commits hooks but pre-commit is not able to manage dynamic args passed to the hooks.

**Additional context**

[Tflint](https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/config.md#varfile) allows this already, so it doesn't seems to be something absurd to do.

**Comment by simar7** [comment]
We've added support for this in Trivy you can see the docs here https://aquasecurity.github.io/trivy/v0.45/docs/references/configuration/config-file/#misconfiguration-options
