### ISSUE TITLE
bug: fail test Test_Issue_1661

### ISSUE THREAD

**Issue by xiota** [aquasecurity/tfsec#2036]
Build log: [tfsec.log](https://github.com/aquasecurity/tfsec/files/11184298/tfsec.log)

```
=== RUN   Test_Issue_1661
--- PASS: Test_Issue_1661 (0.32s)
FAIL
FAIL	github.com/aquasecurity/tfsec/test	21.832s
FAIL
```

**Comment by xiota** [comment]
Marking issues stale and closing them doesn't actually fix the bug.

**Comment by simar7** [comment]
Our efforts have moved to Trivy. Please file a discussion in the Trivy repo if you see fit.
