### ISSUE TITLE
question: How do I use the latest tfsec while still trust it is not compromised?

### ISSUE THREAD

**Issue by zymzxq** [aquasecurity/tfsec#2038]
I want to use tfsec in my pipeline. In order to do that I can
* Download the binary, verify the signature, run it
* Use `latest` tag of `aquasecurity/tfsec` docker image.

Option 1 feels safer beccause of the signature verification. But I prefer the 2nd option because it is much simpler. How can I confirm the image is not compromised?

**Comment by duxbuse** [comment]
TF sec would need to publish the sha at creation time for you to verify. Or you can pull the image and verify the binary signature before using?

**Comment by simar7** [comment]
Our efforts have moved to Trivy and we do publish checksums upon every release. You can find an example here https://github.com/aquasecurity/trivy/releases/tag/v0.44.0
