### ISSUE TITLE
question: Can tfsec handle the end result of a resource instead of looking at the individual parts? 

### ISSUE THREAD

**Issue by jdmedeiros** [aquasecurity/tfsec#2040]
When I run _terraform apply_ I am having [the problem describe here.](https://discuss.hashicorp.com/t/aws-lambda-permission-triggered-by-ses-will-only-work-with-a-fixed-source-arn/52388)

The only way that I know of to solve this problem is by doing something like this:

```
# aws_lambda_permission.start-stop-one:
resource "aws_lambda_permission" "start-stop-one" {
  action         = "lambda:InvokeFunction"
  function_name  = aws_lambda_function.start-stop-one.function_name
  principal      = "ses.amazonaws.com"
  source_account = data.aws_caller_identity.aws.account_id
}

# aws_lambda_permission.start-stop-one:
resource "aws_lambda_permission" "start-stop-one-b" {
  action         = "lambda:InvokeFunction"
  function_name  = aws_lambda_function.start-stop-one.function_name
  principal      = "ses.amazonaws.com"
  source_account = data.aws_caller_identity.aws.account_id
  source_arn = aws_ses_receipt_rule.start-stop-one.arn
  depends_on = [
    aws_lambda_permission.start-stop-one
  ]
}
```

When I run _tfsec_ I get a **CRITICAL Lambda permission lacks source ARN for \*.amazonaws.com principal** for the first resource, as expected. However, the second resource fulfills the requirement of the source_arn when the resource gets updated by _terraform_. The end result is the same as if the **source_arn** had been specified in the first resource; of course to handle that, _tfsec_ would have to be in a _stateful_ frame of mind. Any alternatives?

**Comment by simar7** [comment]
As you mentioned, the above requires state and as tfsec/Trivy don't have that, we cannot make any assumptions for the future state.
