### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by nkadel** [aquasecurity/tfsec#2043]
**Is your feature request related to a problem? Please describe.**
Telling people to install software by running curl commands, piped to "bash" with no chance to review the code, is astonishingly dangerous. Revise the instalation instructions especially for the "bash" script, to download and *then* run the install_linux.sh or other installation scripts.

**Describe the solution you'd like**
Revise the instructions on README.md to leave a local, readable copy of he installation script.

`wget -O install_linux.sh https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh
bash install_linux.sh'

**Describe alternatives you've considered**

Actually building tfsec locally from the tagged git repo could make even more sense in security terms.

**Additional context**

Giving people an installation tool that bootstraps from somewhere offsite is always risky. Let's be very cautious about the deployment security of a tool used to evaluate other security tools.

**Comment by simar7** [comment]
Our efforts have moved to Trivy. Please file a discussion in the Trivy repo if you see fit.
