### ISSUE TITLE
question: Custom checks for multiple tags

### ISSUE THREAD

**Issue by BhushanGavankar** [aquasecurity/tfsec#2046]
I want to check that tf code has all required tags (more than 1). Can I provide a list to the Value field under 'matchSpec'. 
example:
matchSpec:
    name: tags
    action: contains
    value: ["CostCentre", "Department", "DataClassification"]
 errorMessage: The required tags were missing

**Comment by ChendrayanV** [comment]
I was searching for the same ! Here is the fix for your ask  @BhushanGavankar 

```JSON
 "action": "contains",
  "name": "tags",
  "value": {
      "environment" : {
          "action": "isAny",
          "value": [
              "development",
              "production",
              "test"
          ]
      }
  }
```

**Comment by simar7** [comment]
Our efforts have moved to Trivy. Please file a discussion in the Trivy repo if you see fit.
