### ISSUE TITLE
question: 

### ISSUE THREAD

**Issue by coltonfreeman26** [aquasecurity/tfsec#2048]
Good day all,
Is there any plan to update the version of go being used? I have read that yall are in the process of moving over to trivy and that little effort is being spent on tfsec. 
We currently are using tfsec 1.28.1 from docker hub and have multiple findings from Anchore and Twistlock in regards to the current go version. 
go-1.18.7
Looks like the majority of these findings are fixed in 1.19.8 and 1.20.3

**Comment by hamma741** [comment]
Trivy scans only dependencies of the Go project. Let's say you scan the Docker binary, Trivy doesn't detect vulnerabilities of Docker itself. Also, when you scan go.mod in Kubernetes, the Kubernetes vulnerabilities will not be found. 
For more Information 
https://aquasecurity.github.io/trivy/v0.39/docs/vulnerability/languages/golang/

**Comment by simar7** [comment]
Our efforts have moved to Trivy. Please file a discussion in the Trivy repo if you see fit.
