### ISSUE TITLE
Tfsec config file doesn't support to define soft-fail 

### ISSUE THREAD

**Issue by AshishDadhich4h2** [aquasecurity/tfsec#2054]
**Describe the bug**
When we define soft-fail in config file and pass that config file to tfsec cli , it doesn't work.

**To Reproduce**
Define config like tfsec_config.yml
`soft-fail: true  #Runs checks but suppresses error code
include-passed: true #Resources that pass checks are included in the result output
allow-checks-to-panic: true #Allow panics to propagate up from rule checking
verbose: true #Enable verbose logging`

tfsec --config-file tfsec_config.yml

Got an error like ##[error]Failed: tfsec detected misconfigurations. 
Means soft-fail: true is not working when it's set in config.yml file.

**Expected behavior**
It should override cli options from config file.
It works for cli option --exclude when we define in config file 
```
exclude:
  - azure-network-no-public-ingress
```
Ideally it should work for other cli options too.

**Output of your tfsec command with --debug flag**

**System Info**

 - tfsec version: `v1.26.0`
 - terraform version: `1.4.6`
 - OS: `Linux`

**Example Code**

**Additional context**

**Comment by simar7** [comment]
Our efforts have moved to Trivy. Please file a discussion in the Trivy repo if you see it fit.
