### ISSUE TITLE
bug: ID not found tfsec MEDIUM Instance does not have IAM Authentication enabled 

### ISSUE THREAD

**Issue by ramosbianca** [aquasecurity/tfsec#2056]
**Describe the bug**

**Tfsec file**
1. #tfsec:ignore:RDSInstanceIAMAuthEnabled
2. AWS0176
3. aws-rds-enable-iam-authentication

It's like he can't read his own id, I followed all the rules for this ignore, but it's not working

**Comment by ramosbianca** [comment]
Resolution: tfsec was at version 1.28.1, it worked downgrading to 1.28.0

**Comment by jcg-2** [comment]
I believe you can use `tfsec:ignore:AVD-AWS-0176`
