### ISSUE TITLE
question: Custom Check for IAM Approvals

### ISSUE THREAD

**Issue by duxbuse** [aquasecurity/tfsec#2063]
Howdy,  I would like to use Custom Checks to ensure that all IAM resources have an associated link to an approval for its use.

But there doesn't seem to be a way to add a generic new field to TF resources, I was wondering if there was a way to make the custom check check the name of the resource, not a name field as I could use that like in #1882

Or is there a way to look for a comment in the resource?

**Comment by simar7** [comment]
dupe of https://github.com/aquasecurity/tfsec/issues/1803
