### ISSUE TITLE
feat: tfsec does not support terraform 1.5.0+ check block

### ISSUE THREAD

**Issue by reifnir** [aquasecurity/tfsec#2068]
**Is your feature request related to a problem? Please describe.**
We started using the Terraform `check` block, new to Terraform 1.5.

Unfortunately, tfsec scanning fails because it doesn't know what to do with that block.
```bash
$ tfsec $TF_DIR --include-passed $SOFT_FAIL_ARG $MIN_SEV_ARG $CONFIG_ARG -f junit --out "$REPORT_PATH"
Error: scan failed: builds/[REDACTED]/aws/global-policies/networking-shared-permissions-boundary.tf:111,1-6: Unsupported block type; Blocks of type "check" are not expected here.
```

**Describe the solution you'd like**
Tfsec should ignore these blocks until you find something worthy of a security finding.

**Describe alternatives you've considered**
- Disable tfsec scanning
   - Not a great idea, even if we are also scanning with checkov
- Don't use `aws_iam_policy_document` object and store as raw json
   - Hard to read and maintain, changes to any part of the policy show up in a single line change. Bad idea.
- Let it blow up at apply time
   - Going with this until tfsec supports the new block from Terraform

**Comment by nishigori** [comment]
I have solved this problem by https://github.com/aquasecurity/defsec/pull/1354
Currently waiting for defsec (tfsec dependency) to be released.

**Comment by nishigori** [comment]
This issue will be resolved by merging https://github.com/aquasecurity/tfsec/pull/2060

**Comment by maxforasteiro** [comment]
hey @simar7 I know it's not nice to tag people around, but we have such a nice momentum of people trying the new feature from terraform being blocked by a dependency update on your side. could we have this solved?

from what I saw https://github.com/aquasecurity/tfsec/pull/2084 is the latest PR updating the defsec dependency

**Comment by simar7** [comment]
Closing as Trivy supports this now.

**Comment by ilmax** [comment]
@simar7 tfsec doesn't yet support new terraform 1.5+ syntax right? Trivy now supports it but tfsec still didn't update the dependency and most importantly release a version that we can use or am I missing something? 
If that's the case I think this shouldn't be close yet because the problem is not solved as of now

**Comment by reifnir** [comment]
I agree with what @ilmax said. This issue was ready to be merged but kept being kicked down the road because this issue hasn't been dragged across the finish line.
