### ISSUE TITLE
feat: tfsec does not support terraform 1.5.0+ import block 

### ISSUE THREAD

**Issue by nishigori** [aquasecurity/tfsec#2070]
**Is your feature request related to a problem? Please describe.**

This issue is similar to #2068

We started using the Terraform check block, new to Terraform 1.5.

Unfortunately, tfsec scanning fails because it doesn't know what to do with that block.

```sh
$ tfsec-1.28.1 $TF_DIR
Error: scan failed: xxx/_import.tf:11,1-7: Unsupported block type; Blocks of type "import" are not expected here.
```
**Describe the solution you'd like**
Tfsec should ignore these blocks until you find something worthy of a security finding.

**Describe alternatives you've considered**
* Let it blow up at apply time
    * Going with this until tfsec supports the new block from Terraform

----

### Edit Updated

Since it will probably take a long time to resolve this issue,
Here are some possible solutions:
- migrate aquasecurity/trivy https://github.com/aquasecurity/tfsec/issues/2070#issuecomment-1658435165
- you can run tfsec with --ignore-hcl-errors https://github.com/aquasecurity/tfsec/issues/2070#issuecomment-1669056215

**Comment by sebastian-hans-swm** [comment]
Ran into the same issue, looking forward to a solution.

**Comment by nishigori** [comment]
This issue has been fixed by https://github.com/aquasecurity/defsec/pull/1339
and will be resolved by tfsec with the release of defsec
(maybe pr by Dependabot at end of June)

**Comment by nishigori** [comment]
This issue will be resolved by merging #2060

**Comment by dod38fr** [comment]
#2060 was superseded by https://github.com/aquasecurity/tfsec/pull/2073

**Comment by johnknutsonhc** [comment]
> #2060 was superseded by #2073

https://github.com/aquasecurity/tfsec/pull/2073has now been superseded by https://github.com/aquasecurity/tfsec/pull/2078

**Comment by spr-mweber3** [comment]
I just stumbled across this issue. But for me it has not been the `import`-block but the `check`-block. I hope this will be fixed together.

**Comment by seanturner026** [comment]
> I hope this will be fixed together.

Honestly at this point I kind of doubt it. I've been hit with another issue from the October release that required me to downgrade. Once this showed up and there's no movement on merging a depenabot PR I started wondering if this project is actually maintained anymore. Which caused me to find the below issue, which makes it sound like tfsec is going to go away in favor of trivvy.

https://github.com/aquasecurity/tfsec/discussions/1994

**Comment by simar7** [comment]
`import` block is supported in Trivy misconf scanning.

**Comment by spr-mweber3** [comment]
> > I hope this will be fixed together.
> 
> Honestly at this point I kind of doubt it. I've been hit with another issue from the October release that required me to downgrade. Once this showed up and there's no movement on merging a depenabot PR I started wondering if this project is actually maintained anymore. Which caused me to find the below issue, which makes it sound like tfsec is going to go away in favor of trivvy.
> 
> #1994

Thanks for pointing that out. Seems like you're right. Time to move on, it seems.

**Comment by falkenbt** [comment]
As a workaround you can run tfsec with `--ignore-hcl-errors` and rely on tflint or terraform to catch hcl errors.

**Comment by simar7** [comment]
Closing as Trivy supports this now.

**Comment by marcofranssen** [comment]
> Closing as Trivy supports this now.

Should we use trivy instead? Is that what you are saying? is tfsec going to get updates?

**Comment by 2357gi** [comment]
@marcofranssen 
You should definitely use Trivy. As mentioned in this repository's readme, it is recommended to transition from tfsec to Trivy.
https://github.com/aquasecurity/tfsec#-tfsec-to-trivy-migration
