### ISSUE TITLE
bug: expiration_date not a string key_vault_key

### ISSUE THREAD

**Issue by TheIronRock95** [aquasecurity/tfsec#2085]
**Describe the bug**
The output from `time_offset.offset.rfc3339` is not being recognized as a string, leading to unexpected behavior.

**Expected behavior**
Ensure that the output of `time_offset.offset.rfc3339` is treated and used as a string in terraform. This will prevent any issues caused by incorrect data types and allow the proper handling of the output as intended.

**Output of your tfsec command with --debug flag**

> panic: not a string
> 
> goroutine 1 [running]:
> github.com/zclconf/go-cty/cty.Value.AsString({{{0x0?, 0x0?}}, {0x0?, 0x0?}})
> 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/zclconf/go-cty@v1.10.0/cty/value_ops.go:1256 +0x130
> github.com/aquasecurity/defsec/internal/adapters/terraform/azure/keyvault.adaptKey(_)
> 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/azure/keyvault/adapt.go:154 +0x15c
> github.com/aquasecurity/defsec/internal/adapters/terraform/azure/keyvault.(*adapter).adaptVaults(0x14001e1f288, {0x14002c6d200, 0x44, 0x14001e1f298?})
> 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/azure/keyvault/adapt.go:74 +0x1028
> github.com/aquasecurity/defsec/internal/adapters/terraform/azure/keyvault.Adapt({0x14002c6d200, 0x44, 0x48})
> 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/azure/keyvault/adapt.go:20 +0xa4
> github.com/aquasecurity/defsec/internal/adapters/terraform/azure.Adapt({_, _, _})
> 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/azure/adapt.go:30 +0x1a8
> github.com/aquasecurity/defsec/internal/adapters/terraform.Adapt({0x14002c6d200, 0x44, 0x48})
> 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/adapt.go:20 +0x6c
> github.com/aquasecurity/defsec/pkg/scanners/terraform/executor.(*Executor).Execute(0x14001019800, {0x14002c6d200?, 0x44, 0x48})
> 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/pkg/scanners/terraform/executor/executor.go:96 +0xd4
> github.com/aquasecurity/defsec/pkg/scanners/terraform.(*Scanner).ScanFSWithMetrics(0x140002aa1e0, {0x101e65580, 0x1400019c030}, {0x12a63c880?, 0x14000cdab40?}, {0x14000046055, 0x3e})
> 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/pkg/scanners/terraform/scanner.go:216 +0x604
> github.com/aquasecurity/tfsec/internal/app/tfsec/cmd.Root.func1(0x14000c20300, {0x14000cdaa40, 0x0, 0x2})
> 	/private/tmp/tfsec-20221102-4479-e7dyae/tfsec-1.28.1/internal/app/tfsec/cmd/root.go:83 +0x53c
> github.com/spf13/cobra.(*Command).execute(0x14000c20300, {0x14000186190, 0x2, 0x2})
> 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:916 +0x5c8
> github.com/spf13/cobra.(*Command).ExecuteC(0x14000c20300)
> 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040 +0x354
> github.com/spf13/cobra.(*Command).Execute(...)
> 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968
> main.main()
> 	/private/tmp/tfsec-20221102-4479-e7dyae/tfsec-1.28.1/cmd/tfsec/main.go:12 +0x20
> 
> 

**System Info**
 - tfsec version: `v1.28.1`
 - terraform version: `v1.5.4`
 - OS: `MacOS 13.4.1`

**Example Code**
```hcl
resource "azurerm_key_vault_key" "this" {
  name         = "example-key"
  key_vault_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/example/providers/Microsoft.KeyVault/vaults/example-key-vault"
  key_type     = "RSA"
  key_size     = "2048"

  expiration_date = time_offset.offset.rfc3339

}

resource "time_offset" "offset" {
  offset_months = 13
}

```

**Comment by nikpivkin** [comment]
Hi @TheIronRock95 !

This has been [fixed](https://github.com/aquasecurity/defsec/issues/1024). You can use Trivy to scan the configuration, because tfsec is [part of it](https://github.com/aquasecurity/tfsec/discussions/1994).
