### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by RoFz** [aquasecurity/tfsec#2093]
**Describe the bug**
Receiving a `panic: not a string` error message without further indication of where the underlying issue could be located.

**To Reproduce**
1. Run `tfsec .` from. the module's directory

**Expected behavior**
tfsec's error log should pinpoint which terraform resource or variable (line number?) was not correctly understood by its parser.

**Output of your tfsec command with --debug flag**

> 07:29.736937000 system.info                      APP       tfsec
> 07:29.737062000 system.info                      VERSION   v1.28.1
> 07:29.737063000 system.info                      OS        darwin
> 07:29.737064000 system.info                      ARCH      arm64
> 07:29.737065000 system.info                      KERNEL    
> 07:29.737066000 system.info                      TERM      xterm-256color
> 07:29.737068000 system.info                      SHELL     /bin/zsh
> 07:29.737068000 system.info                      GOVERSION go1.19.3
> 07:29.737071000 system.info                      GOROOT    /opt/homebrew/Cellar/go/1.19.3/libexec
> 07:29.737072000 system.info                      CGO       false
> 07:29.737074000 system.info                      CPUCOUNT  10
> 07:29.737075000 system.info                      MAXPROCS  10
> 07:29.737076000 system.info                      WORKDIR   /Users/myusername/Library/CloudStorage/OneDrive-mycompanynamedirectory/Git/mydirectoryname/tf-mod-az-keyvault
> 07:29.737078000 system.info                      UID       501
> 07:29.737119000 system.info                      EUID      501
> 07:29.737121000 system.info                      DOCKER    false
> 07:29.737122000 system.info                      CI        false
> 07:29.737123000 system.info                      HOSTNAME  MACHOSTNAME
> 07:29.737124000 system.info                      TEMP      /var/folders/zt/ww2w2gpx6x5cn0lmsj4tyj5h0000gn/T/
> 07:29.737125000 system.info                      PATHSEP   /
> 07:29.737127000 system.info                      CMD       tfsec . --debug
> 07:29.737132000 cmd                              Command args=[]string{"."}
> 07:29.737766000 cmd                              Determined path dir=/Users/myusername/Library/CloudStorage/OneDrive-mycompanynamedirectory/Git/mydirectoryname/tf-mod-az-keyvault
> 07:29.737862000 cmd                              Determined path root=/
> 07:29.737865000 cmd                              Determined path rel=Users/myusername/Library/CloudStorage/OneDrive-mycompanynamedirectory/Git/mydirectoryname/tf-mod-az-keyvault
> 07:29.737946000 terraform.scanner                Scanning [&{/ /}] at 'Users/myusername/Library/CloudStorage/OneDrive-mycompanynamedirectory/Git/mydirectoryname/tf-mod-az-keyvault'...
> 07:29.740641000 terraform.scanner.rego           Loaded 3 embedded libraries.
> 07:29.757557000 terraform.scanner.rego           Loaded 119 embedded policies.
> 07:29.855858000 terraform.scanner                Scanning root module 'Users/myusername/Library/CloudStorage/OneDrive-mycompanynamedirectory/Git/mydirectoryname/tf-mod-az-keyvault'...
> 07:29.855882000 terraform.parser.<root>          Setting project/module root to 'Users/myusername/Library/CloudStorage/OneDrive-mycompanynamedirectory/Git/mydirectoryname/tf-mod-az-keyvault'
> 07:29.855884000 terraform.parser.<root>          Parsing FS from 'Users/myusername/Library/CloudStorage/OneDrive-mycompanynamedirectory/Git/mydirectoryname/tf-mod-az-keyvault'
> 07:29.856064000 terraform.parser.<root>          Parsing 'Users/myusername/Library/CloudStorage/OneDrive-mycompanynamedirectory/Git/mydirectoryname/tf-mod-az-keyvault/locals.tf'...
> 07:29.858170000 terraform.parser.<root>          Added file Users/myusername/Library/CloudStorage/OneDrive-mycompanynamedirectory/Git/mydirectoryname/tf-mod-az-keyvault/locals.tf.
> 07:29.858188000 terraform.parser.<root>          Parsing 'Users/myusername/Library/CloudStorage/OneDrive-mycompanynamedirectory/Git/mydirectoryname/tf-mod-az-keyvault/module.tf'...
> 07:29.859035000 terraform.parser.<root>          Added file Users/myusername/Library/CloudStorage/OneDrive-mycompanynamedirectory/Git/mydirectoryname/tf-mod-az-keyvault/module.tf.
> 07:29.859046000 terraform.parser.<root>          Parsing 'Users/myusername/Library/CloudStorage/OneDrive-mycompanynamedirectory/Git/mydirectoryname/tf-mod-az-keyvault/outputs.tf'...
> 07:29.859252000 terraform.parser.<root>          Added file Users/myusername/Library/CloudStorage/OneDrive-mycompanynamedirectory/Git/mydirectoryname/tf-mod-az-keyvault/outputs.tf.
> 07:29.859260000 terraform.parser.<root>          Parsing 'Users/myusername/Library/CloudStorage/OneDrive-mycompanynamedirectory/Git/mydirectoryname/tf-mod-az-keyvault/providers.tf'...
> 07:29.859423000 terraform.parser.<root>          Added file Users/myusername/Library/CloudStorage/OneDrive-mycompanynamedirectory/Git/mydirectoryname/tf-mod-az-keyvault/providers.tf.
> 07:29.859430000 terraform.parser.<root>          Parsing 'Users/myusername/Library/CloudStorage/OneDrive-mycompanynamedirectory/Git/mydirectoryname/tf-mod-az-keyvault/variables.tf'...
> 07:29.860197000 terraform.parser.<root>          Added file Users/myusername/Library/CloudStorage/OneDrive-mycompanynamedirectory/Git/mydirectoryname/tf-mod-az-keyvault/variables.tf.
> 07:29.860206000 terraform.parser.<root>          Evaluating module...
> 07:29.861207000 terraform.parser.<root>          Read 38 block(s) and 0 ignore(s) for module 'root' (5 file[s])...
> 07:29.861213000 terraform.parser.<root>          Added 0 variables from tfvars.
> 07:29.861223000 terraform.parser.<root>          Error loading module metadata: open //Users/myusername/Library/CloudStorage/OneDrive-mycompanynamedirectory/Git/mydirectoryname/tf-mod-az-keyvault/.terraform/modules/modules.json: no such file or directory.
> 07:29.861236000 terraform.parser.<root>          Working directory for module evaluation is '/Users/myusername/Library/CloudStorage/OneDrive-mycompanynamedirectory/Git/mydirectoryname/tf-mod-az-keyvault'
> 07:29.861631000 terraform.parser.<root>.evaluator Filesystem key is 'f9088d3ed2db9899500f703a07bb505300c2b5cbc122ac4365ca04af35422e64'
> 07:29.861635000 terraform.parser.<root>.evaluator Starting module evaluation...
> 07:29.863055000 terraform.parser.<root>.evaluator Starting submodule evaluation...
> 07:29.863270000 terraform.parser.<root>.evaluator Finished processing 0 submodule(s).
> 07:29.863277000 terraform.parser.<root>.evaluator Starting post-submodule evaluation...
> 07:29.865051000 terraform.parser.<root>.evaluator Module evaluation complete.
> 07:29.865070000 terraform.parser.<root>          Finished parsing module 'root'.
> 07:29.865087000 terraform.parser.<root>.evaluator Added module output key_vault_id=cty.StringVal("68a86542-0a2a-428f-8ee8-5bc1bdbc8f7f").
> 07:29.865091000 terraform.parser.<root>.evaluator Added module output key_vault_name=cty.NilVal.
> 07:29.865094000 terraform.executor               Adapting modules...
> panic: not a string
> 
> goroutine 1 [running]:
> github.com/zclconf/go-cty/cty.Value.AsString({{{0x0?, 0x0?}}, {0x0?, 0x0?}})
>         /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/zclconf/go-cty@v1.10.0/cty/value_ops.go:1256 +0x130
> github.com/aquasecurity/defsec/internal/adapters/terraform/azure/keyvault.adaptKey(_)
>         /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/azure/keyvault/adapt.go:154 +0x15c
> github.com/aquasecurity/defsec/internal/adapters/terraform/azure/keyvault.(*adapter).adaptVault(_, _, _)
>         /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/azure/keyvault/adapt.go:97 +0x360
> github.com/aquasecurity/defsec/internal/adapters/terraform/azure/keyvault.(*adapter).adaptVaults(0x14001dfb288, {0x140013d21c8, 0x1, 0x14001dfb298?})
>         /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/azure/keyvault/adapt.go:34 +0x16d8
> github.com/aquasecurity/defsec/internal/adapters/terraform/azure/keyvault.Adapt({0x140013d21c8, 0x1, 0x1})
>         /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/azure/keyvault/adapt.go:20 +0xa4
> github.com/aquasecurity/defsec/internal/adapters/terraform/azure.Adapt({_, _, _})
>         /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/azure/adapt.go:30 +0x1a8
> github.com/aquasecurity/defsec/internal/adapters/terraform.Adapt({0x140013d21c8, 0x1, 0x1})
>         /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/adapt.go:20 +0x6c
> github.com/aquasecurity/defsec/pkg/scanners/terraform/executor.(*Executor).Execute(0x14000b51a00, {0x140013d21c8?, 0x1, 0x1})
>         /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/pkg/scanners/terraform/executor/executor.go:96 +0xd4
> github.com/aquasecurity/defsec/pkg/scanners/terraform.(*Scanner).ScanFSWithMetrics(0x140002b44b0, {0x102385580, 0x140001a6030}, {0x12af15b30?, 0x14000e0bf00?}, {0x140006315c1, 0x5c})
>         /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/pkg/scanners/terraform/scanner.go:216 +0x604
> github.com/aquasecurity/tfsec/internal/app/tfsec/cmd.Root.func1(0x14000c4ec00, {0x14000e0be20, 0x1, 0x2})
>         /private/tmp/tfsec-20221102-4479-e7dyae/tfsec-1.28.1/internal/app/tfsec/cmd/root.go:83 +0x53c
> github.com/spf13/cobra.(*Command).execute(0x14000c4ec00, {0x14000192190, 0x2, 0x2})
>         /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:916 +0x5c8
> github.com/spf13/cobra.(*Command).ExecuteC(0x14000c4ec00)
>         /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040 +0x354
> github.com/spf13/cobra.(*Command).Execute(...)
>         /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968
> main.main()
>         /private/tmp/tfsec-20221102-4479-e7dyae/tfsec-1.28.1/cmd/tfsec/main.go:12 +0x20

**System Info**

 - tfsec version: `v1.28.1`
 - terraform version: `v1.5.3`
 - OS: `macOS Ventura 13.5`

**Example Code**
Since the underlying issue is not clear, I'd need to post the entire module's code here, which I'm prevented by my company's policies from doing. It is an Azure KeyVault base module.

**Additional context**
The question here is: how to locate the resource or variable that might be incorrectly declared in the module that is causing this error?

**Comment by nikpivkin** [comment]
Hi @RoFz !
Could you provide an example of the configuration that you have a problem with?

**Comment by RoFz** [comment]
> Hi @RoFz ! Could you provide an example of the configuration that you have a problem with?

> Example Code
> Since the underlying issue is not clear, I'd need to post the entire module's code here, which I'm prevented by my company's policies from doing. It is an Azure KeyVault base module.

Additionally, if I could post a code snippet, that would mean I have managed to track which part of the module has the problem, which is exactly the issue here: tfsec does not provide any indication as to where the underlying problem is.

**Comment by nikpivkin** [comment]
@RoFz It seems this problem has already been [solved](https://github.com/aquasecurity/defsec/issues/1024). You can use [Trivy](https://github.com/aquasecurity/trivy) to scan configurations. https://github.com/aquasecurity/tfsec/discussions/1994

**Comment by RoFz** [comment]
@nikpivkin thanks! I can confirm that it is the same root cause. Here's the code snippet.

```
resource "azurerm_key_vault_key" "kv_stkvdiagkey" {
  name            = format("key-%s", azurecaf_name.caf_stkvdiag.result)
  key_vault_id    = azurerm_key_vault.main.id
  key_type        = "RSA-HSM"
  key_size        = 2048
  expiration_date = time_rotating.kv_stkvdiagkey.rotation_rfc3339
  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey"
  ]
  depends_on = [
    azurerm_key_vault_access_policy.tf_user,
    azurerm_key_vault_access_policy.stkvdiag
  ]
}
```

So, from #1994, tfsec will not be maintained anymore as an individual tool and I should not expect this same [fix](https://github.com/aquasecurity/defsec/issues/1024) to be applied to its homebrew version, would that be correct?

**Comment by tososomaru** [comment]
@RoFz Right, the efforts of the developers are aimed at Trivy.

**Comment by nikpivkin** [comment]
@RoFz That's right, the developers' efforts are aimed at Trivy.
