### ISSUE TITLE
AWS CloudFront Distribution Encryption Bug Persists Post-PR #1083

### ISSUE THREAD

**Issue by obounaim** [aquasecurity/tfsec#2103]
**Describe the bug**

Related to issue : #1082 
Despite the merge of PR [#1083](https://github.com/aquasecurity/tfsec/pull/1083), the tfsec scanner still reports a HIGH severity finding suggesting my AWS CloudFront distribution allows unencrypted communications due to outdated SSL policies.

**To Reproduce**

1. Ensure you are using the latest version of tfsec that includes the changes from PR #1083.
2. Create an AWS CloudFront distribution resource in Terraform with the viewer_certificate block set to cloudfront_default_certificate = true.
3. Run the tfsec scanner on the Terraform code.

**Output of your tfsec command:**
![image](https://github.com/aquasecurity/tfsec/assets/1151352/a9f5ddd1-7f85-4c8b-866b-642dc6a169b9)

**Actual Behavior**
1. The title of the finding is "HIGH Distribution allows unencrypted communications." However the links and code snippet are referring to [CloudFront distribution uses outdated SSL/TLS protocols](https://aquasecurity.github.io/tfsec/v1.28.4/checks/aws/cloudfront/use-secure-tls-policy/)

**Expected Behavior**
1.  According to the terraform documentation when the `cloudfront_default_certificate` is set to true,  the argument [minimum_protocol_version](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#minimum_protocol_version) is not supported

**System Info**
 - tfsec version: `v1.28.4`
 - terraform version: `1.5.5`
 - OS: `Linux`

**Terraform Code**
```

resource "aws_cloudfront_distribution" "this" {
  origin {
    domain_name = var.backend_domain_name
    origin_id   = "my_backend"

    custom_origin_config {
      http_port              = "80"
      https_port             = "443"
      origin_protocol_policy = "https-only"
      origin_ssl_protocols   = ["TLSv1.2"]
    }
  }

  enabled         = true
  is_ipv6_enabled = true

  price_class = "PriceClass_100"

  viewer_certificate {
    cloudfront_default_certificate = true
  }

  default_cache_behavior {
    allowed_methods  = ["GET", "HEAD", "OPTIONS"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "my_backend"

    viewer_protocol_policy = "redirect-to-https"
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
      locations        = []
    }
  }

  custom_error_response {
    error_code         = 403
    response_code      = 200
    response_page_path = "/index.html"
  }
}
```

**Comment by simar7** [comment]
hi, we've moved our efforts to Trivy. If this issue persists in Trivy, please open a discussion here: https://github.com/aquasecurity/trivy/discussions
