### ISSUE TITLE
Add new checks

### ISSUE THREAD

**Issue by owenrumney** [aquasecurity/tfsec#763]
| Provider 	| Resource                                      |	Description | Implemented | Released |
 |:-------------|:----------------------------------------------|:--------------|:-:|:-:|
 | google   	| google_storage_bucket_iam_member              |	Ensure that Cloud Storage bucket is not anonymously or publicly accessible | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_storage_bucket_iam_binding             |	Ensure that Cloud Storage bucket is not anonymously or publicly accessible | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_storage_bucket                         |	Ensure that Cloud Storage buckets have uniform bucket-level access enabled | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_sql_database_instance                  |	Ensure that Cloud SQL database Instances are not open to the world | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_sql_database_instance                  |	Ensure SQL database do not have public IP | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_sql_database_instance                  |	Ensure SQL database 'cross db ownership chaining' flag is set to 'off' | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_sql_database_instance                  |	Ensure SQL database 'contained database authentication' flag is set to 'off' | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_sql_database_instance                  |	Ensure PostgreSQL database 'log_temp_files flag is set to '0' | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_sql_database_instance                  |	Ensure PostgreSQL database 'log_min_messages' flag is set to a valid value | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_sql_database_instance                  |	Ensure PostgreSQL database 'log_min_duration_statement' flag is set to '-1' | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_sql_database_instance                  |	Ensure PostgreSQL database 'log_lock_waits' flag is set to 'on' | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_sql_database_instance                  |	Ensure PostgreSQL database 'log_disconnections' flag is set to 'on' | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_sql_database_instance                  |	Ensure PostgreSQL database 'log_connections' flag is set to 'on' | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_sql_database_instance                  |	Ensure PostgreSQL database 'log_checkpoints' flag is set to 'on' | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_sql_database_instance                  |	Ensure MySQL database 'local_infile' flag is set to 'off' | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_sql_database_instance                  |	Ensure all Cloud SQL database instance requires all incoming connections to use SSL | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_sql_database_instance                  |	Ensure all Cloud SQL database instance have backup configuration enabled | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_project_iam_member                     |	Ensure that Service Account has no Admin privileges | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_project_iam_member                     |	Ensure that IAM users are not assigned the Service Account User or Service Account Token Creator roles at project level | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_project_iam_member                     |	Ensure no roles that enable to impersonate and manage all service accounts are used at a project level | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_project_iam_member                     |	Ensure Default Service account is not used at a project level | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_project_iam_binding                    |	Ensure that IAM users are not assigned the Service Account User or Service Account Token Creator roles at project level | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_project_iam_binding                    |	Ensure no roles that enable to impersonate and manage all service accounts are used at a project level | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_project_iam_binding                    |	Ensure Default Service account is not used at a project level | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_project                                |	Ensure that the default network does not exist in a project | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_organization_iam_member                |	Ensure no roles that enable to impersonate and manage all service accounts are used at an organization level | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_organization_iam_member                |	Ensure default service account is not used at an organization level | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_organization_iam_binding               |	Ensure no roles that enable to impersonate and manage all service accounts are used at an organization level |:heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_organization_iam_binding               |	Ensure default service account is not used at an organization level |:heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_kms_crypto_key                         |	Ensure KMS encryption keys are rotated within a period of 90 days | :x: | :x: |
 | google   	| google_folder_iam_member                      |	Ensure no roles that enable to impersonate and manage all service accounts are used at a folder level | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_folder_iam_member                      |	Ensure Default Service account is not used at a folder level | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_folder_iam_binding                     |	Ensure no roles that enable to impersonate and manage all service accounts are used at a folder level |:heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_folder_iam_binding                     |	Ensure Default Service account is not used at a folder level | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_dns_managed_zone                       |	Ensure that RSASHA1 is not used for the zone-signing and key-signing keys in Cloud DNS DNSSEC | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_dns_managed_zone                       |	Ensure that DNSSEC is enabled for Cloud DNS |:heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_container_node_pool                    |	Ensure Container-Optimized OS (cos) is used for Kubernetes Engine Clusters Node image | :x: | :x: |
 | google   	| google_container_node_pool                    |	Ensure 'Automatic node upgrade' is enabled for Kubernetes Clusters | :x: | :x: |
 | google   	| google_container_node_pool                    |	Ensure 'Automatic node repair' is enabled for Kubernetes Clusters | :x: | :x: |
 | google   	| google_container_cluster                      |	Ensure Stackdriver Monitoring is set to Enabled on Kubernetes Engine Clusters | :x: | :x: |
 | google   	| google_container_cluster                      |	Ensure Stackdriver Logging is set to Enabled on Kubernetes Engine Clusters | :x: | :x: |
 | google   	| google_container_cluster                      |	Ensure PodSecurityPolicy controller is enabled on the Kubernetes Engine Clusters | :x: | :x: |
 | google   	| google_container_cluster                      |	Ensure Network Policy is enabled on Kubernetes Engine Clusters | :x: | :x: |
 | google   	| google_container_cluster                      |	Ensure master authorized networks is set to enabled in GKE clusters | :x: | :x: |
 | google   	| google_container_cluster                      |	Ensure Legacy Authorization is set to Disabled on Kubernetes Engine Clusters | :x: | :x: |
 | google   	| google_container_cluster                      |	Ensure Kubernetes Clusters are configured with Labels | :x: | :x: |
 | google   	| google_container_cluster                      |	Ensure Kubernetes Cluster is created with Private cluster enabled | :x: | :x: |
 | google   	| google_container_cluster                      |	Ensure Kubernetes Cluster is created with Alias IP ranges enabled | :x: | :x: |
 | google   	| google_container_cluster                      |	Ensure GKE Control Plane is not public | :x: | :x: |
 | google   	| google_container_cluster                      |	Ensure a client certificate is used by clients to authenticate to Kubernetes Engine Clusters | :x: | :x: |
 | google   	| google_compute_subnetwork                     |	Ensure that VPC Flow Logs is enabled for every subnet in a VPC Network | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_compute_ssl_policy                     |	Ensure no HTTPS or SSL proxy load balancers permit SSL policies with weak cipher suites | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_compute_project_metadata               |	Ensure oslogin is enabled for a Project |:heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_compute_instance                       |	Ensure VM disks for critical VMs are encrypted with Customer Supplied Encryption Keys (CSEK) | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_compute_instance                       |	Ensure that no instance in the project overrides the project setting for enabling OSLogin(OSLogin needs to be enabled in project metadata for all instances) | :heavy_check_mark: | :heavy_check_mark: ||
 | google   	| google_compute_instance                       |	Ensure that IP forwarding is not enabled on Instances | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_compute_instance                       |	Ensure that instances are not configured to use the default service account with full access to all Cloud APIs | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_compute_instance                       |	Ensure that instances are not configured to use the default service account | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_compute_instance                       |	Ensure that Compute instances do not have public IP addresses | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_compute_instance                       |	Ensure Compute instances are launched with Shielded VM enabled |:heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_compute_instance                       |	Ensure 'Enable connecting to serial ports' is not enabled for VM Instance |:heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_compute_instance                       |	Ensure 'Block Project-wide SSH keys' is enabled for VM instances |:heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_compute_firewall                       |	Ensure Google compute firewall ingress does not allow unrestricted ssh access | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_compute_firewall                       |	Ensure Google compute firewall ingress does not allow unrestricted rdp access | :heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_compute_disk                           |	Ensure VM disks for critical VMs are encrypted with Customer Supplied Encryption Keys (CSEK) |:heavy_check_mark: | :heavy_check_mark: |
 | google   	| google_bigquery_dataset                       |	Ensure that BigQuery datasets are not anonymously or publicly accessible |:heavy_check_mark: | :heavy_check_mark: |
 | azure    	| azurerm_virtual_machine                       |	Ensure that no sensitive credentials are exposed in VM custom_data | :x: | :x: |
 | azure    	| azurerm_sql_firewall_rule                     |	Ensure no SQL Databases allow ingress from 0.0.0.0/0 (ANY IP) | :x: | :x: |
 | azure    	| azurerm_security_center_subscription_pricing  |	Ensure that standard pricing tier is selected | :heavy_check_mark: | :heavy_check_mark: |
 | azure    	| azurerm_security_center_contact               |	Ensure that security contact 'Phone number' is set | :heavy_check_mark: | :heavy_check_mark: |
 | azure    	| azurerm_security_center_contact               |	Ensure that 'Send email notification for high severity alerts' is set to 'On' | :heavy_check_mark: | :heavy_check_mark: |
 | azure    	| azurerm_security_center_contact               |	Ensure that 'Send email notification for high severity alerts' is set to 'On' | :heavy_check_mark: | :heavy_check_mark: |
 | azure    	| azurerm_role_definition                       |	Ensure that no custom subscription owner roles are created | :x: | :x: |
 | azure    	| azurerm_postgresql_server                     |	Ensure 'Enforce SSL connection' is set to 'ENABLED' for PostgreSQL Database Server | :heavy_check_mark: | :heavy_check_mark: |
 | azure    	| azurerm_postgresql_firewall_rule              |	Ensure no SQL Databases allow ingress from 0.0.0.0/0 (ANY IP) | :x: | :x: |
 | azure    	| azurerm_postgresql_configuration              |	Ensure server parameter 'log_connections' is set to 'ON' for PostgreSQL Database Server | :x: | :x: |
 | azure    	| azurerm_postgresql_configuration              |	Ensure server parameter 'log_checkpoints' is set to 'ON' for PostgreSQL Database Server | :x: | :x: |
 | azure    	| azurerm_postgresql_configuration              |	Ensure server parameter 'connection_throttling' is set to 'ON' for PostgreSQL Database Server | :x: | :x: |
 | azure    	| azurerm_network_watcher_flow_log              |	Ensure that Network Security Group Flow Log retention period is 'greater than 90 days' | :heavy_check_mark: | :heavy_check_mark: |
 | azure    	| azurerm_network_security_rule                 |	Ensure that SSH access is restricted from the internet | :heavy_check_mark: | :heavy_check_mark: |
 | azure    	| azurerm_network_security_rule                 |	Ensure that RDP access is restricted from the internet | :heavy_check_mark: | :heavy_check_mark: |
 | azure    	| azurerm_network_security_group                |	Ensure that RDP access is restricted from the internet | :heavy_check_mark: | :heavy_check_mark: |
 | azure    	| azurerm_mysql_server                          |	Ensure 'Enforce SSL connection' is set to 'ENABLED' for MySQL Database Server | :heavy_check_mark: | :heavy_check_mark: |
 | azure    	| azurerm_mysql_firewall_rule                   |	Ensure no SQL Databases allow ingress from 0.0.0.0/0 (ANY IP) | :x: | :x: |
 | azure    	| azurerm_mssql_server_security_alert_policy    |	Ensure that 'Threat Detection types' is set to 'All' | :x: | :x: |
 | azure    	| azurerm_mssql_server_security_alert_policy    |	Ensure that 'Send Alerts To' is enabled for MSSQL servers | :x: | :x: |
 | azure    	| azurerm_mssql_server_security_alert_policy    |	Ensure that 'Email service and co-administrators' is 'Enabled' for MSSQL servers | :x: | :x: |
 | azure    	| azurerm_monitor_log_profile                   |	Ensure that Activity Log Retention is set 365 days or greater | :x: | :x: |
 | azure    	| azurerm_monitor_log_profile                   |	Ensure audit profile captures all the activities | :x: | :x: |
 | azure    	| azurerm_mariadb_firewall_rule                 |	Ensure no SQL Databases allow ingress from 0.0.0.0/0 (ANY IP) | :x: | :x: |
 | azure    	| azurerm_managed_disk                          |	Ensure Azure managed disk have encryption enabled | :heavy_check_mark: | :heavy_check_mark: |
 | azure    	| azurerm_linux_virtual_machine                 |	Ensure Azure Instance does not use basic authentication(Use SSH Key Instead) | :heavy_check_mark: | :heavy_check_mark: |
 | azure    	| azurerm_kubernetes_cluster                    |	Ensure RBAC is enabled on AKS clusters | :x: | :x: |
 | azure    	| azurerm_kubernetes_cluster                    |	Ensure Kube Dashboard is disabled | :x: | :x: |
 | azure    	| azurerm_kubernetes_cluster                    |	Ensure AKS logging to Azure Monitoring is Configured | :x: | :x: |
 | azure    	| azurerm_kubernetes_cluster                    |	Ensure AKS has an API Server Authorized IP Ranges enabled | :x: | :x: |
 | azure    	| azurerm_kubernetes_cluster                    |	Ensure AKS cluster has Network Policy configured | :x: | :x: |
 | azure    	| azurerm_key_vault_secret                      |	Ensure that the expiration date is set on all secrets | :x: | :x: |
 | azure    	| azurerm_app_service                           |	Ensure web app redirects all HTTP traffic to HTTPS in Azure App Service | :x: | :x: |
 | azure    	| azurerm_app_service                           |	Ensure web app is using the latest version of TLS encryption | :x: | :x: |
 | azure    	| azurerm_app_service                           |	Ensure the web app has 'Client Certificates (Incoming client certificates)' set | :x: | :x: |
 | azure    	| azurerm_app_service                           |	Ensure that Register with Azure Active Directory is enabled on App Service | :x: | :x: |
 | azure    	| azurerm_app_service                           |	Ensure that 'HTTP Version' is the latest if used to run the web app | :x: | :x: |
 | azure    	| azurerm_app_service                           |	Ensure App Service Authentication is set on Azure App Service | :x: | :x: |
 | azure    	| azure_security_group_rule                     |	Ensure that SSH access is restricted from the internet | :heavy_check_mark: | :heavy_check_mark: |
 | azure    	| azure_security_group_rule                     |	Ensure that RDP access is restricted from the internet | :heavy_check_mark: | :heavy_check_mark: |
 | aws      	| aws_api_gateway_method                        |	Ensure there is no open access to back-end resources through API | :x: | :x: |
 | aws      	| aws_api_gateway_stage                         |	Ensure API Gateway has X-Ray Tracing enabled | :x: | :x: |
 | aws      	| aws_api_gateway_method_settings               |	Ensure API gateway cache data is encrypted | :x: | :x: |
 | aws      	| aws_cloudtrail                                |	Ensure CloudTrail logs are encrypted at rest using KMS CMKs | :x: | :x: |
 | aws      	| aws_cloudtrail                                |	Ensure CloudTrail log file validation is enabled | :x: | :x: |
 | aws      	| aws_cloudtrail                                |	Ensure CloudTrail is enabled in all Regions | :x: | :x: |
 | aws      	| aws_db_instance                               |	Ensure all data stored in the RDS is securely encrypted at rest | :x: | :x: |
 | aws      	| aws_db_instance                               |	Ensure all data stored in the RDS bucket is not public accessible | :x: | :x: |
 | aws      	| aws_db_security_group                         |	Ensure every security groups rule has a description | :x: | :x: |
 | aws      	| aws_docdb_cluster                             |	Ensure DocDB Logging is enabled | :x: | :x: |
 | aws      	| aws_docdb_cluster                             |	Ensure DocDB is encrypted at rest (default is unencrypted) | :x: | :x: |
 | aws      	| aws_docdb_cluster_instance                    |	Ensure DocDB is encrypted at rest (default is unencrypted) | :x: | :x: |
 | aws      	| aws_dynamodb_table                            |	Ensure Dynamodb point in time recovery (backup) is enabled | :x: | :x: |
 | aws      	| aws_dynamodb_table                            |	Ensure Dynamodb point in time recovery (backup) is enabled | :x: | :x: |
 | aws      	| aws_ebs_volume                                |	Ensure all data stored in the EBS is securely encrypted | :x: | :x: |
 | aws      	| aws_ebs_volume                                |	Ensure all data stored in the EBS is securely encrypted | :x: | :x: |
 | aws      	| aws_ecr_repository                            |	Ensure ECR image scanning on push is enabled | :x: | :x: |
 | aws      	| aws_ecr_repository                            |	Ensure ECR image scanning on push is enabled | :x: | :x: |
 | aws      	| aws_ecr_repository_policy                     |	Ensure ECR policy is not set to public | :x: | :x: |
 | aws      	| aws_ecr_repository_policy                     |	Ensure ECR policy is not set to public | :x: | :x: |
 | aws      	| aws_ecs_cluster                               |	Ensure container insights are enabled on ECS cluster | :x: | :x: |
 | aws      	| aws_ecs_cluster                               |	Ensure container insights are enabled on ECS cluster | :x: | :x: |
 | aws      	| aws_efs_file_system                           |	Ensure EFS is securely encrypted | :x: | :x: |
 | aws      	| aws_efs_file_system                           |	Ensure EFS is securely encrypted | :x: | :x: |
 | aws      	| aws_eks_cluster                               |	Ensure EKS Cluster has Secrets Encryption Enabled | :x: | :x: |
 | aws      	| aws_eks_cluster                               |	Ensure Amazon EKS public endpoint not accessible to 0.0.0.0/0 | :x: | :x: |
 | aws      	| aws_eks_cluster                               |	Ensure Amazon EKS public endpoint disabled | :x: | :x: |
 | aws      	| aws_eks_cluster                               |	Ensure Amazon EKS control plane logging enabled for all log types | :x: | :x: |
 | aws      	| aws_eks_cluster                               |	Ensure EKS Cluster has Secrets Encryption Enabled | :x: | :x: |
 | aws      	| aws_eks_cluster                               |	Ensure Amazon EKS public endpoint not accessible to 0.0.0.0/0 | :x: | :x: |
 | aws      	| aws_eks_cluster                               |	Ensure Amazon EKS public endpoint disabled | :x: | :x: |
 | aws      	| aws_eks_cluster                               |	Ensure Amazon EKS control plane logging enabled for all log types | :x: | :x: |
 | aws      	| aws_elasticache_replication_group             |	Ensure all data stored in the Elasticache Replication Group is securely encrypted at transit and has auth token | :x: | :x: |
 | aws      	| aws_elasticache_replication_group             |	Ensure all data stored in the Elasticache Replication Group is securely encrypted at transit | :x: | :x: |
 | aws      	| aws_elasticache_replication_group             |	Ensure all data stored in the Elasticache Replication Group is securely encrypted at rest | :x: | :x: |
 | aws      	| aws_elasticache_replication_group             |	as auth token | :x: | :x: |
 | aws      	| aws_elasticache_replication_group             |	Ensure all data stored in the Elasticache Replication Group is securely encrypted at transit | :x: | :x: |
 | aws      	| aws_elasticache_replication_group             |	Ensure all data stored in the Elasticache Replication Group is securely encrypted at rest | :x: | :x: |
 | aws      	| aws_elasticache_security_group                |	Ensure every security groups rule has a description | :x: | :x: |
 | aws      	| aws_elasticsearch_domain                      |	Ensure Elasticsearch Domain enforces HTTPS | :x: | :x: |
 | aws      	| aws_elasticsearch_domain                      |	Ensure all Elasticsearch has node-to-node encryption enabled | :x: | :x: |
 | aws      	| aws_elasticsearch_domain                      |	Ensure all data stored in the Elasticsearch is securely encrypted at rest | :x: | :x: |
 | aws      	| aws_globalaccelerator_accelerator             |	Ensure Global Accelerator accelerator has flow logs enabled | :x: | :x: |
 | aws      	| aws_iam_group_policy                          |	Ensure no IAM policies documents allow '*' as a statement's actions | :x: | :x: |
 | aws      	| aws_iam_group_policy                          |	Ensure IAM policies that allow full '*-*' administrative privileges are not created | :x: | :x: |
 | aws      	| aws_iam_policy                                |	Ensure no IAM policies documents allow '*' as a statement's actions | :x: | :x: |
 | aws      	| aws_iam_policy                                |	Ensure IAM policies that allow full '*-*' administrative privileges are not created | :x: | :x: |
 | aws      	| aws_iam_policy_attachment                     |	Ensure IAM policies are attached only to groups or roles (Reducing access management complexity may in-turn reduce opportunity for a principal to inadvertently receive or retain excessive privileges.) | :x: | :x: |
 | aws      	| aws_iam_role                                  |	Ensure IAM role allows only specific services or principals to assume it | :x: | :x: |
 | aws      	| aws_iam_role                                  |	Ensure IAM role allows only specific principals in account to assume it | :x: | :x: |
 | aws      	| aws_iam_role_policy                           |	Ensure no IAM policies documents allow '*' as a statement's actions | :x: | :x: |
 | aws      	| aws_iam_role_policy                           |	Ensure IAM policies that allow full '*-*' administrative privileges are not created | :x: | :x: |
 | aws      	| aws_iam_user_policy                           |	Ensure no IAM policies documents allow '*' as a statement's actions | :x: | :x: |
 | aws      	| aws_iam_user_policy                           |	Ensure IAM policies that allow full '*-*' administrative privileges are not created | :x: | :x: |
 | aws      	| aws_iam_user_policy                           |	Ensure IAM policies are attached only to groups or roles (Reducing access management complexity may in-turn reduce opportunity for a principal to inadvertently receive or retain excessive privileges.) | :x: | :x: |
 | aws      	| aws_iam_user_policy_attachment                |	Ensure IAM policies are attached only to groups or roles (Reducing access management complexity may in-turn reduce opportunity for a principal to inadvertently receive or retain excessive privileges.) | :x: | :x: |
 | aws      	| aws_instance                                  |	Ensure all data stored in the Launch configuration EBS is securely encrypted | :x: | :x: |
 | aws      	| aws_kinesis_stream                            |	Ensure Kinesis Stream is securely encrypted | :x: | :x: |
 | aws      	| aws_kms_key                                   |	Ensure rotation for customer created CMKs is enabled | :x: | :x: |
 | aws      	| aws_lambda_function                           |	X-ray tracing is enabled for Lambda | :x: | :x: |
 | aws      	| aws_lambda_function                           |	Ensure no hard coded AWS access key and secret key exists in lambda environment | :x: | :x: |
 | aws      	| aws_launch_configuration                      |	Ensure all data stored in the Launch configuration EBS is securely encrypted | :x: | :x: |
 | aws      	| aws_launch_template                           |	Ensure Instance Metadata Service Version 1 is not enabled | :x: | :x: |
 | aws      	| aws_mq_broker                                 |	Ensure MQ Broker logging is enabled | :x: | :x: |
 | aws      	| aws_mq_broker                                 |	Ensure MQ Broker is not publicly exposed | :x: | :x: |
 | aws      	| aws_msk_cluster                               |	Ensure MSK Cluster logging is enabled | :x: | :x: |
 | aws      	| aws_msk_cluster                               |	Ensure MSK Cluster encryption in rest and transit is enabled | :x: | :x: |
 | aws      	| aws_neptune_cluster                           |	Ensure Neptune storage is securely encrypted | :x: | :x: |
 | aws      	| aws_rds_cluster_instance                      |	Ensure all data stored in the RDS bucket is not public accessible | :x: | :x: |
 | aws      	| aws_redshift_cluster                          |	Ensure Redshift Cluster logging is enabled | :x: | :x: |
 | aws      	| aws_redshift_cluster                          |	Ensure all data stored in the Redshift cluster is securely encrypted at rest | :x: | :x: |
 | aws      	| aws_redshift_security_group                   |	Ensure every red shift security groups rule has a description | :x: | :x: |
 | aws      	| aws_s3_bucket                                 |	Ensure S3 bucket does not allow an action with any Principal | :x: | :x: |
 | aws      	| aws_s3_bucket                                 |	Ensure all data stored in the S3 bucket have versioning enabled | :x: | :x: |
 | aws      	| aws_s3_bucket_policy                          |	Ensure S3 bucket policy does not allow an action with any Principal | :x: | :x: |
 | aws      	| aws_s3_bucket_public_access_block             |	Ensure S3 bucket has ignore public ACLs enabled | :x: | :x: |
 | aws      	| aws_s3_bucket_public_access_block             |	Ensure S3 bucket has block public policy enabled | :x: | :x: |
 | aws      	| aws_s3_bucket_public_access_block             |	Ensure S3 bucket has block public ACLS enabled | :x: | :x: |
 | aws      	| aws_s3_bucket_public_access_block             |	Ensure S3 bucket has 'restrict_public_bucket' enabled | :x: | :x: |
 | aws      	| aws_sagemaker_notebook_instance               |	Ensure all data stored in the Sagemaker is securely encrypted at rest | :x: | :x: |

**Comment by reedloden** [comment]
Is there a link to said spreadsheet?

**Comment by owenrumney** [comment]
Yeah, we'll make it available soon - we need to clean it up

**Comment by michal-franc** [comment]
We are waiting :P

**Comment by liamg** [comment]
@michal-franc See the original post :)

**Comment by michal-franc** [comment]
`aws | aws_eks_cluster | Ensure Amazon EKS public endpoint not accessible to 0.0.0.0/0` - is already covered by AWS068

**Comment by dirsigler** [comment]
I would also love to see checks for [Scaleway ](https://www.scaleway.com/) and [Hetzner](https://www.hetzner.com/).
