### ISSUE TITLE
Add scoop.sh (windows brew.sh, alternative to choco) as install option

### ISSUE THREAD

**Issue by dennisroche** [aquasecurity/tfsec#865]
**Is your feature request related to a problem? Please describe.**
No. Prefer to use https://scoop.sh as Chocolatey requires admin permissions

**Describe the solution you'd like**
Add `scoop install tfsec` to README.md

**Describe alternatives you've considered**
N/A

**Additional context**
Already opened the PR to add to scoop, see https://github.com/ScoopInstaller/Main/pull/2445

https://scoop.sh monitors GitHub releases and will auto-update 🐏

**Comment by owenrumney** [comment]
Please feel free to re-open when tfsec is part of scoop
