### ISSUE TITLE
Version reported by command line states it's a locally built version

### ISSUE THREAD

**Issue by grantkl** [aquasecurity/tfsec#885]
**Describe the bug**
Updated to TFSec 0.48.2 via brew this morning and went to check the version on the command line and it states it's a locally built version.

```
$ /usr/local/Cellar/tfsec/0.48.2/bin/tfsec -v
You are running a locally built version of tfsec.
$ /usr/local/Cellar/tfsec/0.48.2/bin/tfsec --version
You are running a locally built version of tfsec.
```

**Comment by owenrumney** [comment]
Hey @grantkl  - we're in the process of moving all the repos under the `aquasecurity` org and there are some teething issues - I've fixed this in https://github.com/aquasecurity/tfsec/pull/886 so will be resolved in the next release
