### ISSUE TITLE
Issue with scanning local modules inside subdirectories

### ISSUE THREAD

**Issue by nandhae** [aquasecurity/tfsec#887]
**Description**
When we run `tfsec .` in a parent directory with multiple subdirectories of terraform modules each with or without having own local modules folders, those local modules are not scanned properly because the lookup for them is always happening in the first subdirectory. We end up having false negatives as a result if we don't notice the debug logs.

1. Run `tfsec . --verbose` in a directory with multiple directories as shown below:
![image](https://user-images.githubusercontent.com/11366094/125905299-8a756887-8f7f-41b6-8b55-954de2c44b91.png)

2. You can see that the first level subdirectory scanning happens properly and then it tries to load the modules for each subdirectory and fails for both modules. As you can see in the logs below, It happens because the look up for local modules always happen in the first subdirectory. (In the example `1_component`)

![Screenshot 2021-07-16 at 12 17 12 PM](https://user-images.githubusercontent.com/11366094/125904916-da594fd7-f617-47a0-a94c-5150555bb472.png)

**Expected behaviour**
While loading local modules for each subdirectories in the tree, It looks for the modules in the same subdirectory path.

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina

**Additional context**
tfsec version: `0.48.2`

**Comment by owenrumney** [comment]
I think maybe first thing to try is to 

1. Get latest version, we've done a pretty important fix to modules in results (deduplication was causing an issue)
2. Try running with `--force-all-dirs` - normally it stops at the first folder it finds with a valid tf file, by using force all dirs it will run against every tf file from the top down

**Comment by nandhae** [comment]
Yes, We are using `--force-all-dirs` to solve the problem for now. I'll also raise a PR to support the same in `tfsec-sarif-action`.

tried the latest release `0.48.6` and the same problem persists.

**Comment by owenrumney** [comment]
for the sarif PR, could you make it a `TFSEC_ARGS` type argument, then people can add multiple things if they want?

**Comment by nandhae** [comment]
I was also thinking that would make more sense. Thanks for the input. Will add it that way. 👍🏾

**Comment by owenrumney** [comment]
#aquasecurity/tfsec-sarif-action/issues/11 closes this
