### ISSUE TITLE
An empty string is treated as a sensitive value

### ISSUE THREAD

**Issue by aston-r** [aquasecurity/tfsec#898]
Hello,

I have a lot of variables with empty values and the new version of tfsec reports error:
```
tfsec-linux-amd64 -v
0.49.1
```

````
  [GEN001][CRITICAL] Variable 'variable.actionmq_db_password' includes a potentially sensitive default value.
  variables.tf:302


     299 | variable "actionmq_db_password" {
     300 |   description = "Password for the master DB user"
     301 |   type        = string
     302 |   default     = ""    string: ""
     303 | }
     304 | 
     305 | variable "actionmq_db_port" {

  Impact:     Default values could be exposing sensitive data
  Resolution: Don't include sensitive data in variable defaults
````

I previously used 0.42.1 and it did not report an error if the variable had an empty string.

**Comment by liamg** [comment]
Hi @aston-r, this is because a value is explicitly being set for the field via the default, even though it is empty. Would it be possible to remove the default for this case?

**Comment by aston-r** [comment]
@liamg 

Thank you for your prompt reply. I know the root cause, and it can be fixed by setting the default value to null. I just have a  lot of affected terrafrom modules and I need to  create the a lot of merge request to fix all of them. So before proceeding with  this routine task maybe we can return the previous behavior of tfsec, since the old version of tfsec did not report any issue with  "" as default value

**Comment by liamg** [comment]
I think the best solution here is to use v0.42.1 until your changes are made. Alternatively, you could use `--exclude GEN001` as a temporary measure.

The change in behaviour in tfsec is a fix to ensure that people setting empty passwords etc. have these occurrences highlighted as security issues so we would, unfortunately, be reluctant to revert the change as it may affect others negatively.
