### ISSUE TITLE
Erratic behaviour with AWS099 and inline ignores

### ISSUE THREAD

**Issue by mkielar** [aquasecurity/tfsec#939]
**Describe the bug**
Tfsec `0.48.6` randomly fails despite inline ignores are present.

**To Reproduce**
1. We were not able to reproduce this behaviour locally. 
2. We're running tfsec in an Ubuntu 20.04 based docker container working as a Gitlab Job Image.
    - We have terraform structured into multiple `environment` folders and each environment uses deploys a lambda function
    - The lambda function module contains an `aws_iam_policy_document` that contains wildcards
    - We've added inline ignores (see: Screenshots) that should mute tfsec `AWS099` errors

**Expected behavior**
The AWS099 errors are muted for all environments when the inline ignores are present

**Actual behavior**
There are two issues:
1. Running `tfsec` as explained above randomly fails jobs with the error message as shown in _Screenshots_.
2. Running `tfsec` locally (tested on 0.48.6 and 0.50.7, on Fedora Core 30 running on WSL under Windows 10 Pro), on a very simple template containing only that `aws_iam_policy_document` and nothing else seems to completely ignore the wildcards regardless of whether the inline ingores are present or not, and does not report AWS099 errors.

**Screenshots**
```
  Result 1
  [AWS099][HIGH] Resource 'module.[MASKED]:data.aws_iam_policy_document.lambda_example1' defines a policy with wildcarded actions.
  /builds/[MASKED]/terraform/modules/[MASKED]/deployment_lambda_example1.tf:19-22
      16 | data "aws_iam_policy_document" "lambda_example1" {
      17 |   statement {
      18 |     sid = "AllowS3AccessExample"
      19 |     actions = [    list: ["s3:Describe*", "s3:List*"]
      20 |       "s3:Describe*", #tfsec:ignore:AWS099
      21 |       "s3:List*",     #tfsec:ignore:AWS099
      22 |     ]
      23 |     resources = ["*"] #tfsec:ignore:AWS099
      24 |   }
      25 | }
  Impact:     Overly permissive policies may grant access to sensitive resources
  Resolution: Specify the exact permissions required, and to which resources they should apply instead of using wildcards.
  More Info:
  - https://tfsec.dev/docs/aws/AWS099/ 
  - https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html 
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 running as Docker Container executing Gitlab Job

**Comment by owenrumney** [comment]
Hey @mkielar - In v0.50.6 AWS099 was reworked to be more selective - see https://github.com/aquasecurity/tfsec/pull/918
I'm not sure I completely understand, are you saying that running locally with v0.50.7 the check passes?

**Comment by liamg** [comment]
I think issue (2) is because the policy document needs to be attached to one of `aws_iam_policy`, `aws_iam_user_policy`, `aws_iam_group_policy`, `aws_iam_role_policy`.

**Comment by liamg** [comment]
I'm using this example and can't seem to reproduce the issue - are you able to reproduce it with the following code in your container?
```hcl
resource "aws_iam_role_policy" "test_policy" {
	name = "test_policy"
	role = aws_iam_role.test_role.id

	policy = data.aws_iam_policy_document.s3_policy.json
}

resource "aws_iam_role" "test_role" {
	name = "test_role"
}


data "aws_iam_policy_document" "s3_policy" {
	statement {
		sid = "AllowS3AccessExample"
		actions = [    
			"s3:Describe*", #tfsec:ignore:AWS099
	      	"s3:List*",     #tfsec:ignore:AWS099
      	]
      	resources = ["*"] #tfsec:ignore:AWS099 
    }
}
```

**Comment by liamg** [comment]
I was able to reproduce the ignores not being respected by switching the line endings in the file to CRLF (`sed $'s/$/\r/' -i main.tf`.) I've just pushed a change to strip out `0x0d` (CR) when processing ignore rules which I'm hoping may solve your issue.

My theory is the behaviour may seem erratic as if the last dev to push code contained CRLF endings, the ignores would not work and vice versa.

Please try `v0.51.2` and let us know if the issue persists.

**Comment by mkielar** [comment]
Hi, thanks, we'll definitely give it a go, but - because of our delivery process, and because we've only seen this issue on our Gitlab Runners - this will take a couple of days. The hint with line endings may be a good one - we have devs working with Windows, MacOS and a couple of diffrent Linuxes, perhaps we messed up the line endings somehow, although it still would not explain why sometimes we got a pass and sometimes we got a fail on Gitlab Runner, running tfsec on the same piece of code.

We'll run some tests and get back to you.

**Comment by mkielar** [comment]
Quick but non-conclusive update: Locally, on Windows 10, `0.51.3` handles the ignores correctly, despite CRLFs in file, where 0.50.7 and 0.48.6 did not. That would confirm it might have been new-line issue, but I'll need some more time for a conclusive result from our Gitlab Runners. Anyway, thanks again for quick investigation!

**Comment by liamg** [comment]
@mkielar That's awesome, thanks. Let's hope it solves the runners issue too :crossed_fingers:
