### ISSUE TITLE
Exempt actions that do not support resource-level permissions from AWS099 (ie, some autoscaling actions)

### ISSUE THREAD

**Issue by LesterTheTester** [aquasecurity/tfsec#961]
**Describe the bug**
AWS099 is a welcome addition, but some actions do allow resource-level permissions, i.e the autoscaling actions outlined here:

https://docs.aws.amazon.com/autoscaling/ec2/userguide/control-access-using-iam.html

"Not all Amazon EC2 Auto Scaling actions support resource-level permissions. For actions that don't support resource-level permissions, you must use "*" as the resource"

There are probably others like this and TFsec should automatically exempt them, so over-zealous engineers like me don't try to restrict policies that can't be restricted and break them.

**To Reproduce**
1. Create an IAM policy containing a resource = ["*"] identifier for an autoscaling action, i.e "autoscaling:DescribeTags"

**Expected behavior**
AWS099 is not triggered since these policies cannot be restricted to resources

**Comment by owenrumney** [comment]
Hey @LesterTheTester, thanks for the report, can you confirm which version you're using? 

On Friday last week AWS099 was updated to be more specific based on AWS documentation

**Comment by LesterTheTester** [comment]
ah, this was on v50.0.3...looks like I don't need the ignore comment anymore.

thank you!
