### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by IshakAtLEGO** [aquasecurity/tfsec#966]
**Is your feature request related to a problem? Please describe.**
Config file section on webpage is using Legacy Id and older severity descriptions : 

```yaml
---
severity_overrides:
  CUS002: ERROR
  AWS025: INFO
```
It's misleading - we had a CI pipeline that stopped working because we followed documentation and used Legacy Id in stead of new Id.

**Describe the solution you'd like**
1. Replace examples with the new values for ID and severity.
2. Add list of valid severity strings to `Config file` page
3. Add severity info to rule page :
 > ### S3 Access block should block public ACL
> ID: aws-s3-block-public-acls
> Legacy ID: AWS074
> **Severity :  HIGH**

**Comment by owenrumney** [comment]
Hey @IshakAtLEGO  - thanks for the report - this bug has been fixed such that it supports both old and new codes. It'll be in the next release, later today

**Comment by owenrumney** [comment]
Fixed in v0.53.1
