### ISSUE TITLE
tfsec `v0.53.1` new checks causing failures

### ISSUE THREAD

**Issue by johannesgiorgis-galvanize** [aquasecurity/tfsec#973]
**Describe the bug**
The new AWS checks (api gateway cache settings) that were introduced in tfsec `v0.53.1` are causing failures in our CI builds. We don't have caching enabled so it's simply the default rules it doesn't like:

```
resource "aws_api_gateway_method_settings" "api_post_method_settings" {
  rest_api_id = aws_api_gateway_rest_api.private_api.id
  stage_name  = aws_api_gateway_stage.private_api_prod_stage.stage_name
  method_path = "XXX/XXX/XXX"

  settings {
    logging_level      = "INFO"
    data_trace_enabled = true
    metrics_enabled    = true
  }
}
```

Usually we would be able to find the AWS code and add it to our ignore list, but I can't find it in the docs. The first link provided by the error (https://tfsec.dev/docs/aws/apigateway/enable-cache-encryption#aws/apigateway) is also incorrect as it leads to a page not found.

1. Could you please provide guidance on what is the correct AWS code to add to our ignore list? It would be great if the docs were updated ahead of time so when we encounter the failure, we can use the docs to add the code to our ignore list.
2. Is there a place we can track to see upcoming changes?

Thanks!

**To Reproduce**
1. Install tfsec `v0.53.1`
2. Run against AWS API Gateway resource that doesn't have any caching enabled for its `aws_api_gateway_method_settings`
4. See below error

```
  [aws-apigateway-enable-cache-encryption][MEDIUM] Resource 'aws_api_gateway_method_settings.container_id_post_method_settings' uses default value for settings.cache_data_encrypted

...

  Impact:     Data stored in the cache that is unencrypted may be vulnerable to compromise
  Resolution: Enable cache encryption

  More Info:
  - https://tfsec.dev/docs/aws/apigateway/enable-cache-encryption#aws/apigateway 
  - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_method_settings#cache_data_encrypted
```

**Expected behavior**
This was a new check introduced so the failure we expect. It would be great to be provided the corresponding AWS code so we can either fix the issue or add the AWS code to our ignore list.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux (docker), MacOS

**Additional context**

**Comment by owenrumney** [comment]
Hey @johannesgiorgis-galvanize - the documentation build failed for this release so the new checks didn't get added. 

1. The correct code for this is `aws-apigateway-enable-cache-encryption`
2. The imminent checks are in #763 - although a lot of these exist already. Very soon we will maintain a visible sheet of all the new to be checks

Sorry this has caused you a headache, we're looking at ways to catch the build failure sooner

**Comment by owenrumney** [comment]
v0.53.2 should be pushing the documentation and have a fix to this check.

documentation here - https://tfsec.dev/docs/aws/api-gateway/enable-cache-encryption/#aws/api-gateway

**Comment by johannesgiorgis-galvanize** [comment]
Thanks @owenrumney - appreciate the prompt response as always!
