### ISSUE TITLE
CloudStack support

### ISSUE THREAD

**Issue by danieliziourov-form3** [aquasecurity/tfsec#977]
**Is your feature request related to a problem? Please describe.**

I'd lke `tfsec` to support [CloudStack Terraform provider](https://github.com/apache/cloudstack-terraform-provider).

**Describe the solution you'd like**

Basic rules and documentation how to contribute new ones.

**Describe alternatives you've considered**

[Terrascan](https://github.com/accurics/terrascan) because it has Rego-based rules that I'm more familiar with.

**Comment by owenrumney** [comment]
Hey guys, your names seem familiar

Will look at adding this ASAP

**Comment by owenrumney** [comment]
![image](https://user-images.githubusercontent.com/3049157/127681501-b50495db-e8cc-4e70-b9af-02f5531e5713.png)
One down, a few to go https://tfsec.dev/docs/cloudstack/home/

**Comment by liamg** [comment]
Closing this for now as basic support exists - future checks can be handled in individual issues.
