### ISSUE TITLE
For Each aws-s3-specify-public-access-block incorrectly failed

### ISSUE THREAD

**Issue by jtcarnes** [aquasecurity/tfsec#994]
**Describe the bug**

aws-s3-specify-public-access-block shows erroneous violation if using with for_each blocks.

**To Reproduce**

```tf
resource "aws_s3_bucket" "example" {
  for_each      = toset(["example1", "example2"])
  bucket        = each.key
  .....
}

resource "aws_s3_bucket_public_access_block" "example" {
  for_each = aws_s3_bucket.example
  bucket   = each.value.id

  block_public_acls       = true
  block_public_policy     = true
}
```
This code will fail the rule listed, despite defining an aws_s3_bucket_public_access_block

**Expected behavior**
The rule should pass if aws_s3_bucket_public_access_block includes a for_each that references the bucket

**Info**

- OS: mac Big Sur (11.5)
- tfsec:
```shell
tfsec --version
0.55.1
```

**Comment by jtcarnes** [comment]
Looks like there was a previous issue with this same problem, #892 .

**Comment by liamg** [comment]
Thanks, this is fixed and will shortly be available in the next release. I've added a test for your exact case to prevent future regressions too.
